const app = document.querySelector('#app');
const overlayRoot = document.querySelector('#overlay-root');
const toastRoot = document.querySelector('#toast-root');
const demoLayer = document.querySelector('#demo-layer');
let overlayReturnFocus=null;
if(typeof MutationObserver!=='undefined')new MutationObserver(()=>{
 if(!overlayRoot.children.length)return;
 if(!overlayReturnFocus)overlayReturnFocus=document.activeElement;
 document.querySelector('.app-shell')?.setAttribute('inert','');
 document.querySelector('.demo-bar')?.setAttribute('inert','');
 const dialog=overlayRoot.querySelector('[role="dialog"]')||overlayRoot.querySelector('article,form');
 if(dialog){dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');const heading=dialog.querySelector('h2');if(heading&&!dialog.getAttribute('aria-labelledby')){heading.id=heading.id||'overlay-heading';dialog.setAttribute('aria-labelledby',heading.id)}dialog.setAttribute('tabindex','-1');dialog.focus()}
}).observe(overlayRoot,{childList:true});

const groupMeta = {'Bea’s Family':'Family','Milo’s Family':'Family','Wedding Party':'Wedding Party','College Friends':'Friends','Work Friends':'Friends','Family Friends':'Friends'};

const starterGuests = [
['carolyn-bennett','Carolyn Bennett','Bea’s Family','Bennett Family','Chicken','','Mother of the bride · prefers aisle','Thomas Bennett','','Hosts of the wedding.','Confirmed','magnolia'],
['thomas-bennett','Thomas Bennett','Bea’s Family','Bennett Family','Beef','','','Carolyn Bennett','','Father of the bride.','Confirmed','magnolia'],
['olivia-bennett','Olivia Bennett','Bea’s Family','Bennett Family','Vegetarian','','','Sam Bennett','','Bea’s sister.','Confirmed','magnolia'],
['sam-bennett','Sam Bennett','Bea’s Family','Bennett Family','Chicken','','','Olivia Bennett','','','Confirmed','magnolia'],
['margaret-bennett','Margaret Bennett','Bea’s Family','Bennett Family','Chicken','Gluten Free','Seat away from speakers','Carolyn Bennett','','Grandmother of the bride.','Confirmed','peony'],
['elaine-parker','Elaine Parker','Bea’s Family','Parker Household','Beef','','','Nina Parker','Richard Parker','Seat apart from Richard if there is room.','Confirmed','peony'],
['richard-parker','Richard Parker','Bea’s Family','Parker Household','Chicken','','','','Elaine Parker','Seat apart from Elaine if there is room.','Confirmed','peony'],
['nina-parker','Nina Parker','Bea’s Family','Parker Household','Vegetarian','','','Elaine Parker','','','Confirmed','peony'],
['david-parker','David Parker','Bea’s Family','Single Guest','Beef','','','','','','Confirmed','peony'],
['sophie-bennett','Sophie Bennett','Bea’s Family','Single Guest','Chicken','','','','','','Confirmed','gardenia'],
['teresa-romano','Teresa Romano','Milo’s Family','Romano Family','Chicken','','','Victor Romano','','Mother of the groom.','Confirmed','magnolia'],
['victor-romano','Victor Romano','Milo’s Family','Romano Family','Beef','','','Teresa Romano','','Father of the groom.','Confirmed','magnolia'],
['lucia-romano','Lucia Romano','Milo’s Family','Romano Family','Vegetarian','Nut Allergy','','Marco Romano','','Alert catering team.','Confirmed','magnolia'],
['marco-romano','Marco Romano','Milo’s Family','Romano Family','Chicken','','','Lucia Romano','','','Confirmed','magnolia'],
['helena-costa','Helena Costa','Milo’s Family','Costa Family','Chicken','','','Paul Costa','','','Confirmed','gardenia'],
['paul-costa','Paul Costa','Milo’s Family','Costa Family','Beef','','','Helena Costa','','','Confirmed','gardenia'],
['sofia-romano','Sofia Romano','Milo’s Family','Single Guest','Vegetarian','','','','','','Confirmed','gardenia'],
['luca-romano','Luca Romano','Milo’s Family','Single Guest','Chicken','','','','','','Confirmed','gardenia'],
['gianna-costa','Gianna Costa','Milo’s Family','Costa Family','Chicken','Dairy Free','','Anthony Costa','','','Confirmed','gardenia'],
['anthony-costa','Anthony Costa','Milo’s Family','Costa Family','Beef','','','Gianna Costa','','','Confirmed','gardenia'],
['tyler-brooks','Tyler Brooks','Wedding Party','Single Guest','Beef','','','Tasha Brooks','','Best man.','Confirmed','camellia'],
['zoe-davis','Zoe Davis','Wedding Party','Single Guest','Vegetarian','','','','','Maid of honor.','Confirmed','camellia'],
['evan-chen','Evan Chen','Wedding Party','Chen Household','Chicken','','','Priya Shah','','','Confirmed','camellia'],
['priya-shah','Priya Shah','Wedding Party','Chen Household','Vegetarian','Vegan','','Evan Chen','','','Confirmed','camellia'],
['marcus-reed','Marcus Reed','Wedding Party','Single Guest','Beef','','','','','','Confirmed','camellia'],
['danielle-kim','Danielle Kim','Wedding Party','Single Guest','Chicken','','','','','','Confirmed','camellia'],
['noah-williams','Noah Williams','Wedding Party','Single Guest','Chicken','','','','','','Confirmed','camellia'],
['avery-james','Avery James','Wedding Party','Single Guest','Vegetarian','','','','','','Confirmed','camellia'],
['caitlin-cloyd','Caitlin Cloyd','College Friends','Single Guest','Chicken','','','','','Knows the college group well.','Confirmed','dahlia'],
['jordan-ellis','Jordan Ellis','College Friends','Single Guest','Chicken','','Prefer aisle seat','Tyler Brooks, Tasha Brooks','','Knows most of the college group but not Bea’s work friends.','Confirmed',null],
['maya-carter','Maya Carter','College Friends','Single Guest','Vegetarian','','','','','','Pending',null],
['tasha-brooks','Tasha Brooks','College Friends','Single Guest','Vegetarian','','','Tyler Brooks, Jordan Ellis','','','Confirmed',null],
['aaron-lee','Aaron Lee','College Friends','Single Guest','Chicken','Shellfish Allergy','','','','','Confirmed',null],
['rachel-green','Rachel Green','College Friends','Green Household','Beef','','','Leo Green','','College roommate of Bea.','Confirmed',null],
['leo-green','Leo Green','College Friends','Green Household','Chicken','','','Rachel Green','','','Confirmed',null],
['brooke-sinclair','Brooke Sinclair','College Friends','Single Guest','Vegetarian','','','','','Traveling in on Friday.','Added Late',null],
['natalie-ford','Natalie Ford','Work Friends','Ford Household','Chicken','','','Winston Cole','','','Confirmed','peony'],
['winston-cole','Winston Cole','Work Friends','Single Guest','Beef','','','Natalie Ford','','','Confirmed','peony'],
['deja-harris','Deja Harris','Work Friends','Single Guest','Vegetarian','','','','','','Confirmed','dahlia'],
['isabel-grant','Isabel Grant','Work Friends','Single Guest','Chicken','Gluten Free','','','','','Confirmed','dahlia'],
['felix-ward','Felix Ward','Work Friends','Single Guest','Beef','','','','','','Confirmed','dahlia'],
['kiara-moss','Kiara Moss','Work Friends','Single Guest','Chicken','','','','','','Confirmed','rose'],
['evelyn-moore','Evelyn Moore','Family Friends','Moore Household','Chicken','','','James Moore','','Longtime friends of Bea’s parents.','Confirmed','peony'],
['james-moore','James Moore','Family Friends','Moore Household','Beef','','','Evelyn Moore','','','Confirmed','peony'],
['amelia-clarke','Amelia Clarke','Family Friends','Clarke Family','Vegetarian','','','Robert Clarke, Linda Clarke','','','Confirmed','rose'],
['robert-clarke','Robert Clarke','Family Friends','Clarke Family','Beef','','','Amelia Clarke, Linda Clarke','','','Confirmed','rose'],
['linda-clarke','Linda Clarke','Family Friends','Clarke Family','Chicken','','','Amelia Clarke, Robert Clarke','','','Confirmed','rose'],
['helen-young','Helen Young','Family Friends','Single Guest','Chicken','','Needs step-free route','','','Planner to confirm entrance route.','Pending',null]
].map(([id,name,group,household,meal,dietary,accessibility,keepNear,separate,notes,status,table])=>({id,name,group,household,meal,dietary,accessibility,keepNear,separate,notes,status,table}));
const STORAGE_KEY='tss-seating-studio-demo-v4';
const cloneStarter=()=>JSON.parse(JSON.stringify(starterGuests));
function loadGuests(){try{const saved=localStorage.getItem(STORAGE_KEY);const parsed=saved?JSON.parse(saved):null;return Array.isArray(parsed)&&parsed.length<=1000&&parsed.every(g=>g&&typeof g.name==='string'&&typeof g.id==='string'&&['group','household','meal','dietary','accessibility','keepNear','separate','notes','status'].every(k=>typeof g[k]==='string')&&(g.table===null||['magnolia','gardenia','camellia','peony','dahlia','rose'].includes(g.table)))?parsed:cloneStarter()}catch{return cloneStarter()}}
let guests=loadGuests();
let undoStack=[];
let tourStep=0;
const tables=[{id:'magnolia',number:1,name:'Magnolia',capacity:8,note:'Near the couple'},{id:'gardenia',number:2,name:'Gardenia',capacity:8,note:'Garden side'},{id:'camellia',number:3,name:'Camellia',capacity:8,note:'Near the bar'},{id:'peony',number:4,name:'Peony',capacity:8,note:'Near the speakers'},{id:'dahlia',number:5,name:'Dahlia',capacity:8,note:'Near the dance floor'},{id:'rose',number:6,name:'Rose',capacity:8,note:'Terrace side'}];
let boardView='guests';
let currentRoute='landing',showAvailable=false,guestFilter='All Guests',guestSearch='',boardSearch='',draggedGuestId=null;
const seatedGuests=()=>guests.filter(g=>g.table&&g.status!=='Unable to Attend'&&g.status!=='Declined');
const unassignedGuests=()=>guests.filter(g=>!g.table&&g.status!=='Unable to Attend'&&g.status!=='Declined');
const tableGuests=id=>seatedGuests().filter(g=>g.table===id);
const tableById=id=>tables.find(t=>t.id===id);
const isAttending=g=>!['Declined','Unable to Attend'].includes(g.status);
const activeCount=()=>guests.filter(isAttending).length;
const esc=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const icon=name=>`<span aria-hidden="true">${{home:'⌂',move:'↔',list:'☷',check:'✓',search:'⌕',meal:'♨',note:'◇',user:'♙',plus:'＋',arrow:'→',people:'♙',warning:'!',info:'i',close:'×'}[name]||name}</span>`;
const guestSnapshot=()=>JSON.stringify(guests);
let saveAvailable=true;
function persistGuests(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(guests));saveAvailable=true}catch{saveAvailable=false;toast('Your browser could not save this change. Keep this tab open to continue.',6000)}}
function saveChange(label,before){undoStack.push({label,state:before});if(undoStack.length>12)undoStack.shift();persistGuests();updateDemoControls()}
function updateDemoControls(){const badge=document.querySelector('#check-count');if(badge){badge.textContent=chartIssues().length;badge.hidden=!chartIssues().length}const button=document.querySelector('#undo-change');if(button){button.disabled=!undoStack.length;button.textContent='↶ Undo';button.setAttribute('aria-label',undoStack.length?`Undo ${undoStack.at(-1).label}`:'Undo last change');button.title=undoStack.length?`Undo ${undoStack.at(-1).label}`:'No changes to undo'}}
function undoLastChange(){const change=undoStack.pop();if(!change)return;guests=JSON.parse(change.state);persistGuests();renderCurrent();toast(`Undid: ${change.label}`);updateDemoControls()}
function familiarFaceScore(tableId){const list=tableGuests(tableId);if(!list.length)return 0;const covered=list.filter(guest=>list.some(other=>other.id!==guest.id&&(other.group===guest.group||(guest.household!=='Single Guest'&&other.household===guest.household))));return Math.round(covered.length/list.length*100)}
function connectionAverage(){const seated=seatedGuests();if(!seated.length)return 0;const covered=seated.filter(guest=>{const list=tableGuests(guest.table);return list.some(other=>other.id!==guest.id&&(other.group===guest.group||(guest.household!=='Single Guest'&&other.household===guest.household)))});return Math.round(covered.length/seated.length*100)}
const setAdminMode=()=>{document.body.classList.remove('public-mode');document.body.classList.remove('landing-mode')};
function adminHeader(title,subtitle,actions=''){return `<header class="page-header"><div><p class="eyebrow">Bea + Milo · October 24, 2026</p><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div><div class="page-actions">${actions}<span class="avatar">BM</span></div></header>`}

function landing(){
 document.body.classList.remove('public-mode');
 document.body.classList.add('landing-mode');
 app.innerHTML=`<div class="studio-opening">
  <header class="opening-header"><a class="opening-brand" href="https://tinysitestudios.com/" aria-label="Tiny Site Studios home"><span class="opening-mark" aria-hidden="true">SS</span><span>Seating Studio<small>by Tiny Site Studios</small></span></a><a class="opening-inquiry" href="https://tinysitestudios.com/contact/" target="_blank" rel="noopener">Make it yours <span aria-hidden="true">↗</span></a></header>
  <section class="opening-hero" aria-labelledby="opening-title">
   <div class="opening-copy"><p class="opening-eyebrow"><span></span> A thoughtful welcome starts here</p><h1 id="opening-title">Good company.<br><em>Beautifully<br> seated.</em></h1><p class="opening-description">Bring your people together with a seating plan that feels as considered as the celebration itself.</p><div class="opening-actions"><button class="opening-primary" data-route="dashboard">Explore the planner <span aria-hidden="true">→</span></button><button class="opening-secondary" data-route="finder">See the guest experience <span aria-hidden="true">↗</span></button></div><p class="opening-reassurance">An interactive sample wedding. No sign-up needed.<br>Your changes stay in this browser, ready for you to pick up again.</p><div class="opening-details"><span><b>01</b> Arrange your people</span><span><b>02</b> Find a thoughtful fit</span><span><b>03</b> Welcome every guest</span></div></div>
   <div class="opening-scene" role="img" aria-label="A garden wedding setting for Bea and Milo"><div class="opening-scene-top"><span>A Seating Studio story</span><span>Est. together</span></div><div class="opening-couple"><span>The sample celebration</span><h2>Bea <i>&amp;</i> Milo</h2><p>October 24, 2026</p><div class="opening-rule"></div><em>A place for everyone.<br>A moment to remember.</em></div><span class="opening-scene-bottom">Designed around your people.</span></div>
  </section><footer class="opening-footer"><span>Small details. A warmer welcome.</span><span>A Tiny Site Studios experience</span></footer>
 </div>`;
}

function dashboard(){
 setAdminMode();const seated=seatedGuests().length,unassigned=unassignedGuests().length,percent=(seated+unassigned?Math.round(seated/(seated+unassigned)*100):0);
 app.innerHTML=`${adminHeader('Bea + Milo','October 24, 2026')}
 <section class="demo-welcome"><div><span class="eyebrow">Explore Bea + Milo’s sample wedding</span><strong>A thoughtful seat for everyone.</strong><p>Arrange your people, catch seating issues, and preview a beautiful welcome for every guest. Your demo changes stay in this browser.</p></div><div class="demo-entry-actions"><button data-route="seating">Try planning ${icon('arrow')}</button><button class="entry-secondary" data-route="finder">Preview the guest experience</button><button class="entry-tour" id="welcome-tour">Take a guided tour</button></div></section>
 <section class="metrics" aria-label="Seating summary"><article class="metric"><strong>${activeCount()}</strong><span>Guests</span></article><article class="metric"><strong>${seated}</strong><span>Seated</span></article><article class="metric"><strong>${unassigned}</strong><span>Unassigned</span></article><article class="metric"><strong>6</strong><span>Guest Tables</span></article></section>
 <section class="action-grid"><button class="action-card featured" data-route="seating"><i>${icon('move')}</i><strong>Arrange Seating</strong><p>Move guests between tables.</p><em>${icon('arrow')}</em></button><button class="action-card" data-route="guests"><i>${icon('list')}</i><strong>Guest List</strong><p>View meals, groups, dietary needs, accessibility notes, and details.</p><em>${icon('arrow')}</em></button><button class="action-card" data-route="checks"><i>${icon('check')}</i><strong>Check My Chart</strong><p>Find seating issues and things to review.</p><em>${icon('arrow')}</em></button><button class="action-card" data-route="finder"><i>${icon('search')}</i><strong>Guest Seat Finder</strong><p>Preview the guest-facing reception experience.</p><em>${icon('arrow')}</em></button></section>
 <section class="dashboard-lower"><article class="panel"><div class="panel-title"><h2>Seating Progress</h2><span>${unassigned?'In progress':'Complete'}</span></div><div class="progress-copy"><strong>${percent}% Complete</strong><span><b>${unassigned} guests</b> still need seats.</span></div><div class="progress-track"><i style="width:${percent}%"></i></div><button class="text-button" data-route="seating">Continue arranging ${icon('arrow')}</button></article><article class="panel"><div class="panel-title"><h2>Needs Attention</h2><button data-route="checks">View all</button></div><div class="alert-list">${dashboardAlerts()}</div></article></section>
 <section class="comfort-highlight"><div class="comfort-orbit"><span>${connectionAverage()}%</span><i></i><i></i><i></i></div><div><span class="eyebrow">Comfort Map · A Seating Studio signature</span><h2>Help every guest feel at home.</h2><p>${connectionAverage()}% of seated guests currently share a table with someone from their group or household. See who may appreciate a familiar face.</p></div><button class="secondary-button" data-comfort-map>Open Comfort Map ${icon('arrow')}</button></section>
 <section class="sweetheart-row"><div><span class="eyebrow">Sweetheart Table</span><strong>Bea + Milo</strong><small>2 seats · couple only</small></div><span>♡</span></section>`;
}
function dashboardAlerts(){const issues=chartIssues();return issues.slice(0,3).map(issue=>`<button class="mini-alert" data-route="checks"><i></i><span>${issue.title}</span><span aria-hidden="true">→</span></button>`).join('')||'<div class="empty-mini">Your chart is looking good.</div>'}

function guestCard(g,draggable=false){return `<article class="guest-card" data-guest-id="${g.id}" ${draggable?'draggable="true"':''} tabindex="0"><div class="guest-avatar">${g.name.split(' ').map(p=>p[0]).join('').slice(0,2)}</div><div class="guest-card-copy"><strong>${esc(g.name)}</strong><p>${esc(g.group)} · ${esc(g.meal)}</p><div class="guest-tags">${g.dietary?`<span>${esc(g.dietary)}</span>`:''}${g.accessibility?`<span class="note-tag">${icon('note')} Seating note</span>`:''}${g.household!=='Single Guest'?`<span>${icon('people')} ${esc(g.household.replace(' Household',''))}</span>`:''}</div></div><button class="grab" type="button" data-move-guest="${g.id}" aria-label="Move ${esc(g.name)}">Move</button></article>`}

function seatingBoard(){
 const guestScroll=app.querySelector('.unassigned-list')?.scrollTop||0;
 const tableScroll=app.querySelector('.table-grid')?.scrollTop||0;
 setAdminMode();const list=unassignedGuests().filter(g=>g.name.toLowerCase().includes(boardSearch.toLowerCase()));
 app.innerHTML=`${adminHeader('Arrange Seating','Choose Move beside a guest, or drag them to a table.',`<label class="availability-toggle"><input type="checkbox" id="available-toggle" ${showAvailable?'checked':''}><span></span> Show Available Seats</label>`)}<div class="board-summary"><span><b>${seatedGuests().length}</b> seated</span><span><b>${unassignedGuests().length}</b> unassigned</span><span><b>${tables.reduce((sum,t)=>sum+Math.max(0,t.capacity-tableGuests(t.id).length),0)}</b> open seats</span><span class="autosave">${saveAvailable?'✓ Saved in this browser':'Changes are only in this open tab'}</span></div><div class="board-view-switch" role="group" aria-label="Seating view"><button data-board-view="guests" aria-pressed="${boardView==='guests'}">Guests <span>${unassignedGuests().length} unassigned</span></button><button data-board-view="tables" aria-pressed="${boardView==='tables'}">Tables <span>${tables.length} tables</span></button></div><div class="seating-layout" data-mobile-view="${boardView}"><aside class="unassigned-panel" data-drop-target="unassigned"><div class="sticky-panel-title"><div><h2>Unassigned Guests</h2><b>${unassignedGuests().length}</b></div><label class="search-field compact">${icon('search')}<input id="board-search" aria-label="Search unassigned guests" placeholder="Search unassigned guests" value="${esc(boardSearch)}"></label></div><div class="unassigned-list" role="region" aria-label="Unassigned guests" tabindex="0">${list.map(g=>guestCard(g,true)).join('')||`<div class="empty-state">${boardSearch?'No guests match your search.':'Everyone has a seat. Open Tables to review your arrangement.'}</div>`}</div></aside><section class="tables-area"><div class="tables-heading"><div><span class="eyebrow">Reception room</span><h2>Guest Tables</h2></div><div class="legend"><span><i class="open-dot"></i> Open</span><span><i class="full-dot"></i> Full</span><span><i class="over-dot"></i> Over</span></div></div><div class="table-grid" role="region" aria-label="Guest tables" tabindex="0">${tables.map(tableCard).join('')}</div></section></div>`;wireDragDrop();
 app.querySelector('.unassigned-list').scrollTop=guestScroll;
 app.querySelector('.table-grid').scrollTop=tableScroll;
}
function tableCard(t){const list=tableGuests(t.id),count=list.length,open=t.capacity-count,state=count>t.capacity?'over':count===t.capacity?'full':'open',comfort=familiarFaceScore(t.id);return `<article class="table-card ${state} ${showAvailable&&open>0?'available-highlight':''} ${showAvailable&&open<=0?'recede':''}" data-drop-target="${t.id}"><button class="table-card-head" data-table-id="${t.id}"><span><small>Table ${t.number}</small><strong>${t.name}</strong></span><span class="occupancy ${state}">${count} / ${t.capacity}</span></button>${state==='over'?`<div class="capacity-flag">${icon('warning')} ${count-t.capacity} over capacity</div>`:showAvailable&&open>0?`<div class="seat-flag">${open} ${open===1?'seat':'seats'} available</div>`:''}<div class="table-comfort"><span>Seated with their group</span><div><i style="width:${comfort}%"></i></div><b>${comfort}%</b></div><div class="table-guest-list">${list.map(g=>`<div class="table-guest" draggable="true" data-guest-id="${g.id}"><button class="guest-name" data-guest-id="${g.id}" aria-label="Details for ${esc(g.name)}">${esc(g.name)}${g.accessibility?' <span title="Seating note">◇</span>':''}</button><button class="guest-move" data-move-guest="${g.id}" aria-label="Move ${esc(g.name)}">Move</button></div>`).join('')}</div><div class="table-drop-hint">Drop guest here</div></article>`}
function wireDragDrop(){document.querySelectorAll('[draggable="true"][data-guest-id]').forEach(card=>{card.addEventListener('dragstart',event=>{draggedGuestId=card.dataset.guestId;card.classList.add('dragging');event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',draggedGuestId)});card.addEventListener('dragend',()=>{card.classList.remove('dragging');document.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'))})});document.querySelectorAll('[data-drop-target]').forEach(target=>{target.addEventListener('dragover',event=>{event.preventDefault();target.classList.add('drag-over')});target.addEventListener('dragleave',event=>{if(!target.contains(event.relatedTarget))target.classList.remove('drag-over')});target.addEventListener('drop',event=>{event.preventDefault();target.classList.remove('drag-over');const id=event.dataTransfer.getData('text/plain')||draggedGuestId;requestMove(id,target.dataset.dropTarget==='unassigned'?null:target.dataset.dropTarget)})})}
function linkedGuest(g){if(g.household==='Single Guest')return null;return guests.find(other=>other.id!==g.id&&other.household===g.household&&other.status!=='Unable to Attend'&&other.status!=='Declined')}
function requestMove(id,target){const g=guests.find(x=>x.id===id);if(!g||g.table===target)return;const partner=linkedGuest(g);if(partner&&partner.table===g.table){showChoiceModal({title:`Move ${g.name.split(' ')[0]}?`,copy:`${g.name.split(' ')[0]} and ${partner.name.split(' ')[0]} are linked as the ${g.household}. You can keep them together or move one person.`,choices:[{label:`Move ${g.name.split(' ')[0]} only`,action:()=>attemptMove([g],target)},{label:`Move ${g.name.split(' ')[0]} + ${partner.name.split(' ')[0]}`,primary:true,action:()=>attemptMove([g,partner],target)}]})}else attemptMove([g],target)}
function attemptMove(moving,target,override=false){closeOverlay();if(target){const t=tableById(target),incoming=moving.filter(g=>g.table!==target).length;if(!override&&tableGuests(target).length+incoming>t.capacity){showChoiceModal({title:'This table is full.',copy:`${t.name} has ${tableGuests(target).length} of ${t.capacity} seats filled. You can still add ${moving.length>1?'them':'this guest'} if needed.`,warning:true,choices:[{label:'Cancel',action:closeOverlay},{label:'Add Anyway',primary:true,action:()=>attemptMove(moving,target,true)}]});return}}const before=guestSnapshot();moving.forEach(g=>g.table=target);saveChange(`move ${moving.length>1?'household':moving[0].name}`,before);if(tourStep===1&&moving.some(g=>g.id==='jordan-ellis')&&target==='dahlia')tourStep=2;if(tourStep===2&&target==='rose'&&moving.some(g=>g.id==='rachel-green')&&moving.some(g=>g.id==='leo-green'))tourStep=3;toast(`${moving.map(g=>g.name.split(' ')[0]).join(' + ')} moved to ${target?tableById(target).name:'Unassigned'}.`);renderCurrent();renderTour()}

function guestList(){
 setAdminMode();const filters=['All Guests','Unassigned','Bea’s Family','Milo’s Family','Wedding Party','Friends','Dietary Needs','Accessibility Notes'];let list=guests.filter(g=>g.name.toLowerCase().includes(guestSearch.toLowerCase()));if(guestFilter==='Unassigned')list=list.filter(g=>!g.table&&isAttending(g));else if(guestFilter==='Friends')list=list.filter(g=>(groupMeta[g.group]==='Friends'||g.group==='Friends'));else if(guestFilter==='Dietary Needs')list=list.filter(g=>g.dietary);else if(guestFilter==='Accessibility Notes')list=list.filter(g=>g.accessibility);else if(guestFilter!=='All Guests')list=list.filter(g=>g.group===guestFilter);
 app.innerHTML=`${adminHeader('Guest List','Meals, notes, households, and seating—all in one place.',`<button class="secondary-button" id="import-guests">Import spreadsheet</button><button class="primary-button" id="add-guest">${icon('plus')} Add Guest</button>`)}<div class="guest-tools"><label class="search-field">${icon('search')}<input id="guest-search" aria-label="Search guest list" placeholder="Search ${guests.length} guests" value="${esc(guestSearch)}"></label><div class="filter-row" role="group" aria-label="Filter guests">${filters.map(f=>`<button class="filter-pill ${guestFilter===f?'active':''}" data-filter="${f}" aria-pressed="${guestFilter===f}">${f}${f==='Unassigned'?` <b>${unassignedGuests().length}</b>`:''}</button>`).join('')}</div></div><div class="guest-list-head"><span>${list.length} guests</span><span>Guest details</span><span>Meal</span><span>Seating</span></div><section class="guest-list-table">${list.map(guestRow).join('')}</section>`;
}
function guestRow(g){const table=g.table?tableById(g.table):null;return `<button class="guest-row" data-guest-id="${g.id}"><span class="guest-primary"><i class="guest-avatar">${g.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</i><span><strong>${esc(g.name)}</strong><small>${esc(g.group)} · ${esc(g.household)}</small></span></span><span class="detail-chips">${g.dietary?`<i>${esc(g.dietary)}</i>`:''}${g.accessibility?`<i>${icon('note')} Seating note</i>`:''}${!g.dietary&&!g.accessibility?'<small>—</small>':''}</span><span>${esc(g.meal)}</span><span>${table?`<b>Table ${table.number}</b><small>${table.name}</small>`:`<b class="unassigned-text">${g.status==='Unable to Attend'?'Unable to Attend':'Unassigned'}</b><small>${g.status}</small>`}</span></button>`}

function chartIssues(){
 const items=[];
 tables.forEach(t=>{const count=tableGuests(t.id).length;if(count>t.capacity)items.push({type:'Capacity',tone:'warning',title:`${esc(t.name)} has ${count} guests but capacity is ${t.capacity}.`,copy:'Move a guest to an open table, or review the capacity with your venue.',button:`Review ${esc(t.name)}`,action:'table',target:t.id})});
 const seen=new Set();
 guests.filter(g=>isAttending(g)&&g.table&&g.separate).forEach(g=>g.separate.split(',').map(name=>name.trim()).forEach(name=>{const other=guests.find(x=>x.name===name&&isAttending(x)&&x.table===g.table);if(!other)return;const pair=[g.id,other.id].sort().join('|');if(seen.has(pair))return;seen.add(pair);items.push({type:'Guest Preference',tone:'warning',title:`${esc(g.name)} and ${esc(other.name)} are seated together.`,copy:'They are marked: <b>Separate If Possible</b>. Choose a table that works for them.',button:'Choose a new table',action:'move',target:other.id})}));
 if(unassignedGuests().length)items.push({type:'Unassigned Guests',tone:'warning',title:`${unassignedGuests().length} guests still need seats.`,copy:tables.filter(t=>tableGuests(t.id).length<t.capacity).map(t=>`${esc(t.name)}: ${t.capacity-tableGuests(t.id).length} open`).join(' · ')||'All tables are full. Review capacity with your venue.',button:'Seat these guests',action:'suggestions'});
 guests.filter(g=>isAttending(g)&&g.table&&g.accessibility).forEach(g=>{const t=tableById(g.table);if(/away from speakers/i.test(g.accessibility)&&/near the speakers/i.test(t.note))items.push({type:'Accessibility',tone:'info',title:`${esc(g.name)} requested a seat away from speakers.`,copy:`${esc(t.name)} is near the speakers.`,button:'Review seating',action:'guest',target:g.id})});
 return items;
}
function checkIssues(){
 setAdminMode();const items=chartIssues();
 app.innerHTML=`${adminHeader('Check My Chart','A quick review of capacity, guest preferences, and seating notes.',`<button class="secondary-button" data-route="seating">Back to Seating Board</button>`)}<div class="review-summary"><div><span class="review-count">${items.length}</span><span><strong>${items.length} ${items.length===1?'Thing':'Things'} to Review</strong><small>Suggestions only—you’re always in control.</small></span></div><span class="chart-health">${items.length?'Needs a quick look':'Looking good'}</span></div><section class="review-list">${items.map(item=>`<article class="review-card ${item.tone}"><div class="review-icon">${item.tone==='info'?icon('info'):icon('warning')}</div><div><span class="eyebrow">${item.type}</span><h2>${item.title}</h2><p>${item.copy}</p></div><button class="secondary-button" data-check-action="${item.action}" ${item.target?`data-target="${item.target}"`:''}>${item.button} ${icon('arrow')}</button></article>`).join('')||'<article class="all-clear"><span>✓</span><h2>Your chart looks ready.</h2><p>No issues found in the checks available here. Confirm any remaining seating notes with your venue.</p><button class="primary-button" data-route="finder">Preview Guest Seat Finder</button></article>'}</section>`;
}

function guestFinder(){
 document.body.classList.add('public-mode');app.innerHTML=`<div class="finder-page"><header class="finder-nav"><button data-route="dashboard">← Planner view</button><div><span>BEA</span><i>+</i><span>MILO</span></div><small>Reception Companion</small></header><main class="finder-main"><section class="finder-card"><p class="wedding-date">OCTOBER TWENTY-FOUR · TWO THOUSAND TWENTY-SIX</p><h1>Bea <i>+</i> Milo</h1><div class="flourish">❦</div><h2>Find Your Seat</h2><p class="finder-welcome">We’re so happy you’re here.</p><form id="finder-form"><label for="finder-input">Enter your first or last name</label><div><input id="finder-input" type="search" maxlength="100" autocomplete="off" aria-describedby="finder-help" placeholder="Try “Caitlin Cloyd”"><button type="submit">Find Me</button></div></form><p id="finder-help" class="finder-help">Try Caitlin Cloyd, or search Bennett to choose from matching names.</p><div id="finder-result" aria-live="polite" aria-atomic="true"></div></section><aside class="companion-preview"><span class="eyebrow">Tonight’s companion</span><h3>Everything you need,<br>right when you need it.</h3><div class="companion-list"><span class="active">01 <b>Find My Seat</b></span><span>02 <b>Guestbook Live</b></span><span class="future">03 <b>Tonight’s Schedule</b><small>Coming later</small></span><span class="future">04 <b>Menu & Cocktails</b><small>Coming later</small></span></div></aside></main><section class="qr-preview"><div class="qr-sign"><small>BEA + MILO</small><h2>Find Your Seat</h2><p>Sample sign design</p><div class="qr-placeholder" aria-label="QR code placeholder">${Array.from({length:49},(_,i)=>`<i class="${[0,1,2,6,7,8,12,14,16,18,20,22,24,26,28,30,32,34,36,40,41,42,46,47,48].includes(i)?'on':''}"></i>`).join('')}</div><em>Display only · this sample code does not scan.</em></div><div><span class="eyebrow">Reception sign preview</span><h2>One simple scan at the welcome table.</h2><p>A personalized welcome sign can bring guests to their seat finder and Guestbook Live. This is a preview of the sign design.</p></div></section><footer class="finder-footer">A TINY SITE STUDIOS DIGITAL EXPERIENCE</footer></div>`;
}
function renderFinderResult(g){const result=document.querySelector('#finder-result');if(!g){result.innerHTML='<div class="finder-not-found"><strong>We couldn’t find that name.</strong><p>Try a first name, last name, or ask a member of the wedding team.</p></div>';return}if(!g.table){result.innerHTML=`<div class="finder-not-found"><strong>${esc(g.name)}, your table is being finalized.</strong><p>Please see Lily from the wedding team when you arrive.</p></div>`;return}const table=tableById(g.table);result.innerHTML=`<article class="seat-result"><span>We found you.</span><h3>${esc(g.name)}</h3><p>You’re seated at</p><h2>Table ${table.number}</h2><strong>${table.name}</strong><small>${table.note}</small><button id="show-tablemates" aria-expanded="false" aria-controls="tablemates">See Who’s at My Table</button><div id="tablemates" hidden><b>At ${table.name}</b>${tableGuests(table.id).map(person=>`<span>${esc(person.name)}${person.id===g.id?' · You':''}</span>`).join('')}</div></article><section class="memory-actions"><span class="eyebrow">While You’re Here…</span><h3>Help us remember tonight.</h3><div><a href="https://wall.tinysitestudios.com/bea-milo" target="_blank" rel="noopener">▧ <b>Share a Photo</b></a><a href="https://wall.tinysitestudios.com/bea-milo" target="_blank" rel="noopener">✎ <b>Leave a Message</b></a><a href="https://wall.tinysitestudios.com/bea-milo" target="_blank" rel="noopener">◉ <b>Record a Video</b></a></div><a class="guestbook-link" href="https://wall.tinysitestudios.com/bea-milo" target="_blank" rel="noopener">Visit Guestbook Live →</a></section>`;if(tourStep===4&&g.id==='caitlin-cloyd'){tourStep=5;renderTour()}result.scrollIntoView({behavior:'smooth',block:'nearest'})}

const normalizeName=value=>String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase().replace(/\s+/g,' ');
function findGuestMatches(query){const name=normalizeName(query);if(!name)return [];const list=guests.filter(isAttending);const exact=list.filter(g=>normalizeName(g.name)===name);return exact.length?exact:list.filter(g=>normalizeName(g.name).includes(name))}
function searchFinder(query){
 const result=document.querySelector('#finder-result');
 if(!normalizeName(query)){result.innerHTML='<div class="finder-not-found"><strong>Enter your name to find your table.</strong><p>A first name, last name, or full name works.</p></div>';return}
 const matches=findGuestMatches(query);
 if(matches.length<=1){renderFinderResult(matches[0]);return}
 result.innerHTML=`<section class="finder-matches"><h3>Which name is yours?</h3><p>${matches.length} matches. Choose your name, or enter your full name to narrow the list.</p><div>${matches.map(g=>`<button data-finder-guest="${g.id}">${esc(g.name)} <span aria-hidden="true">→</span></button>`).join('')}</div></section>`;
}
function showMovePicker(id){
 const g=guests.find(x=>x.id===id);if(!g)return;
 overlayRoot.innerHTML=`<div class="modal-scrim" data-close-overlay><article class="move-modal" role="dialog" aria-modal="true" aria-labelledby="move-title"><button class="modal-close" data-close-overlay aria-label="Close move options">×</button><span class="eyebrow">Choose a seat</span><h2 id="move-title">Move ${esc(g.name)}</h2><p>Choose a table below. Linked household members can move together in the next step.</p><div class="move-options">${tables.map(t=>{const available=t.capacity-tableGuests(t.id).length;return `<button data-move-target="${t.id}" data-moving="${g.id}" ${g.table===t.id?'disabled':''}><span><small>Table ${t.number}</small><strong>${esc(t.name)}</strong></span><span class="move-availability ${available<=0?'is-full':''}">${g.table===t.id?'Current table':available>0?`${available} open ${available===1?'seat':'seats'}`:available===0?'Full · review capacity':`${-available} over capacity`}</span></button>`}).join('')}</div>${g.table?`<button class="secondary-button" data-move-target="unassigned" data-moving="${g.id}">Return to unassigned</button>`:''}</article></div>`;
}

function showGuestDrawer(id){const g=guests.find(x=>x.id===id),table=g.table?tableById(g.table):null;overlayRoot.innerHTML=`<div class="drawer-scrim" data-close-overlay></div><aside class="guest-drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><header><div><span class="eyebrow">Guest details</span><h2 id="drawer-title">${esc(g.name)}</h2><p>${esc(g.status)}</p></div><button data-close-overlay aria-label="Close">${icon('close')}</button></header><div class="drawer-body"><dl class="detail-list"><div><dt>Group</dt><dd>${esc(g.group)}</dd></div><div><dt>Household / Party</dt><dd>${esc(g.household)}</dd></div><div><dt>Meal</dt><dd>${esc(g.meal)}</dd></div><div><dt>Dietary / Allergy</dt><dd>${esc(g.dietary||'None')}</dd></div><div><dt>Accessibility / Seating Notes</dt><dd>${esc(g.accessibility||'None')}</dd></div><div><dt>Keep Near</dt><dd>${g.keepNear?g.keepNear.split(', ').map(x=>`<span class="person-chip">${esc(x)}</span>`).join(''):'None'}</dd></div><div><dt>Separate If Possible</dt><dd>${esc(g.separate||'None')}</dd></div><div><dt>Planner Notes</dt><dd>${esc(g.notes||'None')}</dd></div></dl><div class="drawer-control"><label>Status<select id="drawer-status">${['Confirmed','Pending','Declined','Unable to Attend','Added Late'].map(s=>`<option ${g.status===s?'selected':''}>${s}</option>`).join('')}</select></label><button class="secondary-button" id="update-status">Update Status</button></div><div class="drawer-control"><label>Move to Table<select id="drawer-table"><option value="">Unassigned</option>${tables.map(t=>`<option value="${t.id}" ${g.table===t.id?'selected':''}>Table ${t.number} · ${t.name}</option>`).join('')}</select></label><button class="secondary-button" id="drawer-move">Move Guest</button></div></div><footer><button class="text-button" id="edit-guest" disabled title="Full guest editing is not available in this demo">Full editing · coming later</button><span>${table?`Currently at Table ${table.number} · ${table.name}`:'Currently unassigned'}</span></footer></aside>`;setTimeout(()=>overlayRoot.querySelector('.guest-drawer')?.classList.add('open'),10);document.querySelector('#update-status').onclick=()=>updateGuestStatus(g,document.querySelector('#drawer-status').value);document.querySelector('#drawer-move').onclick=()=>requestMove(g.id,document.querySelector('#drawer-table').value||null);document.querySelector('#edit-guest').onclick=()=>toast('Guest editing is represented by the controls in this prototype.')}
function updateGuestStatus(g,status){const before=guestSnapshot(),oldTable=g.table?tableById(g.table):null;g.status=status;if(status==='Unable to Attend'||status==='Declined')g.table=null;saveChange(`update ${g.name}`,before);closeOverlay();if(oldTable&&(status==='Unable to Attend'||status==='Declined'))toast(`New opening — ${oldTable.name} now has ${oldTable.capacity-tableGuests(oldTable.id).length} available seat${oldTable.capacity-tableGuests(oldTable.id).length===1?'':'s'}.`,5000);else toast(`${g.name} is now ${status}.`);renderCurrent()}

function showTableDetail(id){const t=tableById(id),list=tableGuests(id),meals=list.reduce((acc,g)=>(acc[g.meal]=(acc[g.meal]||0)+1,acc),Object.create(null)),dietary=list.filter(g=>g.dietary),access=list.filter(g=>g.accessibility);overlayRoot.innerHTML=`<div class="modal-scrim" data-close-overlay><article class="table-modal" role="dialog" aria-modal="true" aria-labelledby="table-title"><button class="modal-close" data-close-overlay aria-label="Close">${icon('close')}</button><span class="eyebrow">Table ${t.number}</span><h2 id="table-title">${t.name}</h2><p>${list.length} of ${t.capacity} seats</p><div class="round-table"><div><small>TABLE ${t.number}</small><strong>${t.name}</strong></div>${list.map((g,i)=>`<button style="--i:${i};--n:${Math.max(list.length,8)}" data-guest-id="${g.id}"><i>${g.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</i><span>${esc(g.name.split(' ')[0])}</span></button>`).join('')}</div><section class="table-summary"><h3>At This Table</h3><div><article><span class="eyebrow">Meals</span>${Object.entries(meals).map(([meal,count])=>`<p><b>${count}</b> ${esc(meal)}</p>`).join('')}</article><article><span class="eyebrow">Dietary</span>${dietary.length?dietary.map(g=>`<p><b>1</b> ${esc(g.dietary)}</p>`).join(''):'<p>None noted</p>'}</article><article><span class="eyebrow">Accessibility</span>${access.length?access.map(g=>`<p><b>1</b> ${esc(g.accessibility)}</p>`).join(''):'<p>None noted</p>'}</article></div></section><footer><button disabled>Print Table Card <small>Coming Soon</small></button><button disabled>Export Details <small>Coming Soon</small></button></footer></article></div>`}
function showChoiceModal({title,copy,choices,warning=false}){overlayRoot.innerHTML=`<div class="modal-scrim"><article class="choice-modal" role="dialog" aria-modal="true"><div class="choice-icon ${warning?'warning':''}">${warning?'!':'↔'}</div><h2>${esc(title)}</h2><p>${esc(copy)}</p><div>${choices.map((c,i)=>`<button class="${c.primary?'primary-button':'secondary-button'}" data-choice="${i}">${esc(c.label)}</button>`).join('')}</div></article></div>`;choices.forEach((choice,i)=>overlayRoot.querySelector(`[data-choice="${i}"]`).onclick=choice.action)}
function showAddGuest(){overlayRoot.innerHTML=`<div class="modal-scrim" data-close-overlay><form class="add-modal" id="add-form"><button type="button" class="modal-close" data-close-overlay>${icon('close')}</button><span class="eyebrow">Guest list</span><h2>Add a Guest</h2><label>Full name<input name="name" required maxlength="100" placeholder="Guest name"></label><label>Group<select name="group">${Object.keys(groupMeta).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Meal<select name="meal"><option>Chicken</option><option>Beef</option><option>Vegetarian</option></select></label><button class="primary-button" type="submit">Add to Unassigned</button></form></div>`}
function showWelcome(){
  overlayRoot.innerHTML=`<div class="modal-scrim welcome-scrim"><article class="welcome-modal" role="dialog" aria-modal="true" aria-labelledby="welcome-title"><div class="welcome-photo"><span>TINY SITE STUDIOS</span><strong>Seating<br>Studio</strong><p>A calmer way to seat every guest.</p></div><div class="welcome-copy"><button class="modal-close" data-close-overlay aria-label="Close">${icon('close')}</button><span class="eyebrow">Live, hands-on demo</span><h2 id="welcome-title">Plan Bea + Milo’s reception.</h2><p>Move guests, catch awkward pairings, and see exactly what guests experience when they scan the sign.</p><ol><li><b>Move Jordan</b><span>Choose Move beside Jordan, then select Dahlia.</span></li><li><b>Keep a couple together</b><span>Move Rachel + Leo in one step.</span></li><li><b>Find your seat</b><span>Search “Caitlin Cloyd” as a guest.</span></li></ol><div class="welcome-actions"><button class="primary-button" id="start-tour">Start the 2-minute tour</button><button class="secondary-button" data-close-overlay>Explore on my own</button></div><small>Every visitor gets a private demo copy. Change anything—you can always reset.</small></div></article></div>`;
}
function resetDemo(notify=true){guests=cloneStarter();undoStack=[];persistGuests();tourStep=0;demoLayer.innerHTML='';renderCurrent();updateDemoControls();if(notify)toast('Demo reset to the original Bea + Milo seating plan.')}
function applyScenario(name){const before=guestSnapshot();guests=cloneStarter();if(name==='nearly'){[['jordan-ellis','dahlia'],['maya-carter','rose'],['tasha-brooks','dahlia'],['aaron-lee','rose']].forEach(([id,table])=>guests.find(g=>g.id===id).table=table)}if(name==='wedding-day'){['margaret-bennett','kiara-moss'].forEach(id=>{const guest=guests.find(g=>g.id===id);guest.status='Unable to Attend';guest.table=null})}if(name==='fresh'){guests.forEach(guest=>{guest.table=null;if(guest.status==='Unable to Attend'||guest.status==='Declined')guest.status='Confirmed'})}saveChange(`load ${name} scenario`,before);closeOverlay();renderCurrent();toast(name==='starter'?'Starter seating restored.':name==='nearly'?'Loaded: Almost finished.':name==='wedding-day'?'Loaded: Wedding-day changes.':'Loaded: Fresh guest list.')}
function showDemoData(){overlayRoot.innerHTML=`<div class="modal-scrim" data-close-overlay><article class="data-modal"><button class="modal-close" data-close-overlay>${icon('close')}</button><span class="eyebrow">Demo data</span><h2>Choose a starting point</h2><p>Each option replaces only your browser’s copy. Other visitors never see your changes.</p><div class="scenario-grid"><button data-scenario="starter"><i>40</i><span><b>Messy starter</b><small>8 unassigned · 4 issues</small></span></button><button data-scenario="nearly"><i>44</i><span><b>Almost finished</b><small>4 unassigned · useful checks</small></span></button><button data-scenario="wedding-day"><i>38</i><span><b>Wedding-day changes</b><small>2 guests can’t attend</small></span></button><button data-scenario="fresh"><i>0</i><span><b>Fresh guest list</b><small>Seat all 48 from scratch</small></span></button></div><button class="danger-text" id="reset-demo">↺ Reset to original demo</button></article></div>`}
function startTour(){resetDemo(false);boardView='guests';tourStep=1;navigate('seating');renderTour()}
function renderTour(){demoLayer.innerHTML='';if(!tourStep)return;const steps={1:{title:'1 · Move one guest',copy:'Choose Move beside Jordan Ellis, then select Dahlia, Table 5. You can also drag him there.',tip:'Dahlia has four open seats.'},2:{title:'2 · Keep a couple together',copy:'Choose Move beside Rachel Green, select Rose, then choose “Move Rachel + Leo.”',tip:'Households stay flexible—you decide.'},3:{title:'3 · See the public side',copy:'You’ve made room for your people. Now see the welcome your guests experience.',button:'Open Guest Seat Finder'},4:{title:'4 · Find a seat',copy:'Search for Caitlin Cloyd and reveal everyone seated at Dahlia.',tip:'Try a first name or last name too.'},5:{title:'You did it',copy:'Make this experience yours, with wedding colors, guest details, and a welcome that feels like you.',button:'Finish tour'}};const step=steps[tourStep];demoLayer.innerHTML=`<aside class="tour-guide"><div><span class="tour-progress">${[1,2,3,4].map(i=>`<i class="${tourStep>=i?'active':''}"></i>`).join('')}</span><button data-tour-close aria-label="Close tour">×</button></div><strong>${step.title}</strong><p>${step.copy}</p>${step.tip?`<small>${step.tip}</small>`:''}${step.button?`<button class="tour-next" data-tour-next>${step.button} →</button>`:''}${tourStep===5?'<a class="tour-inquiry" href="https://tinysitestudios.com/contact/" target="_blank" rel="noopener">Create my wedding experience ↗</a>':''}</aside>`}
function showComfortMap(){const cards=tables.map(table=>{const list=tableGuests(table.id),isolated=list.filter(guest=>!list.some(other=>other.id!==guest.id&&(other.group===guest.group||(guest.household!=='Single Guest'&&other.household===guest.household))));return `<article><div><span>Table ${table.number}</span><b>${table.name}</b></div><strong>${familiarFaceScore(table.id)}%</strong><div class="comfort-bar"><i style="width:${familiarFaceScore(table.id)}%"></i></div><p>${isolated.length?`${isolated.map(g=>g.name).join(', ')} ${isolated.length===1?'is':'are'} the only guest from ${isolated.length===1?'their':'each'} circle.`:'Everyone shares a table with someone from their group or household.'}</p></article>`}).join('');overlayRoot.innerHTML=`<div class="modal-scrim" data-close-overlay><article class="comfort-modal"><button class="modal-close" data-close-overlay>${icon('close')}</button><span class="eyebrow">Comfort Map</span><h2>Seated with their group</h2><p>Capacity tells you whether guests fit. Comfort Map highlights guests seated away from their group or household.</p><div class="comfort-total"><strong>${connectionAverage()}%</strong><span>of seated guests share a table with someone from their circle or household.</span></div><div class="comfort-grid">${cards}</div><small>Based on the groups and households you provide. Shared group membership does not always mean guests know each other.</small></article></div>`}
async function copyDemoLink(){const url=location.origin+location.pathname;try{await navigator.clipboard.writeText(url);toast('Demo link copied—ready to share.')}catch{toast('Copy the link from your browser to share this demo.')}}
let importDraft=null;
function showGuestImport(){
 importDraft=null;
 overlayRoot.innerHTML=`<div class="modal-scrim" data-close-overlay><article class="import-modal" role="dialog" aria-modal="true" aria-labelledby="import-title"><button class="modal-close" data-close-overlay aria-label="Close import">×</button><span class="eyebrow">Bring your people</span><h2 id="import-title">Import your guest list</h2><p>Start with our template. One person per row; only Full Name is required.</p><div class="import-downloads"><a class="secondary-button" href="seating-studio-guest-template.xlsx" download>Download Excel template</a><a class="text-button" href="seating-studio-guest-template.csv" download>CSV template</a></div><p class="import-help">In Excel, save the <b>Guests</b> tab as <b>CSV UTF-8</b>. In Google Sheets, download that tab as CSV. Then choose the CSV file below.</p><label class="import-file-label">Choose your CSV file<input type="file" id="import-file" accept=".csv,text/csv" aria-describedby="import-privacy"></label><p id="import-privacy" class="import-help">Up to 1,000 guests · 1 MB maximum. This demo reads the file on your device. Imports stay in this browser and are not shared with wedding guests.</p><fieldset class="import-mode"><legend>How should we use this list?</legend><label><input type="radio" name="import-mode" value="append" checked> Add to my current ${guests.length} guests</label><label><input type="radio" name="import-mode" value="replace"> Replace my current guest list</label></fieldset><div id="import-preview" aria-live="polite"><p class="import-help">Your preview will appear here before anything changes.</p></div></article></div>`;
}
async function readGuestImport(input){
 importDraft=null;const file=input.files?.[0],preview=document.querySelector('#import-preview');
 if(!file){preview.innerHTML='';return}
 preview.textContent='Reading your guest list…';
 try{
  if(!/\.csv$/i.test(file.name))throw new Error('Choose a CSV file. Save the Guests tab as CSV UTF-8 first.');
  if(file.size>1048576)throw new Error('Choose a CSV file smaller than 1 MB.');
  const text=await file.text();
  if(document.querySelector('#import-file')!==input)return;
  importDraft={...GuestImport.prepare(text,tables),filename:file.name};renderImportPreview();
 }catch(error){if(document.querySelector('#import-file')===input)preview.innerHTML=`<p class="import-error" role="alert">${esc(error.message)}</p>`}
}
function importReview(){
 if(!importDraft)return null;
 const replace=document.querySelector('[name="import-mode"]:checked')?.value==='replace';
 const errors=[...importDraft.errors],warnings=[...importDraft.warnings];
 const duplicateExisting=!replace&&importDraft.guests.some(g=>guests.some(old=>normalizeName(old.name)===normalizeName(g.name)));
 if(duplicateExisting)warnings.push('Some names already appear in your current list. They will be added as separate guests, not merged.');
 const total=importDraft.guests.length+(replace?0:guests.length);
 if(total>1000)errors.push(`This would create ${total} guests. The demo supports up to 1,000. Choose a smaller list or replace the current list.`);
 const combined=[...(replace?[]:guests),...importDraft.guests];
 tables.forEach(t=>{const count=combined.filter(g=>isAttending(g)&&g.table===t.id).length;if(count>t.capacity)warnings.push(`${t.name} would have ${count} guests for ${t.capacity} seats. Check My Chart will flag this after import.`)});
 return {replace,errors,warnings,total,duplicates:importDraft.duplicates||duplicateExisting};
}
function renderImportPreview(){
 const review=importReview();if(!review)return;
 const {errors,warnings,total,replace,duplicates}=review;
 const notice=(items,style)=>items.length?`<div class="${style}"><ul>${items.slice(0,20).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${items.length>20?`<p>And ${items.length-20} more. Correct the file and choose it again.</p>`:''}</div>`:'';
 document.querySelector('#import-preview').innerHTML=`<div class="import-preview-heading"><h3>${importDraft.guests.length} guests in your file</h3><span>${esc(importDraft.filename)}</span></div>${notice(errors,'import-error')}${notice(warnings,'import-warning')}<p>${replace?`Your current ${guests.length} guests and their seats will be replaced.`:`Your current guests and their seats will stay.`} Your list will contain <b>${total} guests</b>. You can undo the import.</p><div class="import-preview-table" role="region" aria-label="Guest import preview" tabindex="0"><table><thead><tr><th>Name / household</th><th>Group / meal</th><th>RSVP / table</th><th>Notes</th></tr></thead><tbody>${importDraft.guests.map(g=>`<tr><td><strong>${esc(g.name||'Missing name')}</strong><small>${esc(g.household)}</small></td><td>${esc(g.group)}<small>${esc(g.meal)}</small></td><td>${esc(g.status)}<small>${g.table?esc(tableById(g.table).name):'Unassigned'}</small></td><td>${[['Dietary',g.dietary],['Accessibility',g.accessibility],['Keep near',g.keepNear],['Separate',g.separate],['Planner',g.notes]].filter(([,value])=>value).map(([label,value])=>`<small><b>${label}:</b> ${esc(value)}</small>`).join('')||'—'}</td></tr>`).join('')}</tbody></table></div>${!errors.length&&duplicates?'<label class="import-duplicate-check"><input type="checkbox" id="import-duplicates"> I reviewed repeated names. Keep each row as a separate guest.</label>':''}<div class="import-footer"><span>${errors.length?'Fix the listed issues and choose your file again.':'Ready when you are. Nothing changes until you confirm.'}</span><button class="primary-button" id="confirm-import" ${errors.length||duplicates?'disabled':''}>${replace?'Replace list with':'Add'} ${importDraft.guests.length} guests</button></div>`;
}
function confirmGuestImport(){
 const review=importReview();
 if(!review||review.errors.length||(review.duplicates&&!document.querySelector('#import-duplicates')?.checked))return;
 const before=guestSnapshot(),ids=new Set(guests.map(g=>g.id));
 const incoming=importDraft.guests.map((g,i)=>{let id=`import-${Date.now()}-${i}`;while(ids.has(id))id+='x';ids.add(id);return {...g,id}});
 guests=review.replace?incoming:[...guests,...incoming];
 saveChange('import guest list',before);guestSearch='';guestFilter='All Guests';boardSearch='';
 closeOverlay();navigate('guests');toast(`Imported ${incoming.length} guests. Use Undo to restore your previous list.`,6000);
}
function closeOverlay(){importDraft=null;overlayRoot.innerHTML='';document.querySelector('.app-shell')?.removeAttribute('inert');document.querySelector('.demo-bar')?.removeAttribute('inert');if(overlayReturnFocus?.isConnected)overlayReturnFocus.focus();overlayReturnFocus=null}function toast(message,duration=3000){toastRoot.innerHTML=`<div class="toast">✓ <span>${esc(message)}</span></div>`;setTimeout(()=>{toastRoot.innerHTML=''},duration)}
function renderCurrent(){document.body.classList.toggle('landing-mode',currentRoute==='landing');({landing,dashboard,seating:seatingBoard,guests:guestList,checks:checkIssues,finder:guestFinder})[currentRoute]();document.querySelectorAll('.nav-item').forEach(item=>{item.classList.toggle('active',item.dataset.route===currentRoute);if(item.dataset.route===currentRoute)item.setAttribute('aria-current','page');else item.removeAttribute('aria-current')});updateDemoControls();app.focus({preventScroll:true})}function navigate(route){currentRoute=route;closeOverlay();renderCurrent();app.scrollTop=0;window.scrollTo({top:0,left:0,behavior:'smooth'})}

document.addEventListener('click',event=>{
  if(event.target.closest('#undo-change')){undoLastChange();return}
  if(event.target.closest('#demo-guide')||event.target.closest('#welcome-tour')){showWelcome();return}
  if(event.target.closest('#start-tour')){closeOverlay();startTour();return}
  if(event.target.closest('#demo-data')){showDemoData();return}
  if(event.target.closest('#sidebar-reset')||event.target.closest('#reset-demo')){showChoiceModal({title:'Start the demo again?',copy:'This replaces your current seating changes with Bea + Milo’s sample plan.',choices:[{label:'Keep exploring',action:closeOverlay},{label:'Reset demo',primary:true,action:()=>{closeOverlay();resetDemo()}}]});return}
  if(event.target.closest('#copy-demo-link')){copyDemoLink();return}
  const scenario=event.target.closest('[data-scenario]');if(scenario){applyScenario(scenario.dataset.scenario);return}
  if(event.target.closest('[data-comfort-map]')){showComfortMap();return}
  if(event.target.closest('[data-tour-close]')){tourStep=0;demoLayer.innerHTML='';return}
  if(event.target.closest('[data-tour-next]')){if(tourStep===3){tourStep=4;navigate('finder');renderTour()}else if(tourStep===5){tourStep=0;demoLayer.innerHTML='';toast('Tour complete. Keep exploring or reset anytime.')}return}
  const view=event.target.closest('[data-board-view]');if(view){boardView=view.dataset.boardView;seatingBoard();return}
  const move=event.target.closest('[data-move-guest]');if(move){showMovePicker(move.dataset.moveGuest);return}
  const target=event.target.closest('[data-move-target]');if(target){requestMove(target.dataset.moving,target.dataset.moveTarget==='unassigned'?null:target.dataset.moveTarget);return}
  const found=event.target.closest('[data-finder-guest]');if(found){renderFinderResult(guests.find(g=>g.id===found.dataset.finderGuest));return}
  const route=event.target.closest('[data-route]');if(route){navigate(route.dataset.route);return}
  const closer=event.target.closest('[data-close-overlay]');if(closer&&(closer===event.target||closer.tagName==='BUTTON')){closeOverlay();return}
  const table=event.target.closest('[data-table-id]');if(table){showTableDetail(table.dataset.tableId);return}
  const guest=event.target.closest('[data-guest-id]');if(guest){showGuestDrawer(guest.dataset.guestId);return}
  const filter=event.target.closest('[data-filter]');if(filter){guestFilter=filter.dataset.filter;guestList();return}
  const check=event.target.closest('[data-check-action]');if(check){const action=check.dataset.checkAction;if(action==='table')showTableDetail(check.dataset.target);if(action==='guest')showGuestDrawer(check.dataset.target);if(action==='suggestions'){boardView='guests';navigate('seating')}if(action==='move')showMovePicker(check.dataset.target);return}
  if(event.target.closest('#import-guests')){showGuestImport();return}
  if(event.target.closest('#confirm-import')){confirmGuestImport();return}
  if(event.target.closest('#add-guest'))showAddGuest();
  if(event.target.closest('#show-tablemates')){const panel=document.querySelector('#tablemates');panel.hidden=!panel.hidden;const toggle=document.querySelector('#show-tablemates');toggle.textContent=panel.hidden?'See Who’s at My Table':'Hide Tablemates';toggle.setAttribute('aria-expanded',String(!panel.hidden))}
});
document.addEventListener('input',event=>{if(event.target.id==='guest-search'){guestSearch=event.target.value;guestList();document.querySelector('#guest-search')?.focus()}if(event.target.id==='board-search'){boardSearch=event.target.value;seatingBoard();const input=document.querySelector('#board-search');input?.focus();input?.setSelectionRange(boardSearch.length,boardSearch.length)}});
document.addEventListener('change',event=>{if(event.target.id==='import-file'){readGuestImport(event.target);return}if(event.target.name==='import-mode'){renderImportPreview();return}if(event.target.id==='import-duplicates'){document.querySelector('#confirm-import').disabled=!event.target.checked;return}if(event.target.id==='available-toggle'){showAvailable=event.target.checked;seatingBoard()}});
document.addEventListener('submit',event=>{if(event.target.id==='finder-form'){event.preventDefault();searchFinder(document.querySelector('#finder-input').value)}if(event.target.id==='add-form'){event.preventDefault();const before=guestSnapshot(),data=new FormData(event.target),name=data.get('name').trim();if(!name){toast('Enter a guest name.');return}guests.push({id:`guest-${Date.now()}`,name,group:data.get('group'),household:'Single Guest',meal:data.get('meal'),dietary:'',accessibility:'',keepNear:'',separate:'',notes:'',status:'Added Late',table:null});saveChange(`add ${name}`,before);closeOverlay();guestList();toast(`${name} added to Unassigned Guests.`)}});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeOverlay();
 if(event.key==='Tab'&&overlayRoot.children.length){const dialog=overlayRoot.querySelector('[role="dialog"]');if(dialog){const controls=[...dialog.querySelectorAll('button:not(:disabled),a[href],input,select,[tabindex="0"]')].filter(el=>!el.hidden);const first=controls[0],last=controls.at(-1);if(!first){event.preventDefault();dialog.focus()}else if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}
 if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-guest-id]')&&!event.target.matches('button')){event.preventDefault();showGuestDrawer(event.target.dataset.guestId)}});
renderCurrent();updateDemoControls();
// Size the desktop workspace to the space below the wrapping demo toolbar.
// Both the menu and the planner then have explicit, independent scroll areas.
if(typeof ResizeObserver!=='undefined'){
 const toolbar=document.querySelector('.demo-bar');
 const syncWorkspaceHeight=()=>document.documentElement.style.setProperty('--demo-bar-height',`${toolbar.getBoundingClientRect().height}px`);
 new ResizeObserver(syncWorkspaceHeight).observe(toolbar);
 syncWorkspaceHeight();
}
