'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const URL_BASE='https://ubovuhkvtwijtzofsobs.supabase.co';
const AUTH_RETURN_URL='https://tinysitestudios.com/weddings/wedding-studio/';
const API_KEY='sb_publishable_ZgDHWGLNW9xc9IXfwAjaDg_DH5xVNa8';
const sections=['Sort later','Ceremony','Reception','Flowers','Attire & beauty','Music','Stationery','Documents'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
const domain=v=>{try{return new URL(v).hostname.replace(/^www\./,'')}catch{return ''}};
let db=null,user=null,items=[],board={title:'Our wedding',wedding_date:''},category='All inspiration',view='canvas',demo=false,editing=null,kind='note',authMode='login',loading=false,selected=new Set(),confirmResolve=null;
let toastTimer,initializing=true,draftPreview={},pendingCapture=null,importing=false;
let draftPosition=null,draftColors=[],paletteJob=0,draftTags=[],draftTasks=[];let boardOwner=null,memberRole='owner',memberTags=null,workspaces=[],offer={ready:false,price_cents:2900,introductory:true},commentsItem=null,exampleComments=[];
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500)}
function check(r){if(r.error)throw r.error;return r.data}
function busy(state){$('#save-state').textContent=state?'Saving…':demo?'Temporary example':'Saved to your account'}
function guard(){if(!demo&&!user){showAuth();return false}if(!demo&&user&&!board.created_at){void loadCloud();return false}if(!canEditBoard()){toast('This workspace is read-only.');return false}return true}
function tagsFor(i){return StudioPlanning.tags(i.tags||[i.category||'Sort later'])}
function allTags(){return [...new Set([...sections,...(board.custom_tags||[]),...items.flatMap(tagsFor)])].sort((a,b)=>a.localeCompare(b))}
function isOwner(){return demo||!user||!boardOwner||boardOwner===user.id}
function editingActive(){return demo||(!offer.ready||!board.created_at||new Date(board.created_at).getTime()+14*86400000>Date.now()||new Date(board.paid_until||0).getTime()>Date.now())}
function canEditBoard(){return editingActive()&&['owner','partner','contribute'].includes(memberRole)}
function canEditItem(i){return canEditBoard()&&(isOwner()||memberRole==='partner'||memberRole==='contribute'&&tagsFor(i).some(t=>memberTags?.includes(t)))}
function showAuth(){authMode='login';setAuthMode();$('#auth').showModal()}
function setAuthMode(){
const reset=authMode==='reset',recover=authMode==='recover';
$('#auth-title').textContent=reset?'Choose a new password.':recover?'Reset your password.':authMode==='signup'?'Your studio starts here.':'Welcome to your studio.';
$('#auth-intro').textContent=reset?'Choose a new password for your Tiny Site Studios account. This also changes the password for other TSS tools using this account.':recover?'Enter your account email and we’ll request a fresh reset link. Open the newest email and use its link once.':'Already use a Tiny Site Studios tool? Sign in with that same email and password. You only need to create an account if you’re new to Tiny Site Studios.';
$('#auth-submit').textContent=reset?'Update password':recover?'Send reset link':authMode==='signup'?'Create account':'Sign in';
$('#auth-toggle').textContent=authMode==='signup'||recover?'Back to sign in':'Create an account';
$('#email-label').hidden=reset;$('#auth-email').required=!reset;$('#password-label').hidden=recover;$('#auth-password').required=!recover;
$('#auth-password').autocomplete=authMode==='login'?'current-password':'new-password';$('#auth-toggle').hidden=reset;$('#forgot').hidden=reset||recover;
$('#auth-error').textContent='';$('#auth-next').hidden=true;$('#auth-resend').hidden=false;$('#auth-submit').hidden=false;
}
function showRecoveryError(){authMode='recover';setAuthMode();$('#auth-error').textContent='This email link is invalid, expired, or has already been used. Request a new link below, then open only the newest email.';$('#auth').showModal()}
function beginPasswordRecovery(){if($('#tour').open)$('#tour').close();authMode='reset';setAuthMode();$('#auth-password').value='';$('#auth').showModal()}
function confirmAction(title,text){$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;$('#confirm-modal').showModal();return new Promise(r=>confirmResolve=r)}
$('#confirm-yes').onclick=()=>{confirmResolve?.(true);confirmResolve=null;$('#confirm-modal').close()};$('#confirm-cancel').onclick=()=>{$('#confirm-modal').close()};$('#confirm-modal').onclose=()=>{confirmResolve?.(false);confirmResolve=null};
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function statusClass(s){return s==='Chosen'?'chosen':s==='Shortlist'?'shortlist':s==='Purchased / booked'?'purchased':''}
function previewImage(i){return i.kind==='image'||i.kind==='link'&&/^image\//.test(i.file_type||'')?i.file_url||safeUrl(i.preview?.image):safeUrl(i.preview?.image)}
function cardHTML(i,readonly=false){const image=previewImage(i);const colors=Array.isArray(i.colors)?i.colors.filter(c=>/^#[0-9a-f]{6}$/i.test(c)):[];const href=safeUrl(i.url),provider=domain(href),pin=/(^|\.)pinterest\.[a-z.]+$|(^|\.)pin\.it$/.test(provider),music=/spotify|music.apple|soundcloud|youtube|youtu.be/.test(provider);const fallback=href?`<div class="link-art ${pin?'pin-art':music?'music-art':''}"><span class="link-art-symbol">${pin?'P':music?'♫':'↗'}</span><span>${pin?'Pinterest inspiration':music?'A soundtrack for your day':esc(i.preview?.site||provider)}</span><small>${pin?'Open the original pin':music?'Open to listen':'An idea worth keeping'}</small></div>`:'';let media=i.kind==='checklist'?taskCardHTML(i,readonly):i.kind==='seating'?`<div class="seating-card-summary">${i.seating?.guests?.length||0} guests · ${i.seating?.tables?.length||0} tables<br>Your room and assignments, together.</div>`:image?`<div class="preview-media"><img class="card-media" src="${esc(image)}" alt="${esc(i.title)}" loading="lazy" referrerpolicy="no-referrer"><div class="image-fallback">${fallback||'<span>Image unavailable · open the original below</span>'}</div></div>`:i.kind==='palette'?`<div class="palette">${colors.map(c=>`<span style="background:${c}" title="${c}"></span>`).join('')}</div>`:i.kind==='file'?`<div class="file-symbol">▤ <span>${esc((i.file_name||'Document').split('.').pop())}</span></div>`:fallback;
if(href)media=`<a class="preview-link" href="${esc(href)}" target="_blank" rel="noopener noreferrer" aria-label="Open ${esc(i.title)}">${media}</a>`;
return `<article class="card ${i.kind==='group'?'group-card':''}" data-id="${esc(i.id)}" ${view==='canvas'&&!readonly?`style="left:${i.x||0}px;top:${i.y||0}px"`:''}><div class="card-top"><span>${tagsFor(i).map(t=>`<span class="card-tag">${esc(t)}</span>`).join('')}</span>${!readonly&&canEditItem(i)?`<button class="drag" data-drag="${esc(i.id)}" aria-label="Move ${esc(i.title)}" title="Drag in Canvas view; use arrow keys to move">⠿</button>`:''}</div>${media}<div class="card-body"><h3>${esc(i.title)}</h3>${i.preview?.description?`<p class="preview-description">${esc(i.preview.description)}</p>`:''}${i.notes?`<p class="card-notes">${esc(i.notes)}</p>`:''}${href?`<a class="link-domain" href="${esc(href)}" target="_blank" rel="noopener noreferrer">↗ ${esc(provider)}${pin?' · Pinterest':i.kind==='link'?' · Open link':''}</a>`:''}${i.file_url?`<a class="link-domain" href="${esc(i.file_url)}" target="_blank" rel="noopener noreferrer">${i.kind==='image'?'View original':i.kind==='link'?'View cover':'Open attachment'} · ${esc(i.file_name||'File')}</a>`:''}${i.file_path&&!i.file_url?'<p class="hint">Attachment unavailable. Reload to try again.</p>':''}${href&&!image&&!readonly?`<p class="preview-hint">${demo?'Sign in for automatic previews':'No cover available · add one in Edit details'}</p>`:''}</div>${colors.length?`<div class="palette-codes">${colors.map(esc).join(' · ')}</div>`:''}<div class="card-footer"><span class="status ${statusClass(i.status)}">${esc(i.status)}</span>${readonly?'':`${i.kind==='seating'?`<button class="card-edit" data-seat="${esc(i.id)}">Open plan</button>`:''}<button class="card-edit" data-comment="${esc(i.id)}">Discuss</button>${canEditItem(i)?`<button class="card-edit" data-edit="${esc(i.id)}">Edit</button>`:''}`}</div></article>`}
// Broken hotlinked images have a useful fallback, including on shared briefs.
document.addEventListener('error',e=>{if(e.target.matches?.('.preview-media img'))e.target.closest('.preview-media').classList.add('image-failed')},true);
function filtered(){const q=$('#search').value.toLowerCase(),s=$('#status-filter').value;return items.filter(i=>(category==='All inspiration'||tagsFor(i).includes(category))&&(!s||i.status===s)&&(!q||[i.title,i.notes,...tagsFor(i),i.file_name,i.url,...(i.tasks||[]).map(t=>t.text)].join(' ').toLowerCase().includes(q)))}
function render(){
$('#board-title').textContent=board.title;$('#board-subtitle').textContent=board.wedding_date?new Date(board.wedding_date+'T12:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'}):'';$('#board-subtitle').hidden=!board.wedding_date;
$('#account').textContent=user?'Sign out':'Sign in / create account';$('#notice').hidden=!!user&&!demo;renderWorkspaceControls();
if(demo)$('#notice').innerHTML='<span><b>Example board.</b> Changes here are temporary and disappear when you leave. Sign in for your own private, cloud-saved board.</span><button id="demo-signin">Save my own board</button>';
else if(!user)$('#notice').innerHTML='<span><b>Your ideas deserve a home.</b> Sign in to save a private board across devices, or explore a temporary example.</span><button id="demo">Try example board</button>';
$('#demo')?.addEventListener('click',loadDemo);$('#demo-signin')?.addEventListener('click',()=>showAuth());
$('#categories').innerHTML=['All inspiration',...allTags()].map((s,n)=>`<button class="nav-item ${s===category?'active':''}" data-section="${esc(s)}"><span>${n===0?'▦':s==='Sort later'?'＋':'·'} &nbsp;${esc(s)}</span><small>${s==='All inspiration'?items.length:items.filter(i=>tagsFor(i).includes(s)).length}</small></button>`).join('');
$$('[data-section]').forEach(b=>b.onclick=()=>{category=b.dataset.section;render()});
$('#section-name').textContent=category;$('#canvas-help').hidden=view!=='canvas';$('#cards-view').classList.toggle('active',view==='cards');$('#canvas-view').classList.toggle('active',view==='canvas');$('#cards-view').setAttribute('aria-pressed',String(view==='cards'));$('#canvas-view').setAttribute('aria-pressed',String(view==='canvas'));const list=filtered();$('#count').textContent=`${list.length} item${list.length!==1?'s':''}`;const el=$('#board');el.className='board'+(view==='canvas'&&list.length?' canvas':'');el.style.minHeight=view==='canvas'&&list.length?Math.max(900,...list.map(i=>(i.y||0)+530))+'px':'';el.style.minWidth=view==='canvas'&&list.length?Math.max(1100,...list.map(i=>(i.x||0)+(i.task_view==='kanban'?530:320)))+'px':'';
if(loading){el.innerHTML='<div class="loading">Opening your private board…</div>';return}
if(!list.length){const has=items.length>0;el.innerHTML=`<div class="empty"><div class="empty-mark">＋</div><h2>${has?'Room for the next idea.':'Every beautiful day starts somewhere.'}</h2><p>${has?'No items match this section or filter. Add an idea here, or explore another section.':'Drop in the flowers you love, the song you’ll dance to, or the little details you don’t want to forget.'}</p><button class="button primary" id="empty-add">＋ Add your first idea</button><button class="button" id="empty-upload">Upload a photo or file</button></div>`;$('#empty-add').onclick=()=>openEditor('note');$('#empty-upload').onclick=()=>openEditor('file');return}
el.innerHTML=list.map(i=>cardHTML(i)).join('');bindBoardExtras();$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(null,items.find(i=>i.id===b.dataset.edit)));$$('[data-drag]').forEach(b=>{b.onpointerdown=startDrag;b.onkeydown=moveKey});
}
async function fileURLs(list){if(demo)return list;return Promise.all(list.map(async i=>{if(!i.file_path)return i;try{const data=check(await db.storage.from('wedding-studio').createSignedUrl(i.file_path,3600));return {...i,file_url:data.signedUrl}}catch{return {...i,file_url:null}}}))}

function loadDemo(){if(user)return;demo=true;board={title:'Alex & Jordan',wedding_date:'2027-10-09'};items=[{id:crypto.randomUUID(),kind:'image',title:'A little garden magic',notes:'Love the loose greenery and the soft white flowers. Keep it relaxed, not too formal.',category:'Flowers',status:'Shortlist',file_url:'/weddings/demos/garden/assets/gallery-1.jpg',file_name:'floral-inspiration.jpg',x:25,y:25},{id:crypto.randomUUID(),kind:'palette',title:'Our color story',notes:'Deep navy, plum, and a little fresh green.',colors:['#172C3A','#743B61','#43867B','#F7F4EF'],category:'Reception',status:'Chosen',x:320,y:50},{id:crypto.randomUUID(),kind:'note',title:'The feeling we’re after',notes:'A really good dinner party with all our favorite people. Candlelight, personal touches, and a dance floor that stays full.',category:'Ceremony',status:'Idea',x:620,y:25},{id:crypto.randomUUID(),kind:'link',title:'An intimate garden celebration',notes:'A little inspiration for the atmosphere. Save product links, pins, and playlists this way too.',url:'https://tinysitestudios.com/weddings/demos/garden/',preview:{image:'https://tinysitestudios.com/weddings/demos/garden/assets/gallery-1.jpg',description:'Loose greenery, warm light, and all our favorite people.',site:'Tiny Site Studios'},category:'Reception',status:'Idea',x:320,y:350},{id:crypto.randomUUID(),kind:'note',title:'One less thing to remember',notes:'Add the vendor quote beside the idea it belongs to. When you decide, mark it “Chosen” and include it in your vendor brief.',category:'Sort later',status:'Idea',x:620,y:330}];items.push({id:crypto.randomUUID(),kind:'checklist',title:'A few next steps',tags:['Planning','Flowers'],category:'Planning',status:'Idea',notes:'Try switching this checklist to a task board.',task_view:'checklist',tasks:[{id:crypto.randomUUID(),text:'Choose the floral direction',status:'done',due:'',owner:'Together',fixed:false},{id:crypto.randomUUID(),text:'Ask the florist about seasonal flowers',status:'doing',due:'',owner:'Alex',fixed:false},{id:crypto.randomUUID(),text:'Approve the final proposal',status:'todo',due:'',owner:'Jordan',fixed:false}],x:25,y:430});busy(false);render()}
function setKind(k){kind=k;$$('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===k||(k==='image'&&b.dataset.kind==='file')));$('#link-fields').hidden=k!=='link';$('#file-fields').hidden=!['file','image','link'].includes(k);$('#upload-label').textContent=k==='link'?'Upload a cover image (optional)':'Choose an image or file';$('#upload-hint').textContent=k==='link'?'JPG, PNG, WebP, GIF, or AVIF · up to 15 MB':'Images, PDFs, and documents · up to 15 MB each';$('#item-file').accept=k==='link'?'image/jpeg,image/png,image/webp,image/gif,image/avif':'.jpg,.jpeg,.png,.webp,.gif,.avif,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.rtf,.odt,.ppt,.pptx';$('#remove-cover').hidden=k!=='link'||!editing?.file_name;$('#palette-fields').hidden=k!=='palette';$('#checklist-fields').hidden=k!=='checklist';$('#decision-label').hidden=['checklist','group','seating'].includes(k);$('#item-url').required=k==='link'}
function openEditor(k='note',item=null,position=null){if(loading||!guard())return;draftPosition=position;editing=item;draftPreview=item?.preview||{};$('#preview-feedback').textContent='';$('#item-form').reset();$('#editor-error').textContent='';$('#editor-title').textContent=item?'Edit your idea':'Add to your board';$('#delete-item').hidden=!item;$('#item-title').value=item?.title||'';$('#item-url').value=item?.url||'';$('#item-notes').value=item?.notes||'';$('#item-category').value=item?.category||(category==='All inspiration'?'Sort later':category);$('#item-status').value=item?.status||'Idea';paletteJob++;$('#palette-feedback').textContent='';$('#palette-photo').disabled=false;$('#item-save').disabled=false;setPalette(item?.colors?.length?item.colors:['#172C3A','#743B61','#43867B','#F7F4EF']);$('#attached').textContent=item?.file_name?'Attached: '+item.file_name:'';draftTags=item?tagsFor(item):[category==='All inspiration'?(memberRole==='contribute'?memberTags?.[0]||'Sort later':'Sort later'):category];draftTasks=structuredClone(item?.tasks||[]);renderTagPicker();renderDraftTasks();$('#draft-task-view').value=item?.task_view||'checklist';$('#item-status').disabled=!isOwner()&&memberRole!=='partner';$('#delete-item').hidden=!item||!isOwner();setKind(item?.kind||k);$('#editor').showModal()}
async function persistItem(item){if(demo){items=items.some(i=>i.id===item.id)?items.map(i=>i.id===item.id?item:i):[...items,item];render();return item}const copy={...item,user_id:boardOwner||user.id};delete copy.file_url;delete copy.created_at;check(await db.from('wedding_studio_items').upsert(copy));const hydrated=(await fileURLs([item]))[0];items=items.some(i=>i.id===item.id)?items.map(i=>i.id===item.id?hydrated:i):[...items,hydrated];render();return hydrated}
$('#item-form').onsubmit=async e=>{e.preventDefault();const title=$('#item-title').value.trim(),file=$('#item-file').files[0];if(!title)return;if(file&&!StudioPlanning.allowedFile(file)){$('#editor-error').textContent='Upload an image or document. Save videos and playlists as links.';return}if(kind==='checklist'&&!draftTasks.some(t=>t.text.trim())){$('#editor-error').textContent='Add at least one task.';return}let colors=[];if(kind==='palette'){colors=StudioPalette.parse($('#item-colors').value);if(!colors.length||colors.length>6||colors.some(c=>!/^#[0-9A-F]{6}$/.test(c))){$('#editor-error').textContent='Choose one to six colors using the swatches, or check your pasted color codes.';return}}
if(kind==='link'&&!safeUrl($('#item-url').value)){$('#editor-error').textContent='Use a complete http or https link.';return}if(['file','image'].includes(kind)&&!file&&!editing?.file_path&&!editing?.file_url){$('#editor-error').textContent='Choose a file to upload.';return}if(file&&kind==='link'&&!/^image\/(jpeg|png|webp|gif|avif)$/.test(file.type)){$('#editor-error').textContent='Choose a JPG, PNG, WebP, GIF, or AVIF cover image.';return}if(file&&file.size>15*1024*1024){$('#editor-error').textContent='This file is larger than 15 MB. Use a smaller file or save a link instead.';return}$('#item-save').disabled=true;busy(true);let uploaded=null;
try{const i={id:editing?.id||crypto.randomUUID(),title,kind,category:StudioPlanning.tags(draftTags)[0],tags:StudioPlanning.tags(draftTags),tasks:kind==='checklist'?draftTasks.filter(t=>t.text.trim()):[],task_view:$('#draft-task-view').value,template_meta:editing?.template_meta||{},seating:editing?.seating||{},status:$('#item-status').value,notes:$('#item-notes').value.trim(),url:kind==='link'?safeUrl($('#item-url').value):'',colors,x:editing?.x??draftPosition?.x??25+(items.length%3)*290,y:editing?.y??draftPosition?.y??25+Math.floor(items.length/3)*420,file_path:editing?.file_path||null,file_name:editing?.file_name||null,file_type:editing?.file_type||null,file_url:editing?.file_url||null,preview:kind==='link'?draftPreview:{}};if(file&&['file','image','link'].includes(kind)){const image=/^image\/(jpeg|png|webp|gif|avif)$/.test(file.type);i.kind=kind==='link'?'link':image?'image':'file';i.file_name=file.name;i.file_type=file.type||'application/octet-stream';if(demo)i.file_url=URL.createObjectURL(file);else{const path=(boardOwner||user.id)+'/'+user.id+'/'+crypto.randomUUID()+'/'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');check(await db.storage.from('wedding-studio').upload(path,file,{contentType:i.file_type,upsert:false}));i.file_path=path;uploaded=path}}if(!['file','image','link'].includes(kind)){i.file_path=null;i.file_name=null;i.file_type=null;i.file_url=null}$('#search').value='';$('#status-filter').value='';if(category!=='All inspiration')category=i.category;await persistItem(i);if(i.kind==='link'&&!i.preview?.checked_at)void enrichItem(i.id,false);$('#editor').close();toast(demo?'Added to the temporary example':'Saved to your board')}catch(err){if(uploaded)await db.storage.from('wedding-studio').remove([uploaded]);$('#editor-error').textContent=err.message||'Could not save. Your details are still here; please try again.'}finally{$('#item-save').disabled=false;busy(false)}};
$('#item-file').onchange=()=>{const f=$('#item-file').files[0];if(f&&!$('#item-title').value)$('#item-title').value=f.name.replace(/\.[^.]+$/,'').slice(0,200)};
$('#delete-item').onclick=async()=>{if(!editing)return;const i=editing;if(!await confirmAction('Delete this idea?','This removes it from your board. Existing vendor briefs keep their snapshots until you revoke them.'))return;try{if(!demo)check(await db.from('wedding_studio_items').delete().eq('id',i.id).eq('user_id',boardOwner||user.id));items=items.filter(x=>x.id!==i.id);$('#editor').close();render();toast('Idea removed')}catch(e){toast(e.message)}};
async function savePosition(i,x,y){const old={x:i.x,y:i.y};i.x=x;i.y=y;busy(true);try{if(!demo)check(await db.from('wedding_studio_items').update({x,y}).eq('id',i.id).eq('user_id',boardOwner||user.id));render()}catch(e){Object.assign(i,old);render();toast('Position could not save. Try again.')}finally{busy(false)}}
function startDrag(e){if(view!=='canvas'||!canEditItem(items.find(i=>i.id===e.currentTarget.dataset.drag)))return;if(e.button!==0)return;const handle=e.currentTarget,card=handle.closest('.card'),i=items.find(i=>i.id===handle.dataset.drag);const startX=e.clientX,startY=e.clientY,ox=i.x||0,oy=i.y||0;handle.setPointerCapture(e.pointerId);let x=ox,y=oy;handle.onpointermove=ev=>{x=Math.max(0,Math.min(10000,ox+ev.clientX-startX));y=Math.max(0,Math.min(10000,oy+ev.clientY-startY));card.style.left=x+'px';card.style.top=y+'px'};handle.onpointerup=()=>{handle.onpointermove=null;handle.onpointerup=null;if(x!==ox||y!==oy)savePosition(i,Math.round(x),Math.round(y))};handle.onpointercancel=()=>{handle.onpointermove=null;render()}}
function moveKey(e){if(!canEditBoard()||view!=='canvas'||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const i=items.find(i=>i.id===e.currentTarget.dataset.drag),step=e.shiftKey?50:10;const x=Math.max(0,Math.min(10000,i.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0))),y=Math.max(0,Math.min(10000,i.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)));savePosition(i,x,y).then(()=>document.querySelector(`[data-drag="${i.id}"]`)?.focus())}
$('#tidy').onclick=async()=>{if(!guard())return;const list=filtered().filter(canEditItem);const cellWidth=list.some(i=>i.task_view==='kanban')?550:320;busy(true);try{for(let n=0;n<list.length;n++){const i=list[n],x=25+n%3*cellWidth,y=25+Math.floor(n/3)*560;if(!demo)check(await db.from('wedding_studio_items').update({x,y}).eq('id',i.id).eq('user_id',boardOwner||user.id));i.x=x;i.y=y}render();toast('Canvas arranged')}catch(e){toast('Could not finish arranging. Try again.')}finally{busy(false)}};
$('#settings').onclick=()=>{if(!guard()||!isOwner())return;$('#wedding-title').value=board.title;$('#wedding-date').value=board.wedding_date;$('#planning-start').value=board.planning_start||new Date().toISOString().slice(0,10);$('#wedding-settings').showModal()};$('#settings-form').onsubmit=async e=>{e.preventDefault();if(!isOwner()||!guard())return;const b={title:$('#wedding-title').value.trim(),wedding_date:$('#wedding-date').value,planning_start:$('#planning-start').value};if(!b.title)return;try{if(!demo)check(await db.from('wedding_studio_boards').update({...b,updated_at:new Date().toISOString()}).eq('user_id',boardOwner||user.id));if($('#shift-tasks').checked&&b.wedding_date&&b.wedding_date!==board.wedding_date){for(const i of items.filter(i=>i.template_meta?.id&&i.kind==='checklist'))await persistItem({...i,tasks:StudioPlanning.shiftTasks(i.tasks,board.wedding_date||i.template_meta.end,b.wedding_date,b.planning_start),template_meta:{...i.template_meta,end:b.wedding_date}})}board={...board,...b};render();$('#wedding-settings').close();toast('Wedding details saved')}catch(err){toast(err.message)}};
function briefChoices(){const list=filtered();$('#brief-choices').innerHTML=list.length?list.map(i=>`<label class="brief-choice"><input type="checkbox" value="${i.id}" ${selected.has(i.id)?'checked':''}>${previewImage(i)?`<img src="${esc(previewImage(i))}" alt="" referrerpolicy="no-referrer">`:''}<span>${esc(i.title)}<small>${esc(i.category)} · ${esc(i.status)}</small></span></label>`).join(''):'<p class="hint" style="padding:20px">Add ideas to this board or adjust your filters first.</p>';$$('#brief-choices input').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.value):selected.delete(c.value);$('#selected-count').textContent=selected.size+' selected'});$('#selected-count').textContent=selected.size+' selected'}
$('#brief-open').onclick=()=>{if(!guard())return;if(!isOwner()){toast('The board owner creates shared vendor briefs.');return}selected=new Set();$('#brief-title').value='';$('#brief-instructions').value='';$('#brief-error').textContent='';$('#brief-result').hidden=true;$('#create-brief').disabled=false;briefChoices();$('#brief-modal').showModal()};$('#select-chosen').onclick=()=>{selected=new Set(filtered().filter(i=>['Chosen','Purchased / booked'].includes(i.status)).map(i=>i.id));briefChoices()};$('#clear-selection').onclick=()=>{selected.clear();briefChoices()};
function briefPayload(){if(!selected.size)throw Error('Select at least one item for this brief.');if(selected.size>100)throw Error('Please choose up to 100 items per brief.');return {wedding:board.title,date:board.wedding_date,instructions:$('#brief-instructions').value.trim(),items:items.filter(i=>selected.has(i.id)).map(i=>{const copy={...i};delete copy.user_id;delete copy.created_at;if(!demo)delete copy.file_url;return copy})}}
$('#create-brief').onclick=async()=>{if(demo){$('#brief-error').textContent='Sign in to create a shareable brief from your saved board. You can preview and print this example.';return}$('#brief-error').textContent='';$('#create-brief').disabled=true;try{const payload=briefPayload(),title=$('#brief-title').value.trim();if(!title)throw Error('Give your brief a title.');const d=check(await db.from('wedding_studio_briefs').insert({user_id:boardOwner||user.id,title,payload}).select('token').single());const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('brief',d.token);$('#brief-link').value=url.href;$('#open-brief').href=url.href;$('#brief-result').hidden=false;toast('Your read-only brief is ready')}catch(e){$('#brief-error').textContent=e.message;$('#create-brief').disabled=false}};
$('#copy-brief').onclick=async()=>{try{await navigator.clipboard.writeText($('#brief-link').value);toast('Vendor link copied')}catch{$('#brief-link').select();toast('Select and copy the highlighted link')}};
function briefHTML(b){return `<section class="brief-page"><div class="brandline"><span>WEDDING STUDIO · TINY SITE STUDIOS</span><button class="button no-print" onclick="window.print()">Print / save PDF</button></div><header><p class="eyebrow">VENDOR BRIEF</p><h1>${esc(b.title)}</h1><p class="brief-meta">${esc(b.wedding)}${b.date?' · '+esc(b.date):''}<br>Snapshot created ${new Date(b.created_at||Date.now()).toLocaleDateString()}${b.expires_at?' · Link expires '+new Date(b.expires_at).toLocaleDateString():''}</p></header>${b.instructions?`<p class="instructions">${esc(b.instructions)}</p>`:''}<div class="board">${b.items.map(i=>cardHTML(i,true)).join('')}</div><footer>Prepared with Wedding Studio by Tiny Site Studios. This brief contains selected items only. Attachment links refresh when you reload the shared brief.</footer></section>`}
$('#print-brief').onclick=async()=>{let b;try{b=briefPayload();b.title=$('#brief-title').value.trim()||'Our wedding vision'}catch(e){$('#brief-error').textContent=e.message;return}const w=window.open('','_blank');if(!w){$('#brief-error').textContent='Allow pop-ups to open the printable brief.';return}w.opener=null;w.document.write('<p>Preparing your brief…</p>');b.items=await fileURLs(b.items);w.document.open();w.document.write(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(b.title)}</title><link rel="stylesheet" href="${new URL('studio.css',location.href).href}"></head><body>${briefHTML(b)}</body></html>`);w.document.close()};
$('#manage-briefs').onclick=async()=>{if(!guard())return;$('#briefs-modal').showModal();if(demo){$('#briefs-list').innerHTML='<p class="intro">Your shared briefs will appear here once you sign in and create one.</p>';return}$('#briefs-list').textContent='Loading…';try{const list=check(await db.from('wedding_studio_briefs').select('id,title,token,expires_at').eq('user_id',boardOwner||user.id).order('created_at',{ascending:false}));$('#briefs-list').innerHTML=list.length?list.map(b=>`<div class="shared-row"><strong>${esc(b.title)}</strong><p>Expires ${new Date(b.expires_at).toLocaleDateString()}</p><a target="_blank" rel="noopener" href="?brief=${b.token}">View brief</a><button class="quiet" data-revoke="${b.id}">Revoke link</button></div>`).join(''):'<p class="intro">No shared briefs yet. Choose “Make a vendor brief” to create your first one.</p>';$$('[data-revoke]').forEach(b=>b.onclick=async()=>{if(!await confirmAction('Revoke this brief?','The shared link will stop working. Attachments already opened may remain available for up to one hour. Downloaded copies cannot be recalled.'))return;try{check(await db.from('wedding_studio_briefs').delete().eq('id',b.dataset.revoke).eq('user_id',boardOwner||user.id));b.closest('.shared-row').remove();toast('Brief link revoked')}catch(e){toast(e.message)}})}catch(e){$('#briefs-list').textContent='Could not load briefs. Close this window and try again.'}};
$('#auth-toggle').onclick=()=>{authMode=authMode==='signup'||authMode==='recover'?'login':'signup';setAuthMode()};
$('#auth-form').onsubmit=async e=>{e.preventDefault();if(!db){$('#auth-error').textContent='The connection could not start. Please reload and try again.';return}$('#auth-submit').disabled=true;$('#auth-error').textContent='';const email=$('#auth-email').value.trim(),password=$('#auth-password').value;try{if(authMode==='recover'){check(await db.auth.resetPasswordForEmail(email,{redirectTo:AUTH_RETURN_URL}));$('#auth-next').hidden=false;$('#auth-resend').hidden=true;$('#auth-submit').hidden=true;$('#auth-message').textContent='If an account exists for this email, a fresh password-reset link has been requested. Open the newest email and use its link once. It should return you to Wedding Studio to choose a new password.';return}if(authMode==='reset'){check(await db.auth.updateUser({password}));$('#auth-password').value='';$('#auth').close();toast('Password updated');await loadCloud();return}const r=authMode==='signup'?await db.auth.signUp({email,password,options:{emailRedirectTo:AUTH_RETURN_URL}}):await db.auth.signInWithPassword({email,password});const data=check(r);if(!data.session){$('#auth-next').hidden=false;$('#auth-submit').hidden=true;$('#auth-message').textContent='If this is a new email address, check your inbox and spam folder for a confirmation link. Already have a Tiny Site Studios account? No new confirmation is needed—sign in with your existing password, or choose Forgot password. For privacy, this screen cannot confirm whether an address is registered.';return}user=data.user;$('#auth').close();category='All inspiration';await loadCloud()}catch(err){$('#auth-error').textContent=err.code==='invalid_credentials'?'That email and password did not match. Try again, or choose Forgot password to reset your TSS password.':err.message||'Unable to sign in. Please try again.'}finally{$('#auth-submit').disabled=false}};
$('#auth-go-login').onclick=()=>{authMode='login';setAuthMode();$('#auth-password').value='';$('#auth-password').focus()};
$('#auth-resend').onclick=async()=>{const email=$('#auth-email').value.trim();if(!email||!$('#auth-email').checkValidity()){$('#auth-error').textContent='Enter a valid email address first.';return}$('#auth-resend').disabled=true;try{check(await db.auth.resend({type:'signup',email,options:{emailRedirectTo:AUTH_RETURN_URL}}));$('#auth-message').textContent='If this address has an unconfirmed account, a new confirmation link has been requested. Check your inbox and spam folder. Already confirmed? Choose Go to sign in.';setTimeout(()=>$('#auth-resend').disabled=false,60000)}catch(e){$('#auth-error').textContent=e.message||'Could not request another confirmation. Please try again.';$('#auth-resend').disabled=false}};
$('#forgot').onclick=()=>{authMode='recover';setAuthMode();$('#auth-password').value='';$('#auth-email').focus()};
$('#account').onclick=async()=>{if(!user){showAuth();return}try{check(await db.auth.signOut());user=null;demo=false;items=[];board={title:'Our wedding',wedding_date:''};render();toast('Signed out')}catch(e){toast(e.message)}};
$$('[data-kind]').forEach(b=>b.onclick=()=>setKind(b.dataset.kind));$('#item-category').innerHTML=sections.map(s=>`<option>${esc(s)}</option>`).join('');$('#cards-view').onclick=()=>{view='cards';render()};$('#canvas-view').onclick=()=>{view='canvas';render()};$('#search').oninput=render;$('#status-filter').onchange=render;
const wrap=$('#board-wrap');
$('#board-add').onclick=()=>openEditor();
wrap.ondblclick=e=>{if(!captureAllowed(e)||e.target.closest('.card,button,a,input,select,textarea,.board-dock'))return;const rect=$('#board').getBoundingClientRect();openEditor('note',null,view==='canvas'?{x:Math.max(0,Math.min(10000,Math.round(e.clientX-rect.left))),y:Math.max(0,Math.min(10000,Math.round(e.clientY-rect.top)))}:null)};
function captureAllowed(e){return !loading&&!$('#app').hidden&&!e.target.closest?.('input,textarea,select,[contenteditable="true"]')&&!$$('dialog[open]').length}
let internalDrag=false,dragDepth=0;
document.addEventListener('dragstart',e=>{internalDrag=!!e.target.closest?.('#board')});
document.addEventListener('dragend',()=>{internalDrag=false;dragDepth=0;document.body.classList.remove('drop-active')});
document.addEventListener('dragover',e=>{if(captureAllowed(e)&&!internalDrag){e.preventDefault();e.dataTransfer.dropEffect='copy'}});
document.addEventListener('dragenter',e=>{if(captureAllowed(e)&&!internalDrag){e.preventDefault();dragDepth++;document.body.classList.add('drop-active')}});
document.addEventListener('dragleave',()=>{if(--dragDepth<=0){dragDepth=0;document.body.classList.remove('drop-active')}});
document.addEventListener('drop',e=>{dragDepth=0;document.body.classList.remove('drop-active');if(!captureAllowed(e)||internalDrag)return;e.preventDefault();const rect=$('#board').getBoundingClientRect();const capture=StudioIntake.read(e.dataTransfer);if(view==='canvas')capture.position={x:Math.max(0,Math.round(e.clientX-rect.left)),y:Math.max(0,Math.round(e.clientY-rect.top))};void receiveCapture(capture)});
document.addEventListener('paste',e=>{if(!captureAllowed(e))return;const capture=StudioIntake.read(e.clipboardData);if(capture.entries.length){e.preventDefault();void receiveCapture(capture)}});
$('#capture-help').onclick=()=>$('#capture-modal').showModal();
async function receiveCapture(capture){if(!capture.entries.length)return;if(!user&&!demo){pendingCapture=capture;showAuth();toast('Sign in to save these ideas. They’re held here while you sign in.');return}await importCapture(capture)}
function importMessage(text,failed=[]){const el=$('#import-status');el.hidden=false;el.textContent=text;if(failed.length){const retry=document.createElement('button');retry.className='quiet';retry.textContent='Retry failed items';retry.onclick=()=>importCapture({entries:failed});el.append(retry)}const close=document.createElement('button');close.className='quiet';close.textContent='Dismiss';close.onclick=()=>el.hidden=true;el.append(close)}
async function importCapture(capture){if(importing){toast('Please wait for this batch to finish, then paste or drop again.');return}if(!guard())return;importing=true;const owner=user?.id,isDemo=demo,targetCategory=category==='All inspiration'?(memberTags?.[0]||'Sort later'):category;const entries=capture.entries.slice(0,30),failed=[],newLinks=[];let added=0;busy(true);$('#search').value='';$('#status-filter').value='';
try{for(let n=0;n<entries.length;n++){if(user?.id!==owner||demo!==isDemo)break;const entry=entries[n];importMessage(`Adding ${n+1} of ${entries.length}…`);let uploaded=null;try{const pos=capture.position;const i={id:crypto.randomUUID(),title:(entry.title||'A new idea').slice(0,200),kind:entry.kind,category:targetCategory,tags:[targetCategory],status:'Idea',notes:entry.notes||'',url:entry.url||'',colors:[],preview:entry.image?{image:entry.image}:{},x:Math.min(10000,pos?pos.x+n*24:25+items.length%3*290),y:Math.min(10000,pos?pos.y+n*24:25+Math.floor(items.length/3)*460)};
if(entry.file){const f=entry.file;if(!StudioPlanning.allowedFile(f))throw Error('Use image/document uploads or save video/audio links');if(f.size>15*1024*1024)throw Error('File exceeds 15 MB');i.kind=/^image\/(jpeg|png|webp|gif|avif)$/.test(f.type)?'image':'file';i.file_name=f.name;i.file_type=f.type||'application/octet-stream';if(demo)i.file_url=URL.createObjectURL(f);else{uploaded=(boardOwner||user.id)+'/'+user.id+'/'+crypto.randomUUID()+'/'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');check(await db.storage.from('wedding-studio').upload(uploaded,f,{contentType:i.file_type,upsert:false}));i.file_path=uploaded}}
if(user?.id!==owner||demo!==isDemo)throw Error('Session changed');await persistItem(i);added++;if(i.kind==='link')newLinks.push(i.id);
}catch(e){if(uploaded&&user?.id===owner)await db.storage.from('wedding-studio').remove([uploaded]);failed.push(entry)}}
importMessage(`${added} idea${added!==1?'s':''} added${demo?' to the temporary example':''}.${failed.length?' '+failed.length+' could not save. Check the connection and 15 MB file limit.':''}${capture.entries.length>30?' Only the first 30 were added; drop the rest as another batch.':''}`,failed);
}finally{importing=false;busy(false)}
for(const id of newLinks){if(user?.id!==owner||demo!==isDemo)break;await enrichItem(id,true)}}
const previewInFlight=new Set();
async function fetchLinkPreview(url){if(demo&&url!=='https://tinysitestudios.com/weddings/demos/garden/')throw Error('Automatic previews are available on your saved board. You can upload a cover in this example.');const session=check(await db.auth.getSession()).session;if(!session&&!demo)throw Error('Sign in to refresh the preview.');const r=await fetch(URL_BASE+'/functions/v1/wedding-studio-link-preview',{method:'POST',headers:{'Content-Type':'application/json','apikey':API_KEY,...(session?{'Authorization':'Bearer '+session.access_token}:{})},body:JSON.stringify({url}),signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw Error(data.error||'Preview unavailable. Add a cover image instead.');return data}
async function enrichItem(id,replaceTitle=false){const original=items.find(i=>i.id===id);if(!original?.url||demo||!user||previewInFlight.has(id))return;const owner=user.id;previewInFlight.add(id);try{let preview;try{preview=await fetchLinkPreview(original.url)}catch{preview={checked_at:new Date().toISOString()}}const latest=items.find(i=>i.id===id);if(user?.id!==owner||!latest||latest.url!==original.url)return;preview={...latest.preview,...preview,image:preview.image||latest.preview?.image||''};await persistItem({...latest,preview,title:replaceTitle&&preview.title&&latest.title===original.title?preview.title:latest.title})}catch{/* Saving the original link is independent of preview availability. */}finally{previewInFlight.delete(id)}}
async function enrichExisting(){const owner=user?.id;for(const i of items.filter(i=>i.kind==='link'&&!i.preview?.checked_at).slice(0,20)){if(user?.id!==owner||demo)break;await enrichItem(i.id,false)}}
$('#refresh-preview').onclick=async()=>{const url=safeUrl($('#item-url').value);if(!url){$('#preview-feedback').textContent='Enter a complete website link first.';return}$('#refresh-preview').disabled=true;$('#preview-feedback').textContent='Looking for a preview…';try{const found=await fetchLinkPreview(url);draftPreview={...found,image:found.image||draftPreview.image||''};if(!$('#item-title').value&&draftPreview.title)$('#item-title').value=draftPreview.title;$('#preview-feedback').textContent=draftPreview.image?'Preview found. Save this item to apply it.':'Page details found, but no cover. Upload an image below.'}catch(e){$('#preview-feedback').textContent=e.message}finally{$('#refresh-preview').disabled=false}};
$('#item-url').addEventListener('input',()=>{draftPreview={};$('#preview-feedback').textContent=''});
$('#remove-cover').onclick=()=>{if(editing)editing={...editing,file_path:null,file_url:null,file_name:null,file_type:null};$('#item-file').value='';$('#attached').textContent='Cover removed. Save to apply.';$('#remove-cover').hidden=true};
async function loadPublicBrief(token){$('#app').hidden=true;const host=document.createElement('div');host.id='public-brief';host.innerHTML='<p class="loading">Opening your vendor brief…</p>';document.body.prepend(host);try{const r=await fetch(URL_BASE+'/functions/v1/wedding-studio-brief?token='+encodeURIComponent(token));const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to open brief');host.innerHTML=briefHTML(data);document.title=data.title+' | Wedding Studio'}catch(e){host.innerHTML=`<div class="empty"><h2>This brief isn’t available.</h2><p>${esc(e.message)}</p><p>Ask the couple for a fresh link.</p></div>`}}

function setPalette(colors){draftColors=colors.filter(c=>/^#[0-9a-f]{6}$/i.test(c)).slice(0,6).map(c=>c.toUpperCase());$('#item-colors').value=draftColors.join(', ');renderPalette()}
function renderPalette(){
 $('#palette-swatches').innerHTML=draftColors.map((c,n)=>`<div class="palette-swatch"><label><span class="sr-only">Color ${n+1}</span><input type="color" value="${c}" data-color="${n}"><span class="color-code">${c}</span></label><button type="button" class="quiet" data-remove-color="${n}" aria-label="Remove color ${n+1}" ${draftColors.length===1?'disabled':''}>Remove</button></div>`).join('');
 $('#palette-add').disabled=draftColors.length>=6;
 $$('[data-color]').forEach(el=>el.oninput=()=>{draftColors[Number(el.dataset.color)]=el.value.toUpperCase();el.nextElementSibling.textContent=el.value.toUpperCase();$('#item-colors').value=draftColors.join(', ')});
 $$('[data-remove-color]').forEach(el=>el.onclick=()=>setPalette(draftColors.filter((_,n)=>n!==Number(el.dataset.removeColor))));
}
$('#palette-add').onclick=()=>{if(draftColors.length<6)setPalette([...draftColors,'#E9D6CF'])};
$('#palette-apply').onclick=()=>{const colors=StudioPalette.parse($('#item-colors').value);if(!colors.length||colors.length>6||colors.some(c=>!/^#[0-9A-F]{6}$/.test(c))){$('#palette-feedback').textContent='Check the codes: use up to six colors, like #743B61, separated by commas or spaces.';return}setPalette(colors);$('#palette-feedback').textContent='Your colors are ready. Tap any swatch to adjust.'};
$('#editor').addEventListener('close',()=>{paletteJob++;$('#item-save').disabled=false});
$('#palette-photo').onchange=async()=>{
 const file=$('#palette-photo').files[0],job=++paletteJob;$('#item-save').disabled=false;if(!file)return;
 if(!/^image\/(jpeg|png|webp|gif|avif)$/.test(file.type)||file.size>15*1024*1024){$('#palette-feedback').textContent='Choose a JPG, PNG, WebP, GIF, or AVIF image under 15 MB.';return}
 $('#palette-feedback').textContent='Finding the colors in your photo…';$('#item-save').disabled=true;
 const url=URL.createObjectURL(file);
 try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('This image could not be opened. Try another photo.'));img.src=url});
 const scale=Math.min(1,160/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,canvas.width,canvas.height);const colors=StudioPalette.extract(ctx.getImageData(0,0,canvas.width,canvas.height).data);
 if(!colors.length)throw Error('No visible colors found. Try a different photo.');if(job!==paletteJob)return;
 setPalette(colors);$('#palette-feedback').textContent=`Found ${colors.length} color${colors.length===1?'':'s'}. Tap a swatch to fine-tune your palette.`;if(!$('#item-title').value)$('#item-title').value='Colors from '+file.name.replace(/\.[^.]+$/,'').slice(0,160);
 }catch(e){if(job===paletteJob)$('#palette-feedback').textContent=e.message||'Could not read this image. Try another photo.'}finally{URL.revokeObjectURL(url);if(job===paletteJob)$('#item-save').disabled=false}
};
const tourSteps=[
 ['Your ideas, all together.','Collect the little details that make your day yours. Your private board holds photos, links, pins, documents, playlists, notes, and colors.','<div class="tour-mini photo">Garden magic</div><div class="tour-mini note">The feeling?<br>A really good dinner party.</div><div class="tour-mini swatches"><i></i><i></i><i></i><i></i></div>'],
 ['Add it the moment you see it.','Use the + button on your board, or double-click any open space. You can also drop files and links onto the page, or click outside a text field and paste.','<div class="tour-add">＋</div><div class="tour-chips"><span>Photo</span><span>Pin or link</span><span>File</span><span>Playlist</span></div>'],
 ['Make it feel like your wedding.','Your Canvas is ready to arrange. Give ideas multiple tags, add your own, and mark favorites Chosen. For palettes, pick colors visually or pull them from a photo.','<div class="tour-mini palette-demo"><div class="tour-mini swatches"><i></i><i></i><i></i><i></i></div><b>Our color story</b><span class="status chosen">Chosen</span></div>'],
 ['Give your vendors a clear picture.','Choose Make a vendor brief, select the ideas and attachments they need, and add instructions. Preview or print it, or create a read-only link from your saved board. Sign in to keep your own board across devices.','<div class="tour-mini brief-demo"><small>VENDOR BRIEF</small><b>Our floral vision</b><span>✓ Selected inspiration</span><span>✓ Notes & attachments</span><span>↗ Ready to share</span></div>']
];
let tourStep=0,tourSeen=false;
function renderTour(){const [title,copy,preview]=tourSteps[tourStep];$('#tour-title').textContent=title;$('#tour-copy').textContent=copy;$('#tour-preview').innerHTML=preview;$('#tour-progress').textContent=`${tourStep+1} OF ${tourSteps.length}`;$('#tour-back').hidden=tourStep===0;$('#tour-next').textContent=tourStep===tourSteps.length-1?'Explore my studio':'Next'}
function openTour(){tourStep=0;renderTour();$('#tour').showModal()}
function rememberTour(){tourSeen=true;try{localStorage.setItem('wedding-studio-tour-v1','seen')}catch{}}
function maybeShowTour(){if(tourSeen||new URLSearchParams(location.search).has('brief')||/type=recovery|access_token=/.test(location.hash||'')||new URLSearchParams(location.search).has('invite')||$$('dialog[open]').length)return;try{if(localStorage.getItem('wedding-studio-tour-v1')==='seen')return}catch{}openTour();rememberTour()}
$('#tour-open').onclick=openTour;
$('#tour-skip').onclick=()=>$('#tour').close();
$('#tour').addEventListener('close',rememberTour);
$('#tour-back').onclick=()=>{tourStep=Math.max(0,tourStep-1);renderTour();$('#tour-title').focus()};
$('#tour-next').onclick=()=>{if(tourStep===tourSteps.length-1){$('#tour').close();return}tourStep++;renderTour();$('#tour-title').focus()};

async function init(){const token=new URLSearchParams(location.search).get('brief');if(token){await loadPublicBrief(token);return}render();const callbackError=new URLSearchParams(location.hash.slice(1)).has('error');if(callbackError){history.replaceState(null,'',location.pathname+location.search);showRecoveryError()}else maybeShowTour();if(!window.supabase){toast('Could not connect. Reload to enable sign-in.');return}db=window.supabase.createClient(URL_BASE,API_KEY,{auth:{storageKey:'wedding-studio-auth'}});db.auth.onAuthStateChange((event,session)=>{user=session?.user||null;if(event==='PASSWORD_RECOVERY')beginPasswordRecovery();if(event==='SIGNED_OUT'&&!initializing){finishTrialStart(false);items=[];demo=false;board={title:'Our wedding',wedding_date:''};render()}});try{const data=check(await db.auth.getSession());user=data.session?.user||null;initializing=false;if(user)await loadCloud()}catch(e){initializing=false;toast('Could not restore your session. Please sign in again.')}if(document.modelContext?.registerTool){const abort=new AbortController();try{await document.modelContext.registerTool({name:'read_wedding_board',description:'Read the current visible wedding board and decision labels.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments are accepted.');return {title:board.title,temporary:demo,items:filtered().map(({id,title,category,status,notes,url})=>({id,title,category,status,notes,url}))}}} ,{signal:abort.signal});window.addEventListener('pagehide',()=>abort.abort(),{once:true})}catch{}}}

/* Wedding Studio planning and collaboration. */
function renderTagPicker(){const locked=!isOwner()&&memberRole!=='partner'&&!!editing;const available=memberRole==='contribute'&&!editing?memberTags||[]:allTags();$('#item-tags').innerHTML=[...new Set([...available,...draftTags])].map(t=>`<label><input type="checkbox" data-tag value="${esc(t)}" ${draftTags.includes(t)?'checked':''} ${locked?'disabled':''}>${esc(t)}</label>`).join('');$$('[data-tag]').forEach(el=>el.onchange=()=>{draftTags=$$('[data-tag]:checked').map(el=>el.value)});$('#create-tag').disabled=locked||memberRole==='contribute';$('#new-tag').disabled=locked||memberRole==='contribute'}
$('#create-tag').onclick=()=>{const tag=$('#new-tag').value.trim().slice(0,40);if(!tag||tag==='All inspiration')return;draftTags=StudioPlanning.tags([...draftTags,tag]);board.custom_tags=StudioPlanning.tags([...(board.custom_tags||[]),tag]);$('#new-tag').value='';renderTagPicker()};
function taskCardHTML(i,readonly=false){const tasks=i.tasks||[],editable=!readonly&&canEditItem(i),row=t=>`<div class="task-row ${t.status==='done'?'task-done':''}" ${editable&&i.task_view==='kanban'?`draggable="true" data-task-drag="${esc(t.id)}" data-task-item="${esc(i.id)}"`:''}><label><input type="checkbox" ${t.status==='done'?'checked':''} ${editable?'':'disabled'} data-task-check="${esc(t.id)}" data-task-item="${esc(i.id)}"><span>${esc(t.text)}</span></label>${t.due||t.owner?`<small>${esc(t.due)}${t.owner?' · '+esc(t.owner):''}</small>`:''}${editable&&i.task_view==='kanban'?`<select aria-label="Progress for ${esc(t.text)}" data-task-status="${esc(t.id)}" data-task-item="${esc(i.id)}">${['todo','doing','done'].map((s,n)=>`<option value="${s}" ${t.status===s?'selected':''}>${['To do','In progress','Done'][n]}</option>`).join('')}</select>`:''}</div>`;
return `<div class="task-content"><div class="task-summary">${tasks.filter(t=>t.status==='done').length} / ${tasks.length} complete ${editable?`<button data-task-view="${esc(i.id)}" class="quiet">${i.task_view==='kanban'?'Checklist':'Task board'}</button>`:''}</div>${i.task_view==='kanban'?`<div class="mini-kanban">${['todo','doing','done'].map((s,n)=>`<section data-task-lane="${s}" data-task-item="${esc(i.id)}"><h4>${['To do','In progress','Done'][n]}</h4>${tasks.filter(t=>t.status===s||!t.status&&s==='todo').map(row).join('')||'<p class="hint">Drop a task here</p>'}</section>`).join('')}</div>`:`<div class="task-checklist">${tasks.map(row).join('')}</div>`}</div>`}
function renderDraftTasks(){ $('#draft-task-list').innerHTML=draftTasks.map((t,n)=>`<div class="draft-task"><input data-draft-text="${n}" value="${esc(t.text)}" aria-label="Task ${n+1}" maxlength="300" placeholder="What needs doing?"><div class="task-details"><input type="date" data-draft-due="${n}" value="${esc(t.due||'')}" aria-label="Task ${n+1} due date"><input data-draft-owner="${n}" value="${esc(t.owner||'')}" aria-label="Task ${n+1} owner" placeholder="Who’s doing it?" maxlength="100"><select data-draft-status="${n}" aria-label="Task ${n+1} progress">${['todo','doing','done'].map((s,j)=>`<option value="${s}" ${t.status===s?'selected':''}>${['To do','In progress','Done'][j]}</option>`).join('')}</select><label class="check-label"><input type="checkbox" data-draft-fixed="${n}" ${t.fixed?'checked':''}>Fixed date</label><button type="button" class="quiet" data-draft-remove="${n}" aria-label="Remove task ${n+1}">×</button></div></div>`).join('');for(const field of ['text','due','owner','status','fixed'])$$(`[data-draft-${field}]`).forEach(el=>el.oninput=()=>{draftTasks[Number(el.dataset['draft'+field[0].toUpperCase()+field.slice(1)])][field]=field==='fixed'?el.checked:el.value});$$('[data-draft-remove]').forEach(el=>el.onclick=()=>{draftTasks.splice(Number(el.dataset.draftRemove),1);renderDraftTasks()})}
$('#draft-task-add').onclick=()=>{if(draftTasks.length>=200)return;draftTasks.push({id:crypto.randomUUID(),text:'',status:'todo',due:'',owner:'',fixed:false});renderDraftTasks();$$('[data-draft-text]').at(-1)?.focus()};
async function changeTask(itemId,taskId,status){const i=items.find(i=>i.id===itemId);if(!i||!canEditItem(i))return;try{await persistItem({...i,tasks:i.tasks.map(t=>t.id===taskId?{...t,status}:t)})}catch{toast('Could not save that task. Refresh and try again.')}}
function bindBoardExtras(){
 $$('[data-comment]').forEach(b=>b.onclick=()=>openComments(b.dataset.comment));$$('[data-seat]').forEach(b=>b.onclick=()=>openSeating(items.find(i=>i.id===b.dataset.seat)));
 $$('[data-task-check]').forEach(b=>b.onchange=()=>changeTask(b.dataset.taskItem,b.dataset.taskCheck,b.checked?'done':'todo'));
 $$('[data-task-status]').forEach(b=>b.onchange=()=>changeTask(b.dataset.taskItem,b.dataset.taskStatus,b.value));
 $$('[data-task-view]').forEach(b=>b.onclick=async()=>{const i=items.find(i=>i.id===b.dataset.taskView);try{await persistItem({...i,task_view:i.task_view==='kanban'?'checklist':'kanban'})}catch{toast('Could not switch task view')}});
 $$('[data-task-drag]').forEach(b=>b.ondragstart=e=>{internalDrag=true;e.dataTransfer.setData('application/x-wedding-task',JSON.stringify({item:b.dataset.taskItem,task:b.dataset.taskDrag}));e.stopPropagation()});
 $$('[data-task-lane]').forEach(lane=>{lane.ondragover=e=>{if(internalDrag){e.preventDefault();e.stopPropagation()}};lane.ondrop=e=>{if(!internalDrag)return;e.preventDefault();e.stopPropagation();try{const value=JSON.parse(e.dataTransfer.getData('application/x-wedding-task'));if(value.item===lane.dataset.taskItem)void changeTask(value.item,value.task,lane.dataset.taskLane)}catch{}internalDrag=false}});
}
async function loadCloud(){if(!user||loading)return;demo=false;loading=true;render();try{
 const invite=new URLSearchParams(location.search).get('invite');if(invite){try{boardOwner=check(await db.rpc('ws_accept_invite',{invite_token:invite}));history.replaceState(null,'',location.pathname);toast('Invitation accepted. Welcome to the wedding board.')}catch(e){toast(e.message);history.replaceState(null,'',location.pathname)}}
 const memberships=check(await db.from('wedding_studio_members').select('*').eq('member_id',user.id));
 if(!boardOwner||boardOwner!==user.id&&!memberships.some(m=>m.board_owner===boardOwner))boardOwner=user.id;
 let own=check(await db.from('wedding_studio_boards').select('*').eq('user_id',user.id).maybeSingle());if(!own&&boardOwner===user.id){if(!await requestTrialStart()){loading=false;board={title:'Our wedding',wedding_date:''};items=[];workspaces=[];render();return}check(await db.from('wedding_studio_boards').insert({user_id:user.id,title:'Our wedding'}));own=check(await db.from('wedding_studio_boards').select('*').eq('user_id',user.id).single())}
 workspaces=check(await db.from('wedding_studio_boards').select('*').in('user_id',[user.id,...memberships.map(m=>m.board_owner)]));board=workspaces.find(b=>b.user_id===boardOwner)||own;
 const member=memberships.find(m=>m.board_owner===boardOwner);memberRole=boardOwner===user.id?'owner':member?.role||'view';memberTags=member?.tags||null;
 items=await fileURLs(check(await db.from('wedding_studio_items').select('*').eq('user_id',boardOwner).order('created_at'))||[]);loading=false;busy(false);render();void enrichExisting();if(pendingCapture){const capture=pendingCapture;pendingCapture=null;void importCapture(capture)}
 const purchase=new URLSearchParams(location.search).get('purchase');if(purchase){try{const data=await checkoutCall('verify',{purchase_ref:purchase});if(data.paid){history.replaceState(null,'',location.pathname);toast('Your wedding workspace is purchased.');await loadCloud()}}catch(e){toast(e.message)}}
 }catch(e){loading=false;$('#board').innerHTML='<div class="empty"><h2>Your board couldn’t load.</h2><p>Your saved ideas are still in your account. Check your connection, then try again.</p><button class="button" id="retry">Try again</button></div>';$('#retry').onclick=loadCloud;toast(e.message||'Unable to load your board')}}
function renderWorkspaceControls(){if(!user&&!demo){boardOwner=null;memberRole='owner';memberTags=null}$('#workspace-label').hidden=!user||workspaces.length<2;$('#workspace-select').innerHTML=workspaces.map(b=>`<option value="${esc(b.user_id)}" ${b.user_id===boardOwner?'selected':''}>${esc(b.title)}${b.user_id===user?.id?' · Yours':' · Shared'}</option>`).join('');$('#collaborate-open').hidden=!isOwner();$('#settings').disabled=!isOwner();$('#brief-open').hidden=!isOwner();$('#manage-briefs').hidden=!isOwner();for(const id of ['board-add','templates-open','tidy'])$('#'+id).disabled=(user||demo)&&!canEditBoard();$('#trial-open').hidden=!!user&&!!board.created_at&&!demo;$('#access-title').textContent=!user||demo?'14 DAYS FREE · NO CARD REQUIRED':!isOwner()?'SHARED WEDDING WORKSPACE':board.paid_at?'YOUR WORKSPACE · PURCHASED':editingActive()?'YOUR FREE TRIAL':'YOUR TRIAL HAS ENDED';const trialEnd=board.created_at?new Date(new Date(board.created_at).getTime()+14*86400000):null;$('#access-state').textContent=demo?'Temporary example · Try the features, then sign in for your own board.':!user?'14 days free · One wedding workspace · Your partner and unlimited vendors.':board.paid_until?'Purchased · Editing available through '+new Date(board.paid_until).toLocaleDateString():trialEnd?'Trial through '+trialEnd.toLocaleDateString()+(!offer.ready?' · Checkout is being connected; editing stays available during setup.':' · Keep your work with a one-time purchase.'):'Your free trial starts with your wedding workspace.';$('#purchase-open').textContent=board.paid_at?'Your workspace access':`Pricing · $${offer.price_cents/100} one-time`;}
$('#workspace-select').onchange=()=>{boardOwner=$('#workspace-select').value;category='All inspiration';$('#search').value='';$('#status-filter').value='';void loadCloud()};
$('#refresh-board').onclick=()=>user?loadCloud():render();
let templateDraft=null;
$('#templates-open').onclick=()=>{if(!guard())return;$('#template-select').innerHTML=window.StudioTemplates.map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('');$('#template-start').value=board.planning_start||new Date().toISOString().slice(0,10);$('#template-end').value=board.wedding_date||'';$('#template-dates').innerHTML='';$('#template-error').textContent='';templateDraft=null;$('#template-import').disabled=true;$('#templates-modal').showModal()};
for(const id of ['template-select','template-start','template-end'])$('#'+id).onchange=()=>{templateDraft=null;$('#template-import').disabled=true;$('#template-dates').innerHTML=''};
$('#template-preview').onclick=()=>{try{const t=window.StudioTemplates.find(t=>t.id===$('#template-select').value);const start=$('#template-start').value,end=$('#template-end').value;templateDraft={template:t,start,end,tasks:StudioPlanning.schedule(t,start,end)};$('#template-error').textContent='';$('#template-dates').innerHTML=`<p class="hint">${templateDraft.tasks.length} tasks · ${esc(t.description)} <a href="${esc(t.source)}" target="_blank" rel="noopener">Read the original guide ↗</a></p>`+templateDraft.tasks.map(t=>`<div class="template-task"><span>${esc(t.text)}</span><small>${esc(t.due)}${t.due===start?' · Start now':''}</small></div>`).join('');$('#template-import').disabled=false}catch(e){templateDraft=null;$('#template-import').disabled=true;$('#template-error').textContent=e.message}};
$('#template-import').onclick=async()=>{if(!templateDraft||!guard())return;$('#template-import').disabled=true;try{const d=templateDraft;await persistItem({id:crypto.randomUUID(),title:d.template.title,kind:'checklist',tags:[category==='All inspiration'?(memberRole==='contribute'?memberTags?.[0]:'Planning'):category],category:'Planning',status:'Idea',notes:'Dates are a starting point. Adjust them for your own wedding.',tasks:d.tasks,task_view:'checklist',template_meta:{id:d.template.id,start:d.start,end:d.end,source:d.template.source},colors:[],x:25+items.length%3*320,y:25+Math.floor(items.length/3)*460});$('#templates-modal').close();$('#search').value='';$('#status-filter').value='';render();toast('Your editable plan is on the board.')}catch(e){$('#template-error').textContent=e.message;$('#template-import').disabled=false}};
async function openComments(id){commentsItem=items.find(i=>i.id===id);$('#comments-title').textContent=commentsItem.title;$('#comment-error').textContent='';$('#comment-body').value='';$('#comment-form').hidden=!demo&&(!editingActive()||memberRole==='view');$('#comments-modal').showModal();await loadComments()}
async function loadComments(){try{const list=demo?exampleComments.filter(c=>c.item_id===commentsItem.id):check(await db.from('wedding_studio_comments').select('*').eq('item_id',commentsItem.id).order('created_at'));$('#comments-list').innerHTML=list.length?list.map(c=>`<article class="comment"><b>${esc(c.author_name)}</b><small>${new Date(c.created_at).toLocaleString()}</small><p>${esc(c.body)}</p></article>`).join(''):'<p class="hint">Ask a question, suggest a change, or explain what you love.</p>'}catch(e){$('#comment-error').textContent=e.message}}
$('#comment-form').onsubmit=async e=>{e.preventDefault();const c={id:crypto.randomUUID(),item_id:commentsItem.id,author_id:user?.id,author_name:$('#comment-name').value.trim(),body:$('#comment-body').value.trim()};if(!c.body||!c.author_name)return;try{if(demo)exampleComments.push({...c,created_at:new Date().toISOString()});else check(await db.from('wedding_studio_comments').insert(c));$('#comment-body').value='';await loadComments()}catch(e){$('#comment-error').textContent=e.message}};
$('#collaborate-open').onclick=async()=>{if(!guard()||!isOwner())return;$('#people-feedback').textContent='';$('#invite-result').hidden=true;$('#invite-email').value='';$('#invite-tags').innerHTML=allTags().map(t=>`<label><input type="checkbox" value="${esc(t)}">${esc(t)}</label>`).join('');$('#people-modal').showModal();await listPeople()};
$('#invite-role').onchange=()=>$('#invite-tag-field').hidden=$('#invite-role').value==='partner';
async function listPeople(){if(demo){$('#people-list').innerHTML='<p class="hint">Sign in to invite your partner and vendors to a saved board. This example lets you explore the permissions.</p>';return}const [members,invites]=await Promise.all([db.from('wedding_studio_members').select('*').eq('board_owner',boardOwner),db.from('wedding_studio_invites').select('*').eq('board_owner',boardOwner).is('accepted_at',null)]);const list=[...check(members).map(m=>({...m,type:'member',key:m.member_id})),...check(invites).map(m=>({...m,type:'invite',key:m.id}))];$('#people-list').innerHTML=list.map(m=>`<div class="shared-row"><b>${esc(m.email)}</b><p>${esc(m.role)} · ${m.tags?m.tags.map(esc).join(', '):'All tags'}${m.type==='invite'?' · Pending invitation':''}</p><button class="quiet" data-remove-person="${esc(m.key)}" data-person-type="${m.type}">Revoke access</button></div>`).join('');$$('[data-remove-person]').forEach(b=>b.onclick=async()=>{if(!await confirmAction('Revoke this access?','This person will lose access to your board. You can invite them again later.'))return;try{if(b.dataset.personType==='member')check(await db.from('wedding_studio_members').delete().eq('board_owner',boardOwner).eq('member_id',b.dataset.removePerson));else check(await db.from('wedding_studio_invites').delete().eq('id',b.dataset.removePerson));await listPeople();toast('Access revoked')}catch(e){$('#people-feedback').textContent=e.message}})}
$('#invite-form').onsubmit=async e=>{e.preventDefault();if(demo){$('#people-feedback').textContent='Sign in to create real invitations from your saved board.';return}const role=$('#invite-role').value,tags=role==='partner'?null:$$('#invite-tags input:checked').map(el=>el.value);if(tags&&!tags.length){$('#people-feedback').textContent='Choose at least one tag to share.';return}try{const data=check(await db.from('wedding_studio_invites').insert({board_owner:boardOwner,email:$('#invite-email').value.trim().toLowerCase(),role,tags}).select('token').single());$('#invite-link').value=AUTH_RETURN_URL+'?invite='+data.token;$('#invite-result').hidden=false;$('#people-feedback').textContent='';await listPeople()}catch(e){$('#people-feedback').textContent=e.message}};
$('#copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText($('#invite-link').value);toast('Invitation copied. Send it to the email you invited.')}catch{$('#invite-link').select()}};
const freeTools=[['Just engaged? Build a starting plan','just-engaged/'],['Tips, guides & printable timelines','../tips-timelines/'],['Wedding budget','budget/'],['Can I afford this?','can-i-afford-this/'],['DIY or hire?','diy-or-hire/'],['Wedding hashtag generator','hashtag-generator/']];
$('#tool-links').innerHTML=freeTools.map(([name,path])=>`<div class="tool-row"><a href="/weddings/tools/${path}" target="_blank" rel="noopener">${esc(name)} ↗</a><button class="quiet" data-tool="${esc(path)}">Add to board</button></div>`).join('');
$('#tools-open').onclick=()=>$('#tools-modal').showModal();$$('[data-tool]').forEach(b=>b.onclick=async()=>{if(!guard())return;try{const name=freeTools.find(t=>t[1]===b.dataset.tool)[0];await persistItem({id:crypto.randomUUID(),title:name,kind:'link',url:new URL('/weddings/tools/'+b.dataset.tool,location.origin).href,tags:[category==='All inspiration'?(memberRole==='contribute'?memberTags?.[0]:'Planning tools'):category],category:'Planning tools',status:'Idea',notes:'Open this free TSS tool. Add your results and decisions in these notes.',colors:[],preview:{site:'Tiny Site Studios'},x:25+items.length%3*300,y:25+Math.floor(items.length/3)*450});$('#tools-modal').close();toast('Tool added to your planning board.')}catch(e){toast(e.message)}});
async function checkoutCall(action,body={}){const session=check(await db.auth.getSession()).session;if(!session)throw Error('Sign in to purchase your wedding workspace.');const r=await fetch(URL_BASE+'/functions/v1/wedding-studio-checkout?action='+action,{method:'POST',headers:{'Content-Type':'application/json',apikey:API_KEY,Authorization:'Bearer '+session.access_token},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Checkout unavailable');return d}
$('#purchase-open').onclick=()=>{const needsTrial=!user||demo||!board.created_at;$('#purchase-price').innerHTML=`$${offer.price_cents/100} <small>one-time ${offer.introductory?'introductory price':'purchase'}</small>`;$('#purchase-feedback').textContent=board.paid_until?'Purchased. Editing through '+new Date(board.paid_until).toLocaleDateString():needsTrial?'Try everything free for 14 days first. No card required, and no automatic charge.':!isOwner()?'This is a shared workspace. Its owner manages the purchase.':offer.ready?'Pay securely with Square. Your purchase is linked to your account.':'Checkout is being connected. Your board remains editable during setup.';$('#pricing-trial').hidden=!needsTrial;$('#checkout-start').hidden=needsTrial;$('#checkout-start').disabled=!user||!offer.ready||!!board.paid_at||demo||!isOwner();$('#purchase-modal').showModal()};
let pendingTrial=null;
function showPendingTrial(){if(!pendingTrial||$$('dialog[open]').length)return;$('#trial-price').textContent=`Then $${offer.price_cents/100} one-time${offer.introductory?' at launch · Regular price $49':''}. No subscription.`;$('#trial-modal').showModal()}
function requestTrialStart(){if(pendingTrial)return pendingTrial.promise;let resolve;const promise=new Promise(r=>resolve=r);pendingTrial={promise,resolve,userId:user.id};if($('#tour').open||$('#tour').hasAttribute('open'))$('#tour').close();showPendingTrial();return promise}
function finishTrialStart(accepted){const pending=pendingTrial;pendingTrial=null;$('#trial-modal').close();pending?.resolve(accepted&&user?.id===pending.userId)}
$('#trial-confirm').onclick=()=>finishTrialStart(true);
$('#trial-later').onclick=()=>finishTrialStart(false);
$('#trial-modal').addEventListener('cancel',e=>{e.preventDefault();finishTrialStart(false)});
$$('dialog').forEach(dialog=>dialog.addEventListener('close',()=>setTimeout(showPendingTrial,0)));
function startFreeTrial(){if(!user){showAuth();authMode='signup';setAuthMode();return}boardOwner=user.id;void loadCloud()}
$('#trial-open').onclick=startFreeTrial;
$('#pricing-trial').onclick=()=>{$('#purchase-modal').close();startFreeTrial()};
$('#checkout-start').onclick=async()=>{if(!user||!isOwner())return;$('#checkout-start').disabled=true;try{const d=await checkoutCall('checkout');location.assign(d.url)}catch(e){$('#purchase-feedback').textContent=e.message;$('#checkout-start').disabled=false}};
$('#export-board').onclick=()=>{const data={wedding:board.title,wedding_date:board.wedding_date,items:items.map(i=>{const c={...i};delete c.user_id;delete c.file_path;delete c.file_url;return c})};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='my-wedding-studio.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Board downloaded. Download original attachments from their cards.');};
// Refresh shared content while idle; leave open editors untouched.
let refreshTimer=setInterval(()=>{if(user&&board.created_at&&!loading&&!importing&&!document.hidden&&!$$('dialog[open]').length)void loadCloud()},30000);window.addEventListener('pagehide',()=>clearInterval(refreshTimer));
async function loadOffer(){try{const r=await fetch(URL_BASE+'/functions/v1/wedding-studio-checkout?action=status');if(r.ok)offer=await r.json();renderWorkspaceControls()}catch{}}
let seatDraft=null,seatItem=null,seatRoom=null;
function mountSeatRoom(){const host=$('#seating-room'),guests=()=>seatDraft.guests,tableGuests=id=>guests().filter(g=>g.table===id),tableById=id=>seatDraft.tables.find(t=>t.id===id),unassignedGuests=()=>guests().filter(g=>!g.table),render=()=>{host.innerHTML=seatRoom.markup();seatRoom.bind()};seatRoom=SeatingRoom.create({app:host,tables:seatDraft.tables,guests,tableGuests,tableById,unassignedGuests,isAttending:()=>true,esc,storage:false,snapshot:()=>JSON.stringify({guests:seatDraft.guests,room:seatRoom?.snapshot()}),saveChange:()=>{$('#seating-feedback').textContent='Unsaved changes · Save seating plan to keep them on your board.'},toast,render});if(seatDraft.room)seatRoom.restore(seatDraft.room);render()}
function openSeating(item=null){if(!user&&!demo){showAuth();return}seatItem=item||items.find(i=>i.kind==='seating');seatDraft=structuredClone(seatItem?.seating||{guests:[],tables:Array.from({length:6},(_,n)=>({id:'table-'+(n+1),number:n+1,name:'Table '+(n+1),capacity:8,note:''}))});if(!seatDraft.guests)seatDraft.guests=[];$('#seating-guests').value=seatDraft.guests.map(g=>g.name).join('\n');$('#seating-tables').value=seatDraft.tables.length;$('#seating-feedback').textContent=seatItem?'Saved on your wedding board.':'Start with your guest list. This plan is included in your workspace.';$('#seating-setup').open=!seatDraft.guests.length;$('#seating-modal').showModal();mountSeatRoom();const editable=seatItem?canEditItem(seatItem):canEditBoard();$('#seating-save').disabled=!editable;$('#seating-apply').disabled=!editable;$('#seating-room').inert=!editable;$('#seating-guests').disabled=!editable;$('#seating-tables').disabled=!editable}
$('#seating-open').onclick=()=>openSeating();
$('#seating-apply').onclick=()=>{if(!canEditBoard())return;const names=$('#seating-guests').value.split('\n').map(s=>s.trim().slice(0,120)).filter(Boolean);if(names.length>500){$('#seating-feedback').textContent='Use up to 500 guests.';return}const count=Number($('#seating-tables').value);if(!Number.isInteger(count)||count<1||count>30){$('#seating-feedback').textContent='Choose between 1 and 30 tables.';return}seatDraft.room=seatRoom.snapshot();const used=new Set();seatDraft.guests=names.map(name=>{const old=seatDraft.guests.find(g=>g.name===name&&!used.has(g.id));if(old)used.add(old.id);return old||{id:crypto.randomUUID(),name,table:null,meal:'',dietary:'',accessibility:'',group:''}});seatDraft.tables=Array.from({length:count},(_,n)=>seatDraft.tables[n]||{id:'table-'+(n+1),number:n+1,name:'Table '+(n+1),capacity:8,note:''});seatDraft.guests.forEach(g=>{if(!seatDraft.tables.some(t=>t.id===g.table))g.table=null});mountSeatRoom();$('#seating-feedback').textContent='Guest list applied · Save seating plan to keep it.';};
$('#seating-save').onclick=async()=>{if(!guard())return;$('#seating-save').disabled=true;try{seatDraft.room=seatRoom.snapshot();const i={...seatItem,id:seatItem?.id||crypto.randomUUID(),kind:'seating',title:seatItem?.title||'Our seating plan',tags:seatItem?tagsFor(seatItem):[memberRole==='contribute'?memberTags?.[0]:'Reception'],category:'Reception',status:seatItem?.status||'Idea',notes:seatItem?.notes||'',colors:[],seating:seatDraft,x:seatItem?.x??25+items.length%3*300,y:seatItem?.y??25+Math.floor(items.length/3)*460};await persistItem(i);seatItem=i;$('#seating-feedback').textContent='Saved to your wedding board.';toast('Seating plan saved.')}catch(e){$('#seating-feedback').textContent=e.message}finally{$('#seating-save').disabled=false}};
$('#seating-print').onclick=()=>{const w=window.open('','_blank');if(!w){toast('Allow pop-ups to print your seating plan.');return}w.opener=null;const markup=seatDraft.tables.map(t=>`<section><h2>${esc(t.name)}</h2><p>${seatDraft.guests.filter(g=>g.table===t.id).length} / ${t.capacity} seats</p><ol>${seatDraft.guests.filter(g=>g.table===t.id).map(g=>`<li>${esc(g.name)}</li>`).join('')}</ol></section>`).join('');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(board.title)} · Seating plan</title><style>body{font-family:Arial,sans-serif;max-width:900px;margin:40px auto;padding:20px;color:#172c3a}section{break-inside:avoid;border:1px solid #ddd;padding:20px;margin:20px 0}li{margin:8px 0}@media print{button{display:none}}</style></head><body><button onclick="window.print()">Print / Save PDF</button><h1>${esc(board.title)} · Seating plan</h1><p>${esc(board.wedding_date)} · ${seatDraft.guests.length} guests</p>${markup}<section><h2>Still to place</h2><p>${seatDraft.guests.filter(g=>!g.table).map(g=>esc(g.name)).join(', ')||'Everyone is placed.'}</p></section><footer>Prepared with The Wedding Studio by TSS</footer></body></html>`);w.document.close()};
// Store view preference only; wedding content remains in the account.
try{const preferred=localStorage.getItem('wedding-studio-view');if(['cards','canvas'].includes(preferred))view=preferred}catch{}
for(const [id,value] of [['cards-view','cards'],['canvas-view','canvas']])$('#'+id).onclick=()=>{view=value;try{localStorage.setItem('wedding-studio-view',view)}catch{}render()};
init();void loadOffer();
