'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const URL_BASE='https://ubovuhkvtwijtzofsobs.supabase.co';
const API_KEY='sb_publishable_ZgDHWGLNW9xc9IXfwAjaDg_DH5xVNa8';
const sections=['Sort later','Ceremony','Reception','Flowers','Attire & beauty','Music','Stationery','Documents'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
const domain=v=>{try{return new URL(v).hostname.replace(/^www\./,'')}catch{return ''}};
let db=null,user=null,items=[],board={title:'Our wedding',wedding_date:''},category='All inspiration',view='cards',demo=false,editing=null,kind='note',authMode='login',loading=false,selected=new Set(),confirmResolve=null;
let toastTimer,initializing=true,draftPreview={},pendingCapture=null,importing=false;
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500)}
function check(r){if(r.error)throw r.error;return r.data}
function busy(state){$('#save-state').textContent=state?'Saving…':demo?'Temporary example':'Saved to your account'}
function guard(){if(demo||user)return true;showAuth();return false}
function showAuth(){authMode='login';setAuthMode();$('#auth').showModal()}
function setAuthMode(){const reset=authMode==='reset';$('#auth-title').textContent=reset?'Choose a new password.':authMode==='signup'?'Your studio starts here.':'Welcome to your studio.';$('#auth-submit').textContent=reset?'Update password':authMode==='signup'?'Create account':'Sign in';$('#auth-toggle').textContent=authMode==='signup'?'I already have an account':'Create an account';$('#email-label').hidden=reset;$('#auth-email').required=!reset;$('#auth-password').autocomplete=authMode==='login'?'current-password':'new-password';$('#auth-toggle').hidden=reset;$('#forgot').hidden=reset;$('#auth-error').textContent='';$('#auth-next').hidden=true;$('#auth-submit').hidden=false}
function confirmAction(title,text){$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;$('#confirm-modal').showModal();return new Promise(r=>confirmResolve=r)}
$('#confirm-yes').onclick=()=>{confirmResolve?.(true);confirmResolve=null;$('#confirm-modal').close()};$('#confirm-cancel').onclick=()=>{$('#confirm-modal').close()};$('#confirm-modal').onclose=()=>{confirmResolve?.(false);confirmResolve=null};
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function statusClass(s){return s==='Chosen'?'chosen':s==='Shortlist'?'shortlist':s==='Purchased / booked'?'purchased':''}
function previewImage(i){return i.kind==='image'||i.kind==='link'&&/^image\//.test(i.file_type||'')?i.file_url||safeUrl(i.preview?.image):safeUrl(i.preview?.image)}
function cardHTML(i,readonly=false){const image=previewImage(i);const colors=Array.isArray(i.colors)?i.colors.filter(c=>/^#[0-9a-f]{6}$/i.test(c)):[];const href=safeUrl(i.url),provider=domain(href),pin=/(^|\.)pinterest\.[a-z.]+$|(^|\.)pin\.it$/.test(provider),music=/spotify|music.apple|soundcloud|youtube|youtu.be/.test(provider);const fallback=href?`<div class="link-art ${pin?'pin-art':music?'music-art':''}"><span class="link-art-symbol">${pin?'P':music?'♫':'↗'}</span><span>${pin?'Pinterest inspiration':music?'A soundtrack for your day':esc(i.preview?.site||provider)}</span><small>${pin?'Open the original pin':music?'Open to listen':'An idea worth keeping'}</small></div>`:'';let media=image?`<div class="preview-media"><img class="card-media" src="${esc(image)}" alt="${esc(i.title)}" loading="lazy" referrerpolicy="no-referrer"><div class="image-fallback">${fallback||'<span>Image unavailable · open the original below</span>'}</div></div>`:i.kind==='palette'?`<div class="palette">${colors.map(c=>`<span style="background:${c}" title="${c}"></span>`).join('')}</div>`:i.kind==='file'?`<div class="file-symbol">▤ <span>${esc((i.file_name||'Document').split('.').pop())}</span></div>`:fallback;
if(href)media=`<a class="preview-link" href="${esc(href)}" target="_blank" rel="noopener noreferrer" aria-label="Open ${esc(i.title)}">${media}</a>`;
return `<article class="card" data-id="${esc(i.id)}" ${view==='canvas'&&!readonly?`style="left:${i.x||0}px;top:${i.y||0}px"`:''}><div class="card-top"><span>${esc(i.category)}</span>${!readonly?`<button class="drag" data-drag="${esc(i.id)}" aria-label="Move ${esc(i.title)}" title="Drag in Canvas view; use arrow keys to move">⠿</button>`:''}</div>${media}<div class="card-body"><h3>${esc(i.title)}</h3>${i.preview?.description?`<p class="preview-description">${esc(i.preview.description)}</p>`:''}${i.notes?`<p class="card-notes">${esc(i.notes)}</p>`:''}${href?`<a class="link-domain" href="${esc(href)}" target="_blank" rel="noopener noreferrer">↗ ${esc(provider)}${pin?' · Pinterest':i.kind==='link'?' · Open link':''}</a>`:''}${i.file_url?`<a class="link-domain" href="${esc(i.file_url)}" target="_blank" rel="noopener noreferrer">${i.kind==='image'?'View original':i.kind==='link'?'View cover':'Open attachment'} · ${esc(i.file_name||'File')}</a>`:''}${i.file_path&&!i.file_url?'<p class="hint">Attachment unavailable. Reload to try again.</p>':''}${href&&!image&&!readonly?`<p class="preview-hint">${demo?'Sign in for automatic previews':'No cover available · add one in Edit details'}</p>`:''}</div>${colors.length?`<div class="palette-codes">${colors.map(esc).join(' · ')}</div>`:''}<div class="card-footer"><span class="status ${statusClass(i.status)}">${esc(i.status)}</span>${readonly?'':`<button class="card-edit" data-edit="${esc(i.id)}">Edit details</button>`}</div></article>`}
// Broken hotlinked images have a useful fallback, including on shared briefs.
document.addEventListener('error',e=>{if(e.target.matches?.('.preview-media img'))e.target.closest('.preview-media').classList.add('image-failed')},true);
function filtered(){const q=$('#search').value.toLowerCase(),s=$('#status-filter').value;return items.filter(i=>(category==='All inspiration'||i.category===category)&&(!s||i.status===s)&&(!q||[i.title,i.notes,i.category,i.file_name,i.url].join(' ').toLowerCase().includes(q)))}
function render(){
$('#board-title').textContent=board.title;$('#board-subtitle').textContent=board.wedding_date?new Date(board.wedding_date+'T12:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'}):'A home for everything you’re dreaming up.';
$('#account').textContent=user?'Sign out':'Sign in / create account';$('#notice').hidden=!!user&&!demo;
if(demo)$('#notice').innerHTML='<span><b>Example board.</b> Changes here are temporary and disappear when you leave. Sign in for your own private, cloud-saved board.</span><button id="demo-signin">Save my own board</button>';
else if(!user)$('#notice').innerHTML='<span><b>Your ideas deserve a home.</b> Sign in to save a private board across devices, or explore a temporary example.</span><button id="demo">Try example board</button>';
$('#demo')?.addEventListener('click',loadDemo);$('#demo-signin')?.addEventListener('click',()=>showAuth());
$('#categories').innerHTML=['All inspiration',...sections].map((s,n)=>`<button class="nav-item ${s===category?'active':''}" data-section="${esc(s)}"><span>${n===0?'▦':s==='Sort later'?'＋':'·'} &nbsp;${esc(s)}</span><small>${s==='All inspiration'?items.length:items.filter(i=>i.category===s).length}</small></button>`).join('');
$$('[data-section]').forEach(b=>b.onclick=()=>{category=b.dataset.section;render()});
$('#section-name').textContent=category;$('#canvas-help').hidden=view!=='canvas';$('#cards-view').classList.toggle('active',view==='cards');$('#canvas-view').classList.toggle('active',view==='canvas');$('#cards-view').setAttribute('aria-pressed',String(view==='cards'));$('#canvas-view').setAttribute('aria-pressed',String(view==='canvas'));const list=filtered();$('#count').textContent=`${list.length} item${list.length!==1?'s':''}`;const el=$('#board');el.className='board'+(view==='canvas'&&list.length?' canvas':'');el.style.minHeight=view==='canvas'&&list.length?Math.max(900,...list.map(i=>(i.y||0)+530))+'px':'';el.style.minWidth=view==='canvas'&&list.length?Math.max(1100,...list.map(i=>(i.x||0)+300))+'px':'';
if(loading){el.innerHTML='<div class="loading">Opening your private board…</div>';return}
if(!list.length){const has=items.length>0;el.innerHTML=`<div class="empty"><div class="empty-mark">＋</div><h2>${has?'Room for the next idea.':'Every beautiful day starts somewhere.'}</h2><p>${has?'No items match this section or filter. Add an idea here, or explore another section.':'Drop in the flowers you love, the song you’ll dance to, or the little details you don’t want to forget.'}</p><button class="button primary" id="empty-add">＋ Add your first idea</button><button class="button" id="empty-upload">Upload a photo or file</button></div>`;$('#empty-add').onclick=()=>openEditor('note');$('#empty-upload').onclick=()=>openEditor('file');return}
el.innerHTML=list.map(i=>cardHTML(i)).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(null,items.find(i=>i.id===b.dataset.edit)));$$('[data-drag]').forEach(b=>{b.onpointerdown=startDrag;b.onkeydown=moveKey});
}
async function fileURLs(list){if(demo)return list;return Promise.all(list.map(async i=>{if(!i.file_path)return i;try{const data=check(await db.storage.from('wedding-studio').createSignedUrl(i.file_path,3600));return {...i,file_url:data.signedUrl}}catch{return {...i,file_url:null}}}))}
async function loadCloud(){if(!user)return;demo=false;loading=true;render();try{const [b,r]=await Promise.all([db.from('wedding_studio_boards').select('*').eq('user_id',user.id).maybeSingle(),db.from('wedding_studio_items').select('*').eq('user_id',user.id).order('created_at')]);board=check(b)||{title:'Our wedding',wedding_date:''};items=await fileURLs(check(r)||[]);loading=false;busy(false);render();void enrichExisting();if(pendingCapture){const capture=pendingCapture;pendingCapture=null;void importCapture(capture)}}catch(e){loading=false;$('#board').innerHTML='<div class="empty"><h2>Your board couldn’t load.</h2><p>Please check your connection, then try again. Your saved ideas are still in your account.</p><button class="button" id="retry">Try again</button></div>';$('#retry').onclick=loadCloud;toast(e.message||'Unable to load your board')}}
function loadDemo(){if(user)return;demo=true;board={title:'Alex & Jordan',wedding_date:'2027-10-09'};items=[{id:crypto.randomUUID(),kind:'image',title:'A little garden magic',notes:'Love the loose greenery and the soft white flowers. Keep it relaxed, not too formal.',category:'Flowers',status:'Shortlist',file_url:'/weddings/demos/garden/assets/gallery-1.jpg',file_name:'floral-inspiration.jpg',x:25,y:25},{id:crypto.randomUUID(),kind:'palette',title:'Our color story',notes:'Deep navy, plum, and a little fresh green.',colors:['#172C3A','#743B61','#43867B','#F7F4EF'],category:'Reception',status:'Chosen',x:320,y:50},{id:crypto.randomUUID(),kind:'note',title:'The feeling we’re after',notes:'A really good dinner party with all our favorite people. Candlelight, personal touches, and a dance floor that stays full.',category:'Ceremony',status:'Idea',x:620,y:25},{id:crypto.randomUUID(),kind:'link',title:'An intimate garden celebration',notes:'A little inspiration for the atmosphere. Save product links, pins, and playlists this way too.',url:'https://tinysitestudios.com/weddings/demos/garden/',preview:{image:'https://tinysitestudios.com/weddings/demos/garden/assets/gallery-1.jpg',description:'Loose greenery, warm light, and all our favorite people.',site:'Tiny Site Studios'},category:'Reception',status:'Idea',x:320,y:350},{id:crypto.randomUUID(),kind:'note',title:'One less thing to remember',notes:'Add the vendor quote beside the idea it belongs to. When you decide, mark it “Chosen” and include it in your vendor brief.',category:'Sort later',status:'Idea',x:620,y:330}];busy(false);render()}
function setKind(k){kind=k;$$('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===k||(k==='image'&&b.dataset.kind==='file')));$('#link-fields').hidden=k!=='link';$('#file-fields').hidden=!['file','image','link'].includes(k);$('#upload-label').textContent=k==='link'?'Upload a cover image (optional)':'Choose an image or file';$('#upload-hint').textContent=k==='link'?'JPG, PNG, WebP, GIF, or AVIF · up to 15 MB':'Images, PDFs, documents, audio, or video · up to 15 MB each';$('#item-file').accept=k==='link'?'image/jpeg,image/png,image/webp,image/gif,image/avif':'';$('#remove-cover').hidden=k!=='link'||!editing?.file_name;$('#palette-fields').hidden=k!=='palette';$('#item-url').required=k==='link'}
function openEditor(k='note',item=null){if(!guard())return;editing=item;draftPreview=item?.preview||{};$('#preview-feedback').textContent='';$('#item-form').reset();$('#editor-error').textContent='';$('#editor-title').textContent=item?'Edit your idea':'Add to your board';$('#delete-item').hidden=!item;$('#item-title').value=item?.title||'';$('#item-url').value=item?.url||'';$('#item-notes').value=item?.notes||'';$('#item-category').value=item?.category||(category==='All inspiration'?'Sort later':category);$('#item-status').value=item?.status||'Idea';$('#item-colors').value=item?.colors?.join(', ')||'';$('#attached').textContent=item?.file_name?'Attached: '+item.file_name:'';setKind(item?.kind||k);$('#editor').showModal()}
async function persistItem(item){if(demo){items=items.some(i=>i.id===item.id)?items.map(i=>i.id===item.id?item:i):[...items,item];render();return item}const copy={...item,user_id:user.id};delete copy.file_url;delete copy.created_at;check(await db.from('wedding_studio_items').upsert(copy));const hydrated=(await fileURLs([item]))[0];items=items.some(i=>i.id===item.id)?items.map(i=>i.id===item.id?hydrated:i):[...items,hydrated];render();return hydrated}
$('#item-form').onsubmit=async e=>{e.preventDefault();const title=$('#item-title').value.trim(),file=$('#item-file').files[0];if(!title)return;let colors=[];if(kind==='palette'){colors=$('#item-colors').value.split(',').map(s=>s.trim().toUpperCase()).filter(Boolean);if(!colors.length||colors.length>6||colors.some(c=>!/^#[0-9A-F]{6}$/.test(c))){$('#editor-error').textContent='Use one to six six-digit hex colors, such as #743B61.';return}}
if(kind==='link'&&!safeUrl($('#item-url').value)){$('#editor-error').textContent='Use a complete http or https link.';return}if(['file','image'].includes(kind)&&!file&&!editing?.file_path&&!editing?.file_url){$('#editor-error').textContent='Choose a file to upload.';return}if(file&&kind==='link'&&!/^image\/(jpeg|png|webp|gif|avif)$/.test(file.type)){$('#editor-error').textContent='Choose a JPG, PNG, WebP, GIF, or AVIF cover image.';return}if(file&&file.size>15*1024*1024){$('#editor-error').textContent='This file is larger than 15 MB. Use a smaller file or save a link instead.';return}$('#item-save').disabled=true;busy(true);let uploaded=null;
try{const i={id:editing?.id||crypto.randomUUID(),title,kind,category:$('#item-category').value,status:$('#item-status').value,notes:$('#item-notes').value.trim(),url:kind==='link'?safeUrl($('#item-url').value):'',colors,x:editing?.x??25+(items.length%3)*290,y:editing?.y??25+Math.floor(items.length/3)*420,file_path:editing?.file_path||null,file_name:editing?.file_name||null,file_type:editing?.file_type||null,file_url:editing?.file_url||null,preview:kind==='link'?draftPreview:{}};if(file&&['file','image','link'].includes(kind)){const image=/^image\/(jpeg|png|webp|gif|avif)$/.test(file.type);i.kind=kind==='link'?'link':image?'image':'file';i.file_name=file.name;i.file_type=file.type||'application/octet-stream';if(demo)i.file_url=URL.createObjectURL(file);else{const path=user.id+'/'+crypto.randomUUID()+'/'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');check(await db.storage.from('wedding-studio').upload(path,file,{contentType:i.file_type,upsert:false}));i.file_path=path;uploaded=path}}if(!['file','image','link'].includes(kind)){i.file_path=null;i.file_name=null;i.file_type=null;i.file_url=null}await persistItem(i);if(i.kind==='link'&&!i.preview?.checked_at)void enrichItem(i.id,false);$('#editor').close();toast(demo?'Added to the temporary example':'Saved to your board')}catch(err){if(uploaded)await db.storage.from('wedding-studio').remove([uploaded]);$('#editor-error').textContent=err.message||'Could not save. Your details are still here; please try again.'}finally{$('#item-save').disabled=false;busy(false)}};
$('#item-file').onchange=()=>{const f=$('#item-file').files[0];if(f&&!$('#item-title').value)$('#item-title').value=f.name.replace(/\.[^.]+$/,'').slice(0,200)};
$('#delete-item').onclick=async()=>{if(!editing)return;const i=editing;if(!await confirmAction('Delete this idea?','This removes it from your board. Existing vendor briefs keep their snapshots until you revoke them.'))return;try{if(!demo)check(await db.from('wedding_studio_items').delete().eq('id',i.id).eq('user_id',user.id));items=items.filter(x=>x.id!==i.id);$('#editor').close();render();toast('Idea removed')}catch(e){toast(e.message)}};
async function savePosition(i,x,y){const old={x:i.x,y:i.y};i.x=x;i.y=y;busy(true);try{if(!demo)check(await db.from('wedding_studio_items').update({x,y}).eq('id',i.id).eq('user_id',user.id));render()}catch(e){Object.assign(i,old);render();toast('Position could not save. Try again.')}finally{busy(false)}}
function startDrag(e){if(view!=='canvas')return;if(e.button!==0)return;const handle=e.currentTarget,card=handle.closest('.card'),i=items.find(i=>i.id===handle.dataset.drag);const startX=e.clientX,startY=e.clientY,ox=i.x||0,oy=i.y||0;handle.setPointerCapture(e.pointerId);let x=ox,y=oy;handle.onpointermove=ev=>{x=Math.max(0,Math.min(10000,ox+ev.clientX-startX));y=Math.max(0,Math.min(10000,oy+ev.clientY-startY));card.style.left=x+'px';card.style.top=y+'px'};handle.onpointerup=()=>{handle.onpointermove=null;handle.onpointerup=null;if(x!==ox||y!==oy)savePosition(i,Math.round(x),Math.round(y))};handle.onpointercancel=()=>{handle.onpointermove=null;render()}}
function moveKey(e){if(view!=='canvas'||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const i=items.find(i=>i.id===e.currentTarget.dataset.drag),step=e.shiftKey?50:10;const x=Math.max(0,Math.min(10000,i.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0))),y=Math.max(0,Math.min(10000,i.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)));savePosition(i,x,y).then(()=>document.querySelector(`[data-drag="${i.id}"]`)?.focus())}
$('#tidy').onclick=async()=>{if(!guard())return;const list=filtered();busy(true);try{for(let n=0;n<list.length;n++){const i=list[n],x=25+n%3*290,y=25+Math.floor(n/3)*460;if(!demo)check(await db.from('wedding_studio_items').update({x,y}).eq('id',i.id).eq('user_id',user.id));i.x=x;i.y=y}render();toast('Canvas arranged')}catch(e){toast('Could not finish arranging. Try again.')}finally{busy(false)}};
$('#settings').onclick=()=>{if(!guard())return;$('#wedding-title').value=board.title;$('#wedding-date').value=board.wedding_date;$('#wedding-settings').showModal()};$('#settings-form').onsubmit=async e=>{e.preventDefault();const b={title:$('#wedding-title').value.trim(),wedding_date:$('#wedding-date').value};if(!b.title)return;try{if(!demo)check(await db.from('wedding_studio_boards').upsert({...b,user_id:user.id,updated_at:new Date().toISOString()}));board=b;render();$('#wedding-settings').close();toast('Wedding details saved')}catch(err){toast(err.message)}};
function briefChoices(){const list=filtered();$('#brief-choices').innerHTML=list.length?list.map(i=>`<label class="brief-choice"><input type="checkbox" value="${i.id}" ${selected.has(i.id)?'checked':''}>${previewImage(i)?`<img src="${esc(previewImage(i))}" alt="" referrerpolicy="no-referrer">`:''}<span>${esc(i.title)}<small>${esc(i.category)} · ${esc(i.status)}</small></span></label>`).join(''):'<p class="hint" style="padding:20px">Add ideas to this board or adjust your filters first.</p>';$$('#brief-choices input').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.value):selected.delete(c.value);$('#selected-count').textContent=selected.size+' selected'});$('#selected-count').textContent=selected.size+' selected'}
$('#brief-open').onclick=()=>{if(!guard())return;selected=new Set();$('#brief-title').value='';$('#brief-instructions').value='';$('#brief-error').textContent='';$('#brief-result').hidden=true;$('#create-brief').disabled=false;briefChoices();$('#brief-modal').showModal()};$('#select-chosen').onclick=()=>{selected=new Set(filtered().filter(i=>['Chosen','Purchased / booked'].includes(i.status)).map(i=>i.id));briefChoices()};$('#clear-selection').onclick=()=>{selected.clear();briefChoices()};
function briefPayload(){if(!selected.size)throw Error('Select at least one item for this brief.');if(selected.size>100)throw Error('Please choose up to 100 items per brief.');return {wedding:board.title,date:board.wedding_date,instructions:$('#brief-instructions').value.trim(),items:items.filter(i=>selected.has(i.id)).map(i=>{const copy={...i};delete copy.user_id;delete copy.created_at;if(!demo)delete copy.file_url;return copy})}}
$('#create-brief').onclick=async()=>{if(demo){$('#brief-error').textContent='Sign in to create a shareable brief from your saved board. You can preview and print this example.';return}$('#brief-error').textContent='';$('#create-brief').disabled=true;try{const payload=briefPayload(),title=$('#brief-title').value.trim();if(!title)throw Error('Give your brief a title.');const d=check(await db.from('wedding_studio_briefs').insert({user_id:user.id,title,payload}).select('token').single());const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('brief',d.token);$('#brief-link').value=url.href;$('#open-brief').href=url.href;$('#brief-result').hidden=false;toast('Your read-only brief is ready')}catch(e){$('#brief-error').textContent=e.message;$('#create-brief').disabled=false}};
$('#copy-brief').onclick=async()=>{try{await navigator.clipboard.writeText($('#brief-link').value);toast('Vendor link copied')}catch{$('#brief-link').select();toast('Select and copy the highlighted link')}};
function briefHTML(b){return `<section class="brief-page"><div class="brandline"><span>WEDDING STUDIO · TINY SITE STUDIOS</span><button class="button no-print" onclick="window.print()">Print / save PDF</button></div><header><p class="eyebrow">VENDOR BRIEF</p><h1>${esc(b.title)}</h1><p class="brief-meta">${esc(b.wedding)}${b.date?' · '+esc(b.date):''}<br>Snapshot created ${new Date(b.created_at||Date.now()).toLocaleDateString()}${b.expires_at?' · Link expires '+new Date(b.expires_at).toLocaleDateString():''}</p></header>${b.instructions?`<p class="instructions">${esc(b.instructions)}</p>`:''}<div class="board">${b.items.map(i=>cardHTML(i,true)).join('')}</div><footer>Prepared with Wedding Studio by Tiny Site Studios. This brief contains selected items only. Attachment links refresh when you reload the shared brief.</footer></section>`}
$('#print-brief').onclick=async()=>{let b;try{b=briefPayload();b.title=$('#brief-title').value.trim()||'Our wedding vision'}catch(e){$('#brief-error').textContent=e.message;return}const w=window.open('','_blank');if(!w){$('#brief-error').textContent='Allow pop-ups to open the printable brief.';return}w.opener=null;w.document.write('<p>Preparing your brief…</p>');b.items=await fileURLs(b.items);w.document.open();w.document.write(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(b.title)}</title><link rel="stylesheet" href="${new URL('studio.css',location.href).href}"></head><body>${briefHTML(b)}</body></html>`);w.document.close()};
$('#manage-briefs').onclick=async()=>{if(!guard())return;$('#briefs-modal').showModal();if(demo){$('#briefs-list').innerHTML='<p class="intro">Your shared briefs will appear here once you sign in and create one.</p>';return}$('#briefs-list').textContent='Loading…';try{const list=check(await db.from('wedding_studio_briefs').select('id,title,token,expires_at').eq('user_id',user.id).order('created_at',{ascending:false}));$('#briefs-list').innerHTML=list.length?list.map(b=>`<div class="shared-row"><strong>${esc(b.title)}</strong><p>Expires ${new Date(b.expires_at).toLocaleDateString()}</p><a target="_blank" rel="noopener" href="?brief=${b.token}">View brief</a><button class="quiet" data-revoke="${b.id}">Revoke link</button></div>`).join(''):'<p class="intro">No shared briefs yet. Choose “Make a vendor brief” to create your first one.</p>';$$('[data-revoke]').forEach(b=>b.onclick=async()=>{if(!await confirmAction('Revoke this brief?','The shared link will stop working. Attachments already opened may remain available for up to one hour. Downloaded copies cannot be recalled.'))return;try{check(await db.from('wedding_studio_briefs').delete().eq('id',b.dataset.revoke).eq('user_id',user.id));b.closest('.shared-row').remove();toast('Brief link revoked')}catch(e){toast(e.message)}})}catch(e){$('#briefs-list').textContent='Could not load briefs. Close this window and try again.'}};
$('#auth-toggle').onclick=()=>{authMode=authMode==='signup'?'login':'signup';setAuthMode()};
$('#auth-form').onsubmit=async e=>{e.preventDefault();if(!db){$('#auth-error').textContent='The connection could not start. Please reload and try again.';return}$('#auth-submit').disabled=true;$('#auth-error').textContent='';const email=$('#auth-email').value.trim(),password=$('#auth-password').value;try{if(authMode==='reset'){check(await db.auth.updateUser({password}));$('#auth').close();toast('Password updated');await loadCloud();return}const r=authMode==='signup'?await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}}):await db.auth.signInWithPassword({email,password});const data=check(r);if(!data.session){$('#auth-next').hidden=false;$('#auth-submit').hidden=true;$('#auth-message').textContent='If this is a new email address, check your inbox and spam folder for a confirmation link. Already have a Tiny Site Studios account? No new confirmation is needed—sign in with your existing password, or choose Forgot password. For privacy, this screen cannot confirm whether an address is registered.';return}user=data.user;$('#auth').close();category='All inspiration';await loadCloud()}catch(err){$('#auth-error').textContent=err.message||'Unable to sign in. Please try again.'}finally{$('#auth-submit').disabled=false}};
$('#auth-go-login').onclick=()=>{authMode='login';setAuthMode();$('#auth-password').value='';$('#auth-password').focus()};
$('#auth-resend').onclick=async()=>{const email=$('#auth-email').value.trim();if(!email||!$('#auth-email').checkValidity()){$('#auth-error').textContent='Enter a valid email address first.';return}$('#auth-resend').disabled=true;try{check(await db.auth.resend({type:'signup',email,options:{emailRedirectTo:location.origin+location.pathname}}));$('#auth-message').textContent='If this address has an unconfirmed account, a new confirmation link has been requested. Check your inbox and spam folder. Already confirmed? Choose Go to sign in.';setTimeout(()=>$('#auth-resend').disabled=false,60000)}catch(e){$('#auth-error').textContent=e.message||'Could not request another confirmation. Please try again.';$('#auth-resend').disabled=false}};
$('#forgot').onclick=async()=>{const email=$('#auth-email').value.trim();if(!email||!$('#auth-email').checkValidity()){$('#auth-error').textContent='Enter your email address first.';return}try{check(await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname}));$('#auth-error').textContent='If an account exists, you’ll receive a password reset email.'}catch(e){$('#auth-error').textContent=e.message}};
$('#account').onclick=async()=>{if(!user){showAuth();return}try{check(await db.auth.signOut());user=null;demo=false;items=[];board={title:'Our wedding',wedding_date:''};render();toast('Signed out')}catch(e){toast(e.message)}};
$('#add').onclick=()=>openEditor();$$('[data-kind]').forEach(b=>b.onclick=()=>setKind(b.dataset.kind));$('#item-category').innerHTML=sections.map(s=>`<option>${esc(s)}</option>`).join('');$('#cards-view').onclick=()=>{view='cards';render()};$('#canvas-view').onclick=()=>{view='canvas';render()};$('#search').oninput=render;$('#status-filter').onchange=render;
const wrap=$('#board-wrap');
function captureAllowed(e){return !loading&&!$('#app').hidden&&!e.target.closest?.('input,textarea,select,[contenteditable="true"]')&&!$$('dialog[open]').length}
let internalDrag=false,dragDepth=0;
document.addEventListener('dragstart',e=>{internalDrag=!!e.target.closest?.('#board')});
document.addEventListener('dragend',()=>{internalDrag=false;dragDepth=0;document.body.classList.remove('drop-active')});
document.addEventListener('dragover',e=>{if(captureAllowed(e)&&!internalDrag){e.preventDefault();e.dataTransfer.dropEffect='copy'}});
document.addEventListener('dragenter',e=>{if(captureAllowed(e)&&!internalDrag){e.preventDefault();dragDepth++;document.body.classList.add('drop-active')}});
document.addEventListener('dragleave',()=>{if(--dragDepth<=0){dragDepth=0;document.body.classList.remove('drop-active')}});
document.addEventListener('drop',e=>{dragDepth=0;document.body.classList.remove('drop-active');if(!captureAllowed(e)||internalDrag)return;e.preventDefault();const rect=$('#board').getBoundingClientRect();const capture=StudioIntake.read(e.dataTransfer);if(view==='canvas')capture.position={x:Math.max(0,Math.round(e.clientX-rect.left)),y:Math.max(0,Math.round(e.clientY-rect.top))};void receiveCapture(capture)});
document.addEventListener('paste',e=>{if(!captureAllowed(e))return;const capture=StudioIntake.read(e.clipboardData);if(capture.entries.length){e.preventDefault();void receiveCapture(capture)}});
$('#capture-help').onclick=()=>$('#capture-modal').showModal();
async function receiveCapture(capture){if(!capture.entries.length)return;if(!user&&!demo){pendingCapture=capture;showAuth();toast('Sign in to save these ideas. They’re held here while you sign in.');return}await importCapture(capture)}
function importMessage(text,failed=[]){const el=$('#import-status');el.hidden=false;el.textContent=text;if(failed.length){const retry=document.createElement('button');retry.className='quiet';retry.textContent='Retry failed items';retry.onclick=()=>importCapture({entries:failed});el.append(retry)}const close=document.createElement('button');close.className='quiet';close.textContent='Dismiss';close.onclick=()=>el.hidden=true;el.append(close)}
async function importCapture(capture){if(importing){toast('Please wait for this batch to finish, then paste or drop again.');return}if(!guard())return;importing=true;const owner=user?.id,isDemo=demo,targetCategory=category==='All inspiration'?'Sort later':category;const entries=capture.entries.slice(0,30),failed=[],newLinks=[];let added=0;busy(true);$('#search').value='';$('#status-filter').value='';
try{for(let n=0;n<entries.length;n++){if(user?.id!==owner||demo!==isDemo)break;const entry=entries[n];importMessage(`Adding ${n+1} of ${entries.length}…`);let uploaded=null;try{const pos=capture.position;const i={id:crypto.randomUUID(),title:(entry.title||'A new idea').slice(0,200),kind:entry.kind,category:targetCategory,status:'Idea',notes:entry.notes||'',url:entry.url||'',colors:[],preview:entry.image?{image:entry.image}:{},x:Math.min(10000,pos?pos.x+n*24:25+items.length%3*290),y:Math.min(10000,pos?pos.y+n*24:25+Math.floor(items.length/3)*460)};
if(entry.file){const f=entry.file;if(f.size>15*1024*1024)throw Error('File exceeds 15 MB');i.kind=/^image\/(jpeg|png|webp|gif|avif)$/.test(f.type)?'image':'file';i.file_name=f.name;i.file_type=f.type||'application/octet-stream';if(demo)i.file_url=URL.createObjectURL(f);else{uploaded=user.id+'/'+crypto.randomUUID()+'/'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');check(await db.storage.from('wedding-studio').upload(uploaded,f,{contentType:i.file_type,upsert:false}));i.file_path=uploaded}}
if(user?.id!==owner||demo!==isDemo)throw Error('Session changed');await persistItem(i);added++;if(i.kind==='link')newLinks.push(i.id);
}catch(e){if(uploaded&&user?.id===owner)await db.storage.from('wedding-studio').remove([uploaded]);failed.push(entry)}}
importMessage(`${added} idea${added!==1?'s':''} added${demo?' to the temporary example':''}.${failed.length?' '+failed.length+' could not save. Check the connection and 15 MB file limit.':''}${capture.entries.length>30?' Only the first 30 were added; drop the rest as another batch.':''}`,failed);
}finally{importing=false;busy(false)}
for(const id of newLinks){if(user?.id!==owner||demo!==isDemo)break;await enrichItem(id,true)}}
const previewInFlight=new Set();
async function fetchLinkPreview(url){if(demo&&url!=='https://tinysitestudios.com/weddings/demos/garden/')throw Error('Automatic previews are available on your saved board. You can upload a cover in this example.');const session=check(await db.auth.getSession()).session;if(!session&&!demo)throw Error('Sign in to refresh the preview.');const r=await fetch(URL_BASE+'/functions/v1/wedding-studio-link-preview',{method:'POST',headers:{'Content-Type':'application/json','apikey':API_KEY,...(session?{'Authorization':'Bearer '+session.access_token}:{})},body:JSON.stringify({url}),signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw Error(data.error||'Preview unavailable. Add a cover image instead.');return data}
async function enrichItem(id,replaceTitle=false){const original=items.find(i=>i.id===id);if(!original?.url||demo||!user||previewInFlight.has(id))return;const owner=user.id;previewInFlight.add(id);try{let preview;try{preview=await fetchLinkPreview(original.url)}catch{preview={checked_at:new Date().toISOString()}}const latest=items.find(i=>i.id===id);if(user?.id!==owner||!latest||latest.url!==original.url)return;preview={...latest.preview,...preview,image:preview.image||latest.preview?.image||''};await persistItem({...latest,preview,title:replaceTitle&&preview.title&&latest.title===original.title?preview.title:latest.title})}catch{/* Saving the original link is independent of preview availability. */}finally{previewInFlight.delete(id)}}
async function enrichExisting(){const owner=user?.id;for(const i of items.filter(i=>i.kind==='link'&&!i.preview?.checked_at).slice(0,20)){if(user?.id!==owner||demo)break;await enrichItem(i.id,false)}}
$('#refresh-preview').onclick=async()=>{const url=safeUrl($('#item-url').value);if(!url){$('#preview-feedback').textContent='Enter a complete website link first.';return}$('#refresh-preview').disabled=true;$('#preview-feedback').textContent='Looking for a preview…';try{const found=await fetchLinkPreview(url);draftPreview={...found,image:found.image||draftPreview.image||''};if(!$('#item-title').value&&draftPreview.title)$('#item-title').value=draftPreview.title;$('#preview-feedback').textContent=draftPreview.image?'Preview found. Save this item to apply it.':'Page details found, but no cover. Upload an image below.'}catch(e){$('#preview-feedback').textContent=e.message}finally{$('#refresh-preview').disabled=false}};
$('#item-url').addEventListener('input',()=>{draftPreview={};$('#preview-feedback').textContent=''});
$('#remove-cover').onclick=()=>{if(editing)editing={...editing,file_path:null,file_url:null,file_name:null,file_type:null};$('#item-file').value='';$('#attached').textContent='Cover removed. Save to apply.';$('#remove-cover').hidden=true};
async function loadPublicBrief(token){$('#app').hidden=true;const host=document.createElement('div');host.id='public-brief';host.innerHTML='<p class="loading">Opening your vendor brief…</p>';document.body.prepend(host);try{const r=await fetch(URL_BASE+'/functions/v1/wedding-studio-brief?token='+encodeURIComponent(token));const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to open brief');host.innerHTML=briefHTML(data);document.title=data.title+' | Wedding Studio'}catch(e){host.innerHTML=`<div class="empty"><h2>This brief isn’t available.</h2><p>${esc(e.message)}</p><p>Ask the couple for a fresh link.</p></div>`}}
async function init(){const token=new URLSearchParams(location.search).get('brief');if(token){await loadPublicBrief(token);return}render();if(!window.supabase){toast('Could not connect. Reload to enable sign-in.');return}db=window.supabase.createClient(URL_BASE,API_KEY,{auth:{storageKey:'wedding-studio-auth'}});db.auth.onAuthStateChange((event,session)=>{user=session?.user||null;if(event==='PASSWORD_RECOVERY'){authMode='reset';setAuthMode();$('#auth').showModal()}if(event==='SIGNED_OUT'&&!initializing){items=[];demo=false;board={title:'Our wedding',wedding_date:''};render()}});try{const data=check(await db.auth.getSession());user=data.session?.user||null;initializing=false;if(user)await loadCloud()}catch(e){initializing=false;toast('Could not restore your session. Please sign in again.')}if(document.modelContext?.registerTool){const abort=new AbortController();try{await document.modelContext.registerTool({name:'read_wedding_board',description:'Read the current visible wedding board and decision labels.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments are accepted.');return {title:board.title,temporary:demo,items:filtered().map(({id,title,category,status,notes,url})=>({id,title,category,status,notes,url}))}}} ,{signal:abort.signal});window.addEventListener('pagehide',()=>abort.abort(),{once:true})}catch{}}}
init();
