'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE='petty-club-awards-v1';
const categories=['Domestic Affairs','Administrative Bravery','Social Courage','Personal Maintenance','Miscellaneous Excellence'];
const honors={
 'Domestic Affairs':[['The Order of the Empty Chair','For restoring a piece of furniture to its original purpose.'],['Excellence in Refrigerator Stewardship','For valiantly tending to the cold kingdom.'],['The Golden Domestic Distinction','For making your corner of the world a little more livable.']],
 'Administrative Bravery':[['Medal of Administrative Bravery','For facing the paperwork with distinguished courage.'],['Distinguished Inbox Service','For answering the call. Or, more likely, the email.'],['The Golden Unsubscribe','For bringing a recurring obligation to its glorious conclusion.']],
 'Social Courage':[['The Brave Little Ask','For finding the words and letting them out into the world.'],['The Distinguished Hello','For an outstanding contribution to human connection.'],['The Order of Showing Up','For your courageous appearance in the outside world.']],
 'Personal Maintenance':[['Outstanding Achievement in Showing Up','For doing what you could with the day you had.'],['The Medal of Being a Person','For tending to the person doing all the things: you.'],['The Well-Deserved Pause','For recognizing that rest is a perfectly respectable endeavor.']],
 'Miscellaneous Excellence':[['The Exceptionally Small Triumph','For a contribution of modest size and immense distinction.'],['The Order of Getting Around to It','For bringing a long-standing intention into existence.'],['The Golden Little Thing','For proof that the little things are, in fact, things.']]
};
let awards=[],current=null,platform='Facebook',moreLinkedIn=false,toastTimer,storageAvailable=true;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){const target=document.querySelector('dialog[open]')||document.body;target.append($('#toast'));$('#toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',4500)}
try{const value=JSON.parse(localStorage.getItem(STORAGE)||'[]');if(Array.isArray(value))awards=value.filter(a=>a&&typeof a.id==='string'&&typeof a.victory==='string'&&typeof a.title==='string'&&typeof a.citation==='string'&&typeof a.name==='string'&&categories.includes(a.category)&&Number.isFinite(a.created)).slice(0,1000)}catch{storageAvailable=false;toast('Browser storage is unavailable. Awards will last for this visit only.')}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(awards));return true}catch{storageAvailable=false;toast('Could not save in this browser. Download your card to keep it.');return false}}
const badgeIcons={
 chair:'<path d="M65 77V54Q65 49 70 49H109Q114 49 114 54V77M61 79H119V93H61ZM68 94V109M112 94V109"/><path d="M73 56 85 51 97 56 104 71 92 76 74 68Z" fill="#d5806d" stroke="none"/><path d="m67 78 15-7 21 8-4 7H74Z" fill="#76506b" stroke="none"/>',
 fridge:'<rect x="68" y="46" width="45" height="64" rx="5"/><path d="M69 70H112M77 56V63M77 81V93"/><path d="m91 83 5 9 10 1-7 7 2 9-10-5-8 5 2-9-7-7 10-1Z" fill="#bc9148" stroke="none"/>',
 house:'<path d="m57 75 33-28 33 28M65 70V108H115V70M83 108V85H98V108"/><path d="m81 69 7 5 12-14"/>',
 calendar:'<rect x="60" y="53" width="60" height="55" rx="6"/><path d="M60 69H120M74 47V60M106 47V60m-31 27 10 10 19-20"/>',
 envelope:'<rect x="55" y="56" width="70" height="46" rx="5"/><path d="m57 58 33 25 33-25M56 100l22-22M124 100l-22-22"/>',
 unsubscribe:'<path d="M65 59a29 29 0 0 1 47-4l6 7M118 49V62H105M115 97a29 29 0 0 1-47 4l-6-7M62 107V94H75M75 78H106"/>',
 help:'<path d="M64 71Q64 47 90 47Q116 47 116 71Q116 95 90 95H76L64 106Z"/><path d="M90 59V82M78 70H102"/>',
 hello:'<path d="M74 90V60Q74 53 79 55V75M84 73V49Q84 42 90 46V73M96 73V49Q96 43 102 47V75M108 77V60Q108 53 114 57V86Q114 109 91 109Q77 109 69 98L59 82Q55 72 65 77L74 84"/>',
 door:'<path d="M64 108V47H117V108M74 106V55l30-7V112ZM94 80h1M115 87h14m-5-5 5 5-5 5"/>',
 sunrise:'<path d="M55 100H125M66 91a24 24 0 0 1 48 0M90 45V56M56 60l8 9M124 60l-8 9M51 86H60M120 86H129"/>',
 heart:'<path d="M90 105 61 80Q48 56 70 50Q84 46 90 62Q98 44 114 51Q132 61 118 81Z"/>',
 moon:'<path d="M103 45a32 32 0 1 0 27 49 30 30 0 0 1-27-49Z"/><path d="m120 50 3 8 8 3-8 3-3 8-3-8-8-3 8-3Z" fill="#bc9148" stroke="none"/>',
 sprout:'<path d="M90 110V78M90 87Q59 91 61 61Q86 61 90 87ZM90 78Q89 48 117 48Q120 74 90 78Z"/>',
 clock:'<circle cx="90" cy="79" r="31"/><path d="M90 58V80l17 11M84 41H97"/>',
 star:'<path d="m90 44 10 22 24 3-18 17 4 24-20-12-21 12 5-24-18-17 24-3Z"/>'
};
function badgeKind(title='',category='Miscellaneous Excellence'){
 const titles=Object.values(honors).flat().map(h=>h[0]),kinds=['chair','fridge','house','calendar','envelope','unsubscribe','help','hello','door','sunrise','heart','moon','sprout','clock','star'];
 const index=titles.indexOf(title);return index>=0?kinds[index]:['house','calendar','hello','heart','star'][Math.max(0,categories.indexOf(category))];
}
function medal(category='Domestic Affairs',title='The Order of the Empty Chair'){
 const index=Math.max(0,categories.indexOf(category)), color=['#e24283','#00877e','#ee6539','#548024','#4345e7'][index];
 return `<svg class="medal" viewBox="0 0 180 210" aria-hidden="true"><path d="M49 104 39 201 70 181 91 202 94 108Z" fill="${color}"/><path d="M92 107 91 202 114 181 144 200 131 105Z" fill="${color}"/><path d="M53 145 51 179 68 168 77 179 79 143M105 144 108 180 118 169 132 180 127 144" fill="none" stroke="#fff8" stroke-width="2"/><path d="M90 6 104 14 121 13 131 27 148 33 150 50 163 62 158 78 163 94 150 106 148 123 131 129 121 143 104 142 90 150 76 142 59 143 49 129 32 123 30 106 17 94 22 78 17 62 30 50 32 33 49 27 59 13 76 14Z" fill="#ffc83e"/><circle cx="90" cy="78" r="59" fill="#ffe064" stroke="#b8790b" stroke-width="2"/><circle cx="90" cy="78" r="51" fill="#fff7ce" stroke="#ecab22"/><g fill="none" stroke="${color}" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round">${badgeIcons[badgeKind(title,category)]}</g><path d="M50 77C50 99 63 113 78 119M130 77C130 99 117 113 102 119" stroke="#b38d49" fill="none" stroke-width="2"/><text x="90" y="37" text-anchor="middle" font-family="Georgia" font-size="7" fill="#785932" letter-spacing="2">P. A. C.</text></svg>`
}
$('#hero-medal').innerHTML=medal();
function chooseHonor(victory,category){const text=victory.toLowerCase();if(/laundry|clothes|fold/.test(text))return honors['Domestic Affairs'][0];if(/leftover|fridge|refrigerator/.test(text))return honors['Domestic Affairs'][1];if(/email|inbox/.test(text))return honors['Administrative Bravery'][1];if(/cancel|unsubscribe|subscription/.test(text))return honors['Administrative Bravery'][2];if(/\b(help|asked|ask)\b/.test(text))return honors['Social Courage'][0];if(/hard day|one thing/.test(text))return honors['Personal Maintenance'][0];if(/\b(rest|break|pause)\b/.test(text))return honors['Personal Maintenance'][2];if(/\bfinally\b|putting off/.test(text))return honors['Miscellaneous Excellence'][1];if(/appointment|paperwork/.test(text))return honors['Administrative Bravery'][0];return honors[category][Math.floor(Math.random()*honors[category].length)]}
function awardTile(a){return `<button class="award-tile" data-award="${escapeHTML(a.id)}" aria-label="View ${escapeHTML(a.title)}">${medal(a.category,a.title)}<h3>${escapeHTML(a.title)}</h3><p>“${escapeHTML(a.victory)}”</p><small>${escapeHTML(a.category)} · ${new Date(a.created).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</small></button>`}
function empty(){return '<div class="empty"><div class="empty-symbol" aria-hidden="true">✧</div><h3>Your first questionable distinction awaits.</h3><p>Did something ordinary? That’s precisely our specialty.</p><button class="text-button" data-declare>Claim your first honor ↗</button></div>'}
function render(){ $('#count').textContent=awards.length;$('#recent-awards').innerHTML=awards.length?`<div class="award-grid" style="margin:0">${awards.slice(0,3).map(awardTile).join('')}</div>`:empty();const filtered=awards.filter(a=>!$('#filter').value||a.category===$('#filter').value);$('#shelf-awards').innerHTML=filtered.length?filtered.map(awardTile).join(''):awards.length?'<div class="empty"><h3>No honors in this department yet.</h3><p>Your committee is standing by.</p></div>':empty();$('.storage-note').textContent=storageAvailable?'Your trophy shelf is saved in this browser on this device. Clearing browser data removes your awards.':'Browser storage is unavailable. Awards last for this visit only; download cards to keep them.'}
function route(focus=false){const page=['clubhouse','shelf','rules'].includes(location.hash.slice(1))?location.hash.slice(1):'clubhouse';$$('.page').forEach(e=>e.hidden=e.id!==page);$$('[data-page]').forEach(e=>{if(e.dataset.page===page)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current')});if(focus){$('#main').focus({preventScroll:true});window.scrollTo(0,0)}}
window.addEventListener('hashchange',()=>route(true));route();render();
function declare(victory='',category='Miscellaneous Excellence'){$('#victory-form').reset();$('#victory').value=victory;$('#category').value=category;$('#declare-dialog').showModal();$('#victory').focus()}
document.addEventListener('click',e=>{const d=e.target.closest('[data-declare]'),s=e.target.closest('[data-suggestion]'),a=e.target.closest('[data-award]');if(d)declare();if(s)declare(s.dataset.suggestion,s.dataset.category);if(a)showAward(awards.find(x=>x.id===a.dataset.award));if(e.target.closest('.close'))e.target.closest('dialog').close()});
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}));
$('#filter').addEventListener('change',render);
const tinyWins=[{idea:'Put away the laundry mountain. Reclaim the chair.',victory:'Put the laundry away',category:'Domestic Affairs'},{idea:'Reply to that email. You know the one.',victory:'Answered that overdue email',category:'Administrative Bravery'},{idea:'Drink a glass of water. Very distinguished.',victory:'Drank a glass of water',category:'Personal Maintenance'},{idea:'Clear exactly one corner of your desk.',victory:'Cleared one corner of my desk',category:'Domestic Affairs'},{idea:'Ask for help. That counts as bravery.',victory:'Asked for help',category:'Social Courage'},{idea:'Take a break without earning it first.',victory:'Took a well-deserved break',category:'Personal Maintenance'},{idea:'Finally make the appointment.',victory:'Made the appointment',category:'Administrative Bravery'}];
let suggestionIndex=6,spinTimer;
$('#suggested').textContent=tinyWins[suggestionIndex].idea;
function spinTinyWin(){clearInterval(spinTimer);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;$('#another').disabled=true;let ticks=0;const finish=()=>{$('#another').disabled=false;$('#suggested').textContent=tinyWins[suggestionIndex].idea;$('#suggested').classList.remove('rolling');$('#roulette-status').textContent='Your tiny win idea: '+tinyWins[suggestionIndex].idea};if(reduced){suggestionIndex=(suggestionIndex+1+Math.floor(Math.random()*(tinyWins.length-1)))%tinyWins.length;finish();return}$('#suggested').classList.add('rolling');$('#suggested').setAttribute('aria-live','off');spinTimer=setInterval(()=>{suggestionIndex=(suggestionIndex+1)%tinyWins.length;$('#suggested').textContent=tinyWins[suggestionIndex].idea;if(++ticks>=10+Math.floor(Math.random()*4)){clearInterval(spinTimer);finish()}},85)}
$('#another').addEventListener('click',spinTinyWin);
$('#did-suggested').addEventListener('click',()=>{const win=tinyWins[suggestionIndex];declare(win.victory,win.category)});
function confetti(level){if(level==='polite'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const container=$('#confetti');(document.querySelector('dialog[open]')||document.body).append(container);container.replaceChildren();for(let i=0;i<(level==='academy'?85:28);i++){const bit=document.createElement('i');bit.className='confetti-bit';bit.style.left=Math.random()*100+'%';bit.style.background=['#ffca3a','#ff5c91','#4345e7','#19c9a9','#ff793f'][i%4];bit.style.animationDelay=Math.random()*.6+'s';container.append(bit)}setTimeout(()=>container.replaceChildren(),3600)}
$('#victory-form').addEventListener('submit',e=>{e.preventDefault();const victory=$('#victory').value.trim();if(!victory){$('#victory').setCustomValidity('Tell the committee what you did.');$('#victory').reportValidity();return}const category=$('#category').value,[title,citation]=chooseHonor(victory,category);const a={id:crypto.randomUUID(),victory,category,title,citation,name:$('#nickname').value.trim(),created:Date.now()};awards.unshift(a);const saved=persist();render();const level=new FormData(e.target).get('applause');$('#declare-dialog').close();showAward(a);confetti(level);if(saved)toast('Your contribution has entered the historical record.')});$('#victory').addEventListener('input',()=>$('#victory').setCustomValidity(''));
function showAward(a){if(!a)return;current=a;$('#award-preview').innerHTML=`${medal(a.category,a.title)}<div class="eyebrow">${escapeHTML(a.category)}</div><h2 id="award-title">${escapeHTML(a.title)}</h2><p class="citation">${escapeHTML(a.citation)}</p><div class="victory">“${escapeHTML(a.victory)}”</div>${a.name?`<p class="recipient">Presented with excessive admiration to ${escapeHTML(a.name)}</p>`:''}<div class="eyebrow">LOW STAKES. HIGH HONORS.</div>`;$('#speech-content').hidden=!(typeof a.speech==='string'&&a.speech);$('#speech').value=typeof a.speech==='string'?a.speech:'';$('#speech-generate').hidden=!$('#speech-content').hidden;$('#award-dialog').showModal()}
$('#celebrate-again').addEventListener('click',()=>{confetti('academy');toast(matchMedia('(prefers-reduced-motion: reduce)').matches?'A standing ovation for you! 🎉':'The committee has approved additional fanfare. 🎉')});
$('#accept-award').addEventListener('click',()=>{$('#award-dialog').close();toast('Honor accepted. A bow is entirely appropriate.')});
const speechThanks={chair:'the chair for its patience and the closet for believing in me',fridge:'the refrigerator for its loyal service and the leftovers for their sacrifice',house:'my home for continuing to tolerate my creative approach to tidiness',calendar:'my calendar, my courage, and everyone who put me on hold',envelope:'the inbox for its patience and the send button for making this possible',unsubscribe:'the cancel button and the surprisingly persistent retention department',help:'the people who reminded me I do not have to do everything alone',hello:'the people who made reaching out feel worth it',door:'my shoes for getting me out the door and my couch for understanding',sunrise:'myself for showing up with the energy I had today',heart:'the small acts of care that helped me get here',moon:'the couch, the quiet, and everyone who respects a well-earned pause',sprout:'the little things that quietly add up',clock:'the concept of eventually and everyone who waited patiently',star:'the committee for its extraordinarily generous standards'};
let speechRound=0;
function writeSpeech(){if(!current)return;const thanks=speechThanks[badgeKind(current.title,current.category)],v=current.victory;const versions=[`I graciously accept ${current.title}. My distinguished contribution: ${v}. I’d like to thank ${thanks}. Please hold your applause until I have taken an unnecessarily long bow.`,`When I set out to do this—${v}—I never imagined I would be standing before this imaginary academy. Thank you to ${thanks}. This honor belongs on a shelf that I will almost certainly dust eventually.`,`The committee called it “${current.title}.” I called it “${v}.” Either way, I am accepting this moment with pride. Thank you to ${thanks}. I dedicate this honor to everyone doing the little things.`];current.speech=versions[speechRound++%versions.length];$('#speech').value=current.speech;$('#speech-content').hidden=false;$('#speech-generate').hidden=true;persist();}
$('#speech-generate').addEventListener('click',writeSpeech);
$('#speech-again').addEventListener('click',writeSpeech);
$('#speech').addEventListener('input',()=>{if(current){current.speech=$('#speech').value;persist()}});
$('#speech-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#speech').value);toast('Speech copied. The microphone is yours.')}catch{$('#speech').focus();$('#speech').select();toast('Select and copy your highlighted speech.')}});
$('#delete-award').addEventListener('click',()=>{if(!current||!confirm('Remove this award from your trophy shelf?'))return;awards=awards.filter(a=>a.id!==current.id);persist();render();$('#award-dialog').close();toast('Award removed from your record.')});
function caption(){const victory=$('#share-victory').value.trim()||current.victory;const title=current.title;if(platform==='LinkedIn')return moreLinkedIn?`I’m humbled and thrilled to announce that I’ve been recognized with ${title}.\n\nThe achievement: ${victory}.\n\nThis milestone reflects a commitment to showing up, moving things forward, and occasionally putting them away. Thank you to everyone who believed in this journey.\n\n#SmallWins #PersonalGrowth #PettyAccomplishmentsClub`:`Thrilled to announce I’ve received ${title} for the following outstanding contribution: ${victory}.\n\nLow stakes. High honors. 🏅\n#PettyAccomplishmentsClub`;if(platform==='Instagram')return `${victory}.\n\nSmall victory. Unreasonable amount of prestige. 🏆\n${title}\n\n#PettyAccomplishmentsClub #SmallWins`;return `Proud to announce: ${victory}.\n\nThe committee has awarded me ${title}. Please respect my privacy during this time of extraordinary achievement. 🏅\n\nPetty Accomplishments Club · Low stakes. High honors.`}
function selectPlatform(value){platform=value;moreLinkedIn=false;$$('[data-platform]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.platform===platform)));$('#linkedin-more').hidden=platform!=='LinkedIn';$('#linkedin-more').textContent='Make it more LinkedIn ✨';$('#caption').value=caption()}
$('#share-award').addEventListener('click',()=>{$('#award-dialog').close();$('#share-name').value=current.name;$('#share-victory').value=current.victory;$('#layout').value='square';$('input[name="card-style"][value="official"]').checked=true;selectPlatform('Facebook');drawCard();$('#share-dialog').showModal()});
$$('[data-platform]').forEach(b=>b.addEventListener('click',()=>selectPlatform(b.dataset.platform)));
$('#caption-refresh').addEventListener('click',()=>{$('#caption').value=caption();toast('Caption refreshed for your accomplishment.')});
$('#linkedin-more').addEventListener('click',()=>{moreLinkedIn=!moreLinkedIn;$('#caption').value=caption();$('#linkedin-more').textContent=moreLinkedIn?'A little less LinkedIn, please':'Make it more LinkedIn ✨'});
['#layout','#share-name','#share-victory'].forEach(id=>$(id).addEventListener('input',drawCard));$$('input[name="card-style"]').forEach(input=>input.addEventListener('change',drawCard));
function linesFor(ctx,text,width){const words=String(text).split(/\s+/),lines=[];let line='';for(const word of words){if(ctx.measureText(word).width>width){if(line){lines.push(line);line=''}let part='';for(const char of word){if(ctx.measureText(part+char).width>width){lines.push(part);part=char}else part+=char}line=part;continue}const next=line?line+' '+word:word;if(ctx.measureText(next).width>width){if(line)lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines}
function fitText(ctx,text,width,size,maxLines,family){let lines;do{ctx.font=size+'px '+family;lines=linesFor(ctx,text,width);if(lines.length<=maxLines||size<=18)break;size-=2}while(true);return {lines,size}}
function drawCard(){
 if(!current)return;
 const canvas=$('#social-canvas'),story=$('#layout').value==='story',style=$('input[name="card-style"]:checked').value;
 canvas.width=1080;canvas.height=story?1920:1080;
 const c=canvas.getContext('2d'),h=canvas.height,offset=(h-1080)/2;
 const themes={official:{bg:'#f8f4eb',ink:'#46283f',accent:'#bc9148',muted:'#746772',heading:'BY ORDER OF THE COMMITTEE',footer:'LOW STAKES. HIGH HONORS.'},brag:{bg:'#4345e7',ink:'#ffffff',accent:'#ffe064',muted:'#ececff',heading:'BREAKING (VERY SMALL) NEWS',footer:'SMALL VICTORY. UNREASONABLE PRESTIGE.'},linkedin:{bg:'#f1fffb',ink:'#15364c',accent:'#00877e',muted:'#516677',heading:'A SIGNIFICANT PERSONAL MILESTONE',footer:'HUMBLED. THRILLED. EXCESSIVELY DECORATED.'}};
 const t=themes[style],snapshot={title:current.title,category:current.category,name:$('#share-name').value.trim(),victory:$('#share-victory').value.trim()||current.victory};
 c.fillStyle=t.bg;c.fillRect(0,0,1080,h);c.textAlign='center';
 if(style==='official'){c.strokeStyle=t.accent;c.lineWidth=2;c.strokeRect(42,42,996,h-84);c.strokeRect(56,56,968,h-112)}
 if(style==='brag'){c.strokeStyle=t.accent;c.lineWidth=3;c.strokeRect(38,38,1004,h-76);c.fillStyle=t.accent;c.font='42px Georgia';c.fillText('✦',115,138+offset);c.fillText('✦',965,138+offset)}
 if(style==='linkedin'){c.fillStyle=t.accent;c.fillRect(0,0,1080,22);c.fillStyle='#e9f3f8';c.fillRect(70,185+offset,940,610);c.fillStyle=t.accent;c.font='bold 20px sans-serif';c.fillText('PERSONAL GROWTH DEPARTMENT',540,90+offset)}
 c.fillStyle=t.ink;c.font='bold 22px '+(style==='official'?'Georgia':'sans-serif');c.fillText('PETTY ACCOMPLISHMENTS CLUB',540,120+offset);
 c.font='19px sans-serif';c.fillStyle=t.muted;c.fillText(t.heading,540,164+offset);
 const img=new Image(),renderVersion=++drawCard.version;
 $('#download').disabled=true;$('#native-share').disabled=true;
 drawCard.ready=new Promise(resolve=>{
 img.onload=()=>{if(renderVersion!==drawCard.version){resolve();return}
 c.drawImage(img,440,188+offset,200,233);
 c.fillStyle=t.ink;const title=fitText(c,snapshot.title,850,style==='brag'?60:54,2,style==='official'?'Georgia':'sans-serif');
 const titleTop=478+offset;title.lines.forEach((line,i)=>c.fillText(line,540,titleTop+i*(title.size+8)));
 let y=titleTop+(title.lines.length-1)*(title.size+8)+62;
 const victory=fitText(c,'“'+snapshot.victory+'”',810,style==='brag'?36:30,4,'sans-serif');c.fillStyle=t.muted;victory.lines.forEach((line,i)=>c.fillText(line,540,y+i*(victory.size+10)));
 y+=(victory.lines.length-1)*(victory.size+10)+57;
 if(snapshot.name){const name=fitText(c,'Presented to '+snapshot.name,810,26,2,'Georgia');c.fillStyle=t.ink;name.lines.forEach((line,i)=>c.fillText(line,540,y+i*(name.size+6)))}
 c.strokeStyle=t.accent;c.lineWidth=1;c.beginPath();c.moveTo(170,h-165);c.lineTo(910,h-165);c.stroke();
 c.fillStyle=t.ink;c.font='bold 19px sans-serif';c.fillText(t.footer,540,h-115);
 c.fillStyle=t.muted;c.font='23px sans-serif';c.fillText('tinysitestudios.com/accomplishments',540,h-75);
 $('#download').disabled=false;$('#native-share').disabled=false;resolve();};
 img.onerror=()=>{if(renderVersion===drawCard.version)toast('Could not render this card. Please choose a style to try again.');resolve()};
 img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(medal(snapshot.category,snapshot.title).replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" '));
 });
}
drawCard.version=0;
drawCard.ready=Promise.resolve();
document.fonts.ready.then(()=>{if(current&&!$('#share-dialog').hidden&&$('#share-dialog').open)drawCard()});
const cardBlob=async()=>{let pending;do{pending=drawCard.ready;await pending}while(pending!==drawCard.ready);if($('#download').disabled)throw new Error('Image unavailable');return new Promise((resolve,reject)=>$('#social-canvas').toBlob(b=>b?resolve(b):reject(new Error('Image unavailable')),'image/png'))};
$('#download').addEventListener('click',async()=>{try{const blob=await cardBlob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='petty-accomplishments-'+$('input[name="card-style"]:checked').value+'-'+$('#layout').value+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('Your award card is ready. Attach it to your post or Story.')}catch{toast('Could not create the image. Please try again.')}});
$('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#caption').value);toast('Announcement copied. The world awaits.')}catch{$('#caption').focus();$('#caption').select();toast('Select and copy the highlighted caption.')}});
if(navigator.canShare&&navigator.canShare({files:[new File(['test'],'test.png',{type:'image/png'})]})){$('#native-share').hidden=false;$('#native-share').addEventListener('click',async()=>{try{const file=new File([await cardBlob()],'my-petty-accomplishment.png',{type:'image/png'});await navigator.share({files:[file],title:current.title,text:$('#caption').value})}catch(e){if(e.name!=='AbortError')toast('Sharing is unavailable here. Download the card and copy your caption.')}})}

const badgeExamples=[{category:'Domestic Affairs',index:0,victory:'Put the laundry away',emoji:'🧺',label:'Laundry legend'},{category:'Administrative Bravery',index:1,victory:'Answered that overdue email',emoji:'💌',label:'Inbox hero'},{category:'Social Courage',index:0,victory:'Asked for help',emoji:'💬',label:'Brave little ask'},{category:'Personal Maintenance',index:0,victory:'Did one thing on a hard day',emoji:'🌈',label:'Showed up'},{category:'Personal Maintenance',index:2,victory:'Took a well-deserved break',emoji:'🌙',label:'Rest royalty'},{category:'Miscellaneous Excellence',index:1,victory:'Finally did the thing I was putting off',emoji:'⏰',label:'Eventually icon'}];
let spotlightIndex=0;
$('#badge-playground').innerHTML=badgeExamples.map((b,i)=>`<button class="badge-chip badge-color-${i}" data-badge-index="${i}" aria-pressed="${i===0}" aria-label="Preview ${escapeHTML(b.label)}">${medal(b.category,honors[b.category][b.index][0])}<strong>${escapeHTML(b.label)}</strong><span class="chip-emoji" aria-hidden="true">${b.emoji}</span></button>`).join('');
function spotlightBadge(index){spotlightIndex=index;const b=badgeExamples[index],[title,citation]=honors[b.category][b.index];$('#hero-medal').innerHTML=medal(b.category,title);$('#spotlight-title').textContent=title;$('#spotlight-citation').textContent=citation;$('#spotlight-card').classList.remove('pop');void $('#spotlight-card').offsetWidth;$('#spotlight-card').classList.add('pop');$$('[data-badge-index]').forEach(e=>e.setAttribute('aria-pressed',String(Number(e.dataset.badgeIndex)===index)));$('#badge-detail').innerHTML=`<span class="detail-emoji" aria-hidden="true">${b.emoji}</span><span><strong>${escapeHTML(title)}</strong><small>${escapeHTML(citation)}</small></span><button class="button" id="claim-preview">I did this! ↗</button>`;$('#claim-preview').addEventListener('click',()=>declare(b.victory,b.category))}
$$('[data-badge-index]').forEach(button=>button.addEventListener('click',()=>spotlightBadge(Number(button.dataset.badgeIndex))));
$('#spotlight-next').addEventListener('click',()=>spotlightBadge((spotlightIndex+1)%badgeExamples.length));
$('#meet-badges').addEventListener('click',()=>{$('#badge-lab-title').focus({preventScroll:true});$('.badge-lab').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})});
spotlightBadge(0);
