const weddingDate = new Date("2027-08-14T17:00:00-05:00");
function tick(){const diff=Math.max(0,weddingDate-Date.now()),unit=1000*60*60*24;document.querySelector("[data-days]").textContent=String(Math.floor(diff/unit)).padStart(3,"0");document.querySelector("[data-hours]").textContent=String(Math.floor(diff/unit*24)%24).padStart(2,"0");document.querySelector("[data-minutes]").textContent=String(Math.floor(diff/60000)%60).padStart(2,"0")}
tick();setInterval(tick,60000);
const header=document.querySelector(".site-header"),menu=document.querySelector(".menu-button");menu.addEventListener("click",()=>{const open=header.classList.toggle("open");menu.setAttribute("aria-expanded",open)});
const places={hotel:["01 / CHECK IN","The Gray Hotel","Our home base in the Loop. Room block details are waiting in your invitation email.","Chicago Loop"],venue:["02 / WEDDING","The Atlas","Rooftop vows, gallery dinner, and a late-night dance floor above the river.","Chicago Riverwalk"],welcome:["03 / FRIDAY","Welcome at Orbit","Meet us for drinks, tiny bites, and the first skyline view of the weekend.","West Loop Chicago"],brunch:["04 / SUNDAY","Lula Brunch","A very good breakfast and one more round of hugs before you go.","Logan Square Chicago"]};
document.querySelectorAll(".map-pin").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".map-pin").forEach(x=>x.classList.remove("active"));button.classList.add("active");const p=places[button.dataset.place];document.querySelector("[data-place-number]").textContent=p[0];document.querySelector("[data-place-title]").textContent=p[1];document.querySelector("[data-place-copy]").textContent=p[2];document.querySelector("[data-place-map]").href=`https://maps.google.com/?q=${encodeURIComponent(p[3])}`}));
const playlist=document.querySelector(".playlist"),play=document.querySelector(".play-button");play.addEventListener("click",()=>{const on=playlist.classList.toggle("playing");play.setAttribute("aria-pressed",on);play.querySelector("span").textContent=on?"Ⅱ":"▶"});
document.querySelectorAll("[data-frame]").forEach(button=>button.addEventListener("click",()=>{document.querySelector(".booth-preview").className=`booth-preview ${button.dataset.frame}`}));
const dialog=document.querySelector(".rsvp-dialog");document.querySelectorAll("[data-open-rsvp]").forEach(button=>button.addEventListener("click",()=>dialog.showModal()));document.querySelector(".dialog-close").addEventListener("click",()=>dialog.close());dialog.querySelector("form").addEventListener("submit",event=>{event.preventDefault();dialog.querySelector("output").textContent="RSVP noted for this demo — thank you.";setTimeout(()=>dialog.close(),1800)});
