/* Coverage is positive evidence, not a complete store census. Missing area = unverified,
   never "no store exists". Branch existence does not verify reward participation. */
const locationCoverage={};
function cover(id,areas,url,address=''){for(const area of areas)(locationCoverage[id]??={})[area]={url,address,checked:'2026-10-06'}}
cover('bundt',['Houston','Katy','Cypress','The Woodlands','Humble','Sugar Land','Pearland','Baytown','League City'],'https://www.nothingbundtcakes.com/find-a-bakery/tx/');
cover('sephora',['Houston','Katy','Cypress','The Woodlands','Humble','Sugar Land'],'https://www.sephora.com/happening/storelist');
cover('audit-ulta-beauty',['Houston','Katy','The Woodlands','Humble','Sugar Land','League City'],'https://www.ulta.com/stores/directory');
cover('chuys',['Houston'],'https://www.chuys.com/locations/tx/houston/houston-tx-bunker-hill/6085');
cover('chuys',['Katy'],'https://www.chuys.com/locations/tx/katy/katy-tx/6026');
cover('chuys',['Sugar Land'],'https://www.chuys.com/locations/tx/sugar-land/sugarland-tx/6054');
cover('chuys',['Humble'],'https://www.chuys.com/locations/tx/humble/humble-tx/6011');
cover('tacos',['Houston'],'https://www.tacosagogo.com/locations/','3704 Main St, Houston, TX 77002');
cover('audit-velvet-taco',['Houston'],'https://www.velvettaco.com/location/the-heights/','2001 N Shepherd Drive, Houston, TX 77008');
cover('audit-velvet-taco',['The Woodlands'],'https://www.velvettaco.com/location/the-woodlands/','9120 Gosling Road, The Woodlands, TX 77381');
cover('audit-velvet-taco',['Sugar Land'],'https://www.velvettaco.com/sitemap/');
cover('sephora',['The Woodlands'],'https://www.sephora.com/happening/stores/market-street','9595 Six Pines Dr, Ste 810, The Woodlands, TX 77380');
cover('sephora',['Houston'],'https://www.sephora.com/happening/stores/river-oaks','1987 W Gray St, Houston, TX');
cover('chickfila',['Houston'],'https://www.chick-fil-a.com/locations/tx/45-woodridge','7007 Gulf Fwy, Houston, TX 77087');
cover('chickfila',['The Woodlands'],'https://www.chick-fil-a.com/locations/tx/the-woodlands-mall','1201 Lake Woodlands Dr, Ste 2146, The Woodlands, TX 77380');
cover('bundt',['The Woodlands'],'https://www.nothingbundtcakes.com/find-a-bakery/tx/thewoodlands/bakery-51.html');
cover('chilis',['The Woodlands'],'https://www.chilis.com/locations/us/texas/the-woodlands/woodlands','1110 Lake Woodlands Dr, The Woodlands, TX 77380');
cover('audit-crumbl',['The Woodlands'],'https://crumblcookies.com/stores/tx/txwoodlands','9595 Six Pines Dr, Ste 1075, The Woodlands, TX 77380');
cover('audit-ulta-beauty',['The Woodlands'],'https://www.ulta.com/stores/the-woodlands-tx-1473','1900 Lake Woodlands Dr, Ste 800, The Woodlands, TX 77380');
cover('olivegarden',['Houston'],'https://www.olivegarden.com/locations/tx/houston/houston-gulfgate-center/6485','522 Gulfgate Center Mall, Houston, TX 77087');
cover('audit-torchys-tacos',['The Woodlands'],'https://www.torchystacos.com/woodlands/order','4747 Research Forest Drive, #475, The Woodlands, TX 77381');
cover('audit-torchys-tacos',['Houston'],'https://torchystacos.com/memorial-city/order');
cover('audit-panera',['Houston'],'https://www.panerabread.com/en-us/cafe/locations/tx/houston/8845-w-loop-s','8845 W Loop S, Houston, TX');
cover('audit-dutch-bros',['Houston','Sugar Land'],'https://www.dutchbros.com/locations/');


/* Expanded official location audit, October 6, 2026. Reward eligibility is separate. */
cover("audit-ihop",["Houston"],"https://restaurants.ihop.com/en-us/tx/","");
cover("audit-ihop",["Humble"],"https://restaurants.ihop.com/en-us/tx/","");
cover("audit-ihop",["Katy"],"https://restaurants.ihop.com/en-us/tx/katy/","24515 Katy Frwy, Katy, TX 77494");
cover("audit-ihop",["Cypress"],"https://restaurants.ihop.com/en-us/tx/cypress/","26301 Northwest Hwy, Cypress, TX 77429");
cover("audit-ihop",["Pearland"],"https://restaurants.ihop.com/en-us/tx/","");
cover("audit-ihop",["Sugar Land"],"https://restaurants.ihop.com/en-us/tx/","");
cover("audit-ihop",["Baytown"],"https://restaurants.ihop.com/en-us/tx/","");
cover("audit-smoothie-king",["Houston"],"https://locations.smoothieking.com/site-map/us/tx/houston/","1923 Taylor St., Houston, TX 77007");
cover("audit-smoothie-king",["Katy"],"https://locations.smoothieking.com/site-map/us/tx/","");
cover("audit-smoothie-king",["Cypress"],"https://locations.smoothieking.com/site-map/us/tx/","");
cover("audit-smoothie-king",["The Woodlands"],"https://locations.smoothieking.com/site-map/us/tx/the-woodlands/","1440-B Lake Woodlands Drive, The Woodlands, TX 77380");
cover("audit-smoothie-king",["Humble"],"https://locations.smoothieking.com/site-map/us/tx/","");
cover("audit-smoothie-king",["Sugar Land"],"https://locations.smoothieking.com/site-map/us/tx/","");
cover("audit-smoothie-king",["Pearland"],"https://locations.smoothieking.com/site-map/us/tx/","");
cover("audit-smoothie-king",["Baytown"],"https://locations.smoothieking.com/site-map/us/tx/","");
cover("audit-smoothie-king",["League City"],"https://locations.smoothieking.com/site-map/us/tx/league-city/","1620 W FM 646 Rd., Ste. G, League City, TX 77573");
cover("audit-chipotle",["Houston"],"https://locations.chipotle.com/tx/houston/909-texas-st","909 Texas St, Houston, TX");
cover("audit-chipotle",["Katy"],"https://locations.chipotle.com/tx","");
cover("audit-chipotle",["Cypress"],"https://locations.chipotle.com/tx","");
cover("audit-chipotle",["Humble"],"https://locations.chipotle.com/tx","");
cover("audit-chipotle",["Sugar Land"],"https://locations.chipotle.com/tx","");
cover("audit-chipotle",["Pearland"],"https://locations.chipotle.com/tx","");
cover("audit-chipotle",["Baytown"],"https://locations.chipotle.com/tx","");
cover("audit-chipotle",["League City"],"https://locations.chipotle.com/tx","");
cover("audit-auntie-annes",["Houston"],"https://locations.auntieannes.com/tx/houston/5015-westheimer-rd","5015 Westheimer Rd, Suite K-107A, Houston, TX 77056");
cover("audit-auntie-annes",["Cypress"],"https://locations.auntieannes.com/tx","");
cover("audit-auntie-annes",["The Woodlands"],"https://locations.auntieannes.com/tx","");
cover("audit-auntie-annes",["Sugar Land"],"https://locations.auntieannes.com/tx","");
cover("audit-auntie-annes",["Pearland"],"https://locations.auntieannes.com/tx","");
cover("audit-red-robin",["Houston"],"https://www.redrobin.com/locations/tx/houston/marqe-504","");
cover("audit-red-robin",["Katy"],"https://www.redrobin.com/locations/tx/katy/katy-503","");
cover("audit-red-robin",["Pearland"],"https://www.redrobin.com/locations/tx/pearland/pearland-511","");
cover("audit-outback-steakhouse",["Houston"],"https://locations.outback.com/texas/houston/10001-westheimer-road","10001 Westheimer Road, Houston, TX");
cover("audit-outback-steakhouse",["Katy"],"https://locations.outback.com/texas","");
cover("audit-outback-steakhouse",["Baytown"],"https://locations.outback.com/texas","");
cover("audit-cold-stone-creamery",["Houston"],"https://www.coldstonecreamery.com/stores/ice-cream-near-houston/24225","7620 Katy Fwy, Ste 425, Houston, TX 77024");
cover("audit-einstein-bros-bagels",["Houston"],"https://locations.einsteinbros.com/us/tx/houston/3111-barker-cypress-road","3111 Barker Cypress Road, Houston, TX 77084");
cover("audit-texas-roadhouse",["Houston"],"https://www.texasroadhouse.com/locations/95-houstontx","13345 FM 1960 Road West, Houston, TX 77065");
cover("audit-ikea",["Houston"],"https://www.ikea.com/us/en/stores/houston/","7810 Katy Freeway, Houston, TX 77024");
cover("audit-grimaldis-pizzeria",["Katy"],"https://www.grimaldispizzeria.com/location/cinco-ranch-katy/","2643 Commercial Center Blvd. Ste. C390, Katy, TX 77494");
cover("audit-cinemark",["Houston"],"https://www.cinemark.com/theatres/tx-houston/cinemark-memorial-city","");
cover("audit-cold-stone-creamery",["Sugar Land"],"https://www.coldstonecreamery.com/stores/ice-cream-near-sugar-land/23958","11575 S Texas 6, Ste 14, Sugar Land, TX 77498");
cover("audit-jersey-mikes",["Houston"],"https://www.jerseymikes.com/15180/houston-tx","9650 Westheimer Road, Suite 600, Houston, TX 77063");
cover("audit-firehouse-subs",["Houston"],"https://www.firehousesubs.com/store-locator/store/10305/1214-w-43rd-street--houston--texas--77018","1214 W 43rd Street, Houston, TX 77018");
cover("audit-subway",["Houston"],"https://restaurants.subway.com/united-states/tx/houston/5156-richmond-ave","5156 Richmond Ave, Houston, TX 77056");
cover("audit-subway",["Katy"],"https://restaurants.subway.com/united-states/tx","");
cover("audit-subway",["Cypress"],"https://restaurants.subway.com/united-states/tx","");
cover("audit-subway",["The Woodlands"],"https://restaurants.subway.com/united-states/tx","");
cover("audit-subway",["Humble"],"https://restaurants.subway.com/united-states/tx","");
cover("audit-subway",["Sugar Land"],"https://restaurants.subway.com/united-states/tx","");
cover("audit-subway",["Pearland"],"https://restaurants.subway.com/united-states/tx","");
cover("audit-subway",["Baytown"],"https://restaurants.subway.com/united-states/tx","");
cover("audit-subway",["League City"],"https://restaurants.subway.com/united-states/tx","");
cover("audit-papa-johns",["Houston"],"https://locations.papajohns.com/united-states/tx/77087/houston/4004-broadway-st","4004 Broadway St, Houston, TX 77087");
cover("audit-papa-johns",["Katy"],"https://locations.papajohns.com/united-states/tx","");
cover("audit-papa-johns",["Cypress"],"https://locations.papajohns.com/united-states/tx","");
cover("audit-papa-johns",["The Woodlands"],"https://locations.papajohns.com/united-states/tx","");
cover("audit-papa-johns",["Humble"],"https://locations.papajohns.com/united-states/tx","");
cover("audit-papa-johns",["Sugar Land"],"https://locations.papajohns.com/united-states/tx","");
cover("audit-papa-johns",["Pearland"],"https://locations.papajohns.com/united-states/tx","");
cover("audit-papa-johns",["Baytown"],"https://locations.papajohns.com/united-states/tx","");
cover("audit-papa-johns",["League City"],"https://locations.papajohns.com/united-states/tx","");
cover("audit-tropical-smoothie-cafe",["Houston"],"https://locations.tropicalsmoothiecafe.com/tx/houston/1717-west-34th-st","1717 West 34th St, Houston, TX");
cover("audit-tropical-smoothie-cafe",["Katy"],"https://locations.tropicalsmoothiecafe.com/tx","");
cover("audit-tropical-smoothie-cafe",["Cypress"],"https://locations.tropicalsmoothiecafe.com/tx","");
cover("audit-tropical-smoothie-cafe",["Humble"],"https://locations.tropicalsmoothiecafe.com/tx","");
cover("audit-tropical-smoothie-cafe",["Sugar Land"],"https://locations.tropicalsmoothiecafe.com/tx","");
cover("audit-tropical-smoothie-cafe",["Pearland"],"https://locations.tropicalsmoothiecafe.com/tx","");
cover("audit-tropical-smoothie-cafe",["Baytown"],"https://locations.tropicalsmoothiecafe.com/tx","");
cover("audit-tropical-smoothie-cafe",["League City"],"https://locations.tropicalsmoothiecafe.com/tx","");
cover("audit-menchies",["Houston"],"https://www.menchies.com/location/west-19th-street-center/","512 W. 19th Street, Houston, TX");
cover("audit-7-eleven",["Houston"],"https://www.7-eleven.com/locations/tx/houston/18555-state-hwy-249-36579","18555 State Highway 249, Houston, TX");
cover("audit-gap",["Houston"],"https://www.gap.com/stores/tx/houston/gap-401.html","5085 Westheimer Road #2695, Houston, TX 77056");
cover("audit-ben-and-jerrys",["Houston"],"https://www.benjerry.com/houston","5515 Kirby Drive, Houston, TX 77005");
cover("hhc",["Houston"],"https://www.hhc.ooo/locations/houston","10111 Louetta Rd #800, Houston, TX 77070");
cover("hhc",["Katy"],"https://www.hhc.ooo/locations/houston-metro","23501 Cinco Ranch Blvd R140, Katy, TX 77494");
cover("dennys",["Houston"],"https://locations.dennys.com/tx/houston/247917","9766-B Katy Frwy, Houston, TX");
cover("dennys",["Katy"],"https://locations.dennys.com/tx/katy/247836","2405 Texmati Dr, Katy, TX");
cover("audit-qdoba",["Humble"],"https://locations.qdoba.com/us/tx/humble/7405-fm-1960-road-e","7405 FM 1960 Road E, Humble, TX");
cover("audit-starbucks",["Sugar Land"],"https://www.sugarlandtownsquare.com/stores/starbucks-coffee/","16089 City Walk, Sugar Land, TX");
cover("audit-grimaldis-pizzeria",["Houston"],"https://www.grimaldispizzeria.com/location/citycentre/","12848 Queensbury Lane, Suite 101, Houston, TX 77024");
