export const defaults = Object.freeze({heartfelt:8,funny:4,traditional:3,spiritual:0,unconventional:5,belief:'secular'});
export const presets = Object.freeze({heartfelt:defaults,simple:{heartfelt:5,funny:2,traditional:6,spiritual:0,unconventional:2,belief:'secular'},playful:{heartfelt:6,funny:8,traditional:2,spiritual:0,unconventional:8,belief:'secular'}});
export const packageNames = Object.freeze({unsure:'Help choosing a ceremony',official:'Make It Official · $125 founding rate',simple:'Simple + Sweet · $195 founding rate',story:'Your Story · $295 founding rate',full:'The Full Love Story · $395 founding rate',words:'Wedding Words / vow or speech help',renewal:'Vow renewal · from $195'});
export const beliefNames = Object.freeze({secular:'Secular / nonreligious',spiritual:'Spiritual',religious:'Religious',interfaith:'Interfaith / blended traditions',unsure:'Let’s talk about beliefs and traditions'});
export const dimensions = ['heartfelt','funny','traditional','spiritual','unconventional'];
export function describeVibe(state) {
  const s={...defaults,...state};
  const heartfelt=s.heartfelt>=7;const playful=s.funny>=7;const unique=s.unconventional>=7;
  const title=playful?(heartfelt?'Happy tears.\nBig laughs.':'Your people.\nYour kind of funny.'):heartfelt?'Big feelings.\nEasy connection.':s.traditional>=7?'Familiar moments.\nYour own meaning.':unique?'A little unexpected.\nCompletely you.':'Simple moments.\nReal meaning.';
  const tone=heartfelt?'A deeply heartfelt ceremony with space for emotion':s.heartfelt<=3?'A light, sincere ceremony that keeps the sentiment understated':'A warm ceremony with a thoughtful balance of sentiment';
  const humor=playful?'plenty of natural humor and your favorite inside jokes':s.funny<=2?'a mostly sincere tone':'a few easy laughs';
  const tradition=s.traditional>=7?'familiar ceremony traditions':s.traditional<=3?'a relaxed, less traditional flow':'a blend of familiar moments and personal touches';
  const personal=unique?'Distinctive readings, rituals, or unexpected touches can make it unmistakably yours.':s.unconventional<=3?'We’ll keep the structure familiar and let your words make it personal.':'There’s room to make the details your own.';
  const beliefs=s.belief==='secular'?(s.spiritual===0?'No religious or spiritual elements requested.':`You’ve selected secular, with spiritual interest at ${s.spiritual}/10; we’ll talk through what that mix means to you.`):s.belief==='religious'?'We’ll discuss the religious readings and traditions that matter to you.':s.belief==='interfaith'?'We’ll talk through a respectful blend of your beliefs and traditions.':s.belief==='unsure'?'We’ll explore what feels right for your beliefs and traditions.':s.spiritual>=7?'Spiritual meaning can take a central place in the ceremony.':s.spiritual===0?'You’ve selected spiritual, with no spiritual elements on the slider yet; we’ll clarify what you have in mind.':'We can weave in gentle spiritual reflections, without assuming a particular religion.';
  const sample=playful?'“A life together is made of big promises and very small negotiations—like who gets the good pillow. Today, you choose all of it, and each other.”':heartfelt?'“Somewhere between the first hello and the ordinary days that followed, you became each other’s person. Today, you put words to a choice your hearts have already made.”':s.traditional>=7?'“Today, surrounded by the people who love you, you promise to meet life together—with patience, kindness, and a love you choose again and again.”':unique?'“There is no single way to build a life together. The beautiful part is that you get to choose yours—and today is one of those choices.”':'“Marriage begins with a promise. To show up, to listen, to laugh together, and to keep choosing each other in the life you make from here.”';
  const tags=[heartfelt?'Heartfelt':s.heartfelt<=3?'Light & sincere':'Warm & personal',playful?'Playful':s.funny<=2?'Mostly sincere':'Easy laughter',s.traditional>=7?'Classic moments':s.traditional<=3?'Relaxed flow':'A little of both',beliefNames[s.belief]];
  if(unique)tags.push('Unmistakably yours');
  return {title,description:`${tone}, ${humor}, and ${tradition}. ${personal} ${beliefs}`,sample,tags};
}
export function createBrief(state,selected='unsure') {
  return ['Ceremonies by Caitlin inquiry',`Interested in: ${packageNames[selected]||packageNames.unsure}`,`Beliefs / traditions: ${beliefNames[state.belief]||beliefNames.unsure}`,'Ceremony vibe: '+dimensions.map(key=>`${key[0].toUpperCase()+key.slice(1)} ${state[key]}/10`).join(' · '),'','Our names / pronouns:','Wedding date / time:','Venue / city:','Guest count (optional):','Anything else Caitlin should know:'].join('\n');
}
