const date=new Date("2027-04-24T17:00:00-04:00");function tick(){const d=Math.max(0,date-Date.now());document.querySelector("[data-days]").textContent=String(Math.floor(d/86400000)).padStart(3,"0");document.querySelector("[data-hours]").textContent=String(Math.floor(d/3600000)%24).padStart(2,"0");document.querySelector("[data-minutes]").textContent=String(Math.floor(d/60000)%60).padStart(2,"0")}tick();setInterval(tick,60000);
const head=document.querySelector("body>header"),navButton=document.querySelector(".nav-button");navButton.addEventListener("click",()=>{const open=head.classList.toggle("open");navButton.setAttribute("aria-expanded",open)});
const stories={first:["MAY 2021","A borrowed umbrella","One sudden storm, one tiny coffee shop awning, and a conversation neither of us wanted to end."],date:["JUNE 2021","Tacos, then dancing","Dinner became a record shop, which became a tiny dance floor in Rose’s kitchen."],home:["SEPTEMBER 2023","The yellow door","We painted it twice, planted too many herbs, and made a home with room for everyone."],yes:["APRIL 2026","A picnic and a question","Lena packed the sandwiches. Rose packed a ring. Both of us cried before dessert."],garden:["APRIL 2027","Love in full bloom","Now the path leads here—to all of you, gathered under the trees in Charleston."]};
document.querySelectorAll("[data-stop]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-stop]").forEach(x=>x.classList.remove("active"));button.classList.add("active");const s=stories[button.dataset.stop];document.querySelector("[data-story-date]").textContent=s[0];document.querySelector("[data-story-title]").textContent=s[1];document.querySelector("[data-story-copy]").textContent=s[2]}));
const places={lawn:["01 · CEREMONY LAWN","Under the live oak","Vows begin at five. The lawn is level, shady, and fully accessible from the main path."],champagne:["02 · CHAMPAGNE GARDEN","Meet us by the roses","Cold bubbles, lawn games, and tiny bites live here between vows and dinner."],dinner:["03 · DINNER TENT","Supper under sailcloth","Your table assignment will greet you at the entrance. The dance floor is just beyond."],quiet:["04 · QUIET SPACE","The Wren House library","A calm, cool room is open all evening for anyone who needs a breather."],access:["05 · ACCESSIBILITY","Easy garden access","A paved path reaches every event area. Accessible parking is beside the east gate."]};
document.querySelectorAll("[data-garden]").forEach(button=>button.addEventListener("click",()=>{const s=places[button.dataset.garden];document.querySelector("[data-garden-label]").textContent=s[0];document.querySelector("[data-garden-title]").textContent=s[1];document.querySelector("[data-garden-copy]").textContent=s[2]}));
const messages={rose:"Your people know they are loved because you show them.",daisy:"Joy keeps finding you—let it.",lavender:"You bring calm into every room you enter.",sunflower:"Keep turning toward what feels warm and true."};document.querySelectorAll("[data-flower]").forEach(button=>button.addEventListener("click",()=>document.querySelector(".flower output").textContent=messages[button.dataset.flower]));
document.querySelector(".guestbook form").addEventListener("submit",event=>{event.preventDefault();const [name,note]=event.target.querySelectorAll("input,textarea");const quote=document.createElement("blockquote");quote.innerHTML=`“${note.value.replace(/[<>]/g,"")}”<cite>— ${name.value.replace(/[<>]/g,"")}</cite>`;document.querySelector(".notes").prepend(quote);event.target.reset()});
document.querySelector(".rsvp form").addEventListener("submit",event=>{event.preventDefault();event.target.querySelector("output").textContent="Your demo RSVP has been gathered with love. Thank you!";event.target.reset()});
